// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: star/StarShopMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.star";

export interface StarShopMsg {
  goodId: number;
  result: number;
  num: number;
}

function createBaseStarShopMsg(): StarShopMsg {
  return { goodId: 0, result: 0, num: 0 };
}

export const StarShopMsg: MessageFns<StarShopMsg> = {
  encode(message: StarShopMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.goodId !== 0) {
      writer.uint32(8).int32(message.goodId);
    }
    if (message.result !== 0) {
      writer.uint32(16).int32(message.result);
    }
    if (message.num !== 0) {
      writer.uint32(24).int32(message.num);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StarShopMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStarShopMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.goodId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.result = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.num = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StarShopMsg {
    return {
      goodId: isSet(object.goodId) ? globalThis.Number(object.goodId) : 0,
      result: isSet(object.result) ? globalThis.Number(object.result) : 0,
      num: isSet(object.num) ? globalThis.Number(object.num) : 0,
    };
  },

  toJSON(message: StarShopMsg): unknown {
    const obj: any = {};
    if (message.goodId !== 0) {
      obj.goodId = Math.round(message.goodId);
    }
    if (message.result !== 0) {
      obj.result = Math.round(message.result);
    }
    if (message.num !== 0) {
      obj.num = Math.round(message.num);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StarShopMsg>, I>>(base?: I): StarShopMsg {
    return StarShopMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StarShopMsg>, I>>(object: I): StarShopMsg {
    const message = createBaseStarShopMsg();
    message.goodId = object.goodId ?? 0;
    message.result = object.result ?? 0;
    message.num = object.num ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
