// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: uiplay/UserUiPlayListMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.uiplay";

export interface UserUiPlayListMsg {
  uiPlayInfoList: number[];
  uiPlayRewardCount: number;
}

function createBaseUserUiPlayListMsg(): UserUiPlayListMsg {
  return { uiPlayInfoList: [], uiPlayRewardCount: 0 };
}

export const UserUiPlayListMsg: MessageFns<UserUiPlayListMsg> = {
  encode(message: UserUiPlayListMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.uiPlayInfoList) {
      writer.int32(v);
    }
    writer.join();
    if (message.uiPlayRewardCount !== 0) {
      writer.uint32(16).int32(message.uiPlayRewardCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserUiPlayListMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserUiPlayListMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.uiPlayInfoList.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.uiPlayInfoList.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.uiPlayRewardCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserUiPlayListMsg {
    return {
      uiPlayInfoList: globalThis.Array.isArray(object?.uiPlayInfoList)
        ? object.uiPlayInfoList.map((e: any) => globalThis.Number(e))
        : [],
      uiPlayRewardCount: isSet(object.uiPlayRewardCount) ? globalThis.Number(object.uiPlayRewardCount) : 0,
    };
  },

  toJSON(message: UserUiPlayListMsg): unknown {
    const obj: any = {};
    if (message.uiPlayInfoList?.length) {
      obj.uiPlayInfoList = message.uiPlayInfoList.map((e) => Math.round(e));
    }
    if (message.uiPlayRewardCount !== 0) {
      obj.uiPlayRewardCount = Math.round(message.uiPlayRewardCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserUiPlayListMsg>, I>>(base?: I): UserUiPlayListMsg {
    return UserUiPlayListMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserUiPlayListMsg>, I>>(object: I): UserUiPlayListMsg {
    const message = createBaseUserUiPlayListMsg();
    message.uiPlayInfoList = object.uiPlayInfoList?.map((e) => e) || [];
    message.uiPlayRewardCount = object.uiPlayRewardCount ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
