// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: item/BottleScoreMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.item";

export interface BottleScoreMsg {
  treeStatus: string;
  count: number;
  openView: boolean;
  alterBottle: boolean;
}

function createBaseBottleScoreMsg(): BottleScoreMsg {
  return { treeStatus: "", count: 0, openView: false, alterBottle: false };
}

export const BottleScoreMsg: MessageFns<BottleScoreMsg> = {
  encode(message: BottleScoreMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.treeStatus !== "") {
      writer.uint32(10).string(message.treeStatus);
    }
    if (message.count !== 0) {
      writer.uint32(16).int32(message.count);
    }
    if (message.openView !== false) {
      writer.uint32(24).bool(message.openView);
    }
    if (message.alterBottle !== false) {
      writer.uint32(32).bool(message.alterBottle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BottleScoreMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBottleScoreMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.treeStatus = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.openView = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.alterBottle = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BottleScoreMsg {
    return {
      treeStatus: isSet(object.treeStatus) ? globalThis.String(object.treeStatus) : "",
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      openView: isSet(object.openView) ? globalThis.Boolean(object.openView) : false,
      alterBottle: isSet(object.alterBottle) ? globalThis.Boolean(object.alterBottle) : false,
    };
  },

  toJSON(message: BottleScoreMsg): unknown {
    const obj: any = {};
    if (message.treeStatus !== "") {
      obj.treeStatus = message.treeStatus;
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.openView !== false) {
      obj.openView = message.openView;
    }
    if (message.alterBottle !== false) {
      obj.alterBottle = message.alterBottle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BottleScoreMsg>, I>>(base?: I): BottleScoreMsg {
    return BottleScoreMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BottleScoreMsg>, I>>(object: I): BottleScoreMsg {
    const message = createBaseBottleScoreMsg();
    message.treeStatus = object.treeStatus ?? "";
    message.count = object.count ?? 0;
    message.openView = object.openView ?? false;
    message.alterBottle = object.alterBottle ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
