// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: leed/LeedData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.leed";

export interface LeedData {
  templateId: number;
  userId: number;
  currentCount: number;
  beginDate: string;
  isComplete: boolean;
}

function createBaseLeedData(): LeedData {
  return { templateId: 0, userId: 0, currentCount: 0, beginDate: "", isComplete: false };
}

export const LeedData: MessageFns<LeedData> = {
  encode(message: LeedData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.templateId !== 0) {
      writer.uint32(8).int32(message.templateId);
    }
    if (message.userId !== 0) {
      writer.uint32(16).int32(message.userId);
    }
    if (message.currentCount !== 0) {
      writer.uint32(24).int32(message.currentCount);
    }
    if (message.beginDate !== "") {
      writer.uint32(34).string(message.beginDate);
    }
    if (message.isComplete !== false) {
      writer.uint32(40).bool(message.isComplete);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeedData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeedData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.templateId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.currentCount = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.beginDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isComplete = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LeedData {
    return {
      templateId: isSet(object.templateId) ? globalThis.Number(object.templateId) : 0,
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      currentCount: isSet(object.currentCount) ? globalThis.Number(object.currentCount) : 0,
      beginDate: isSet(object.beginDate) ? globalThis.String(object.beginDate) : "",
      isComplete: isSet(object.isComplete) ? globalThis.Boolean(object.isComplete) : false,
    };
  },

  toJSON(message: LeedData): unknown {
    const obj: any = {};
    if (message.templateId !== 0) {
      obj.templateId = Math.round(message.templateId);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.currentCount !== 0) {
      obj.currentCount = Math.round(message.currentCount);
    }
    if (message.beginDate !== "") {
      obj.beginDate = message.beginDate;
    }
    if (message.isComplete !== false) {
      obj.isComplete = message.isComplete;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LeedData>, I>>(base?: I): LeedData {
    return LeedData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LeedData>, I>>(object: I): LeedData {
    const message = createBaseLeedData();
    message.templateId = object.templateId ?? 0;
    message.userId = object.userId ?? 0;
    message.currentCount = object.currentCount ?? 0;
    message.beginDate = object.beginDate ?? "";
    message.isComplete = object.isComplete ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
