// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: leed/LeedFinishedRspMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.leed";

export interface LeedFinishedRspMsg {
  result: boolean;
  site: number;
  leedProcess: number;
}

function createBaseLeedFinishedRspMsg(): LeedFinishedRspMsg {
  return { result: false, site: 0, leedProcess: 0 };
}

export const LeedFinishedRspMsg: MessageFns<LeedFinishedRspMsg> = {
  encode(message: LeedFinishedRspMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== false) {
      writer.uint32(8).bool(message.result);
    }
    if (message.site !== 0) {
      writer.uint32(16).int32(message.site);
    }
    if (message.leedProcess !== 0) {
      writer.uint32(24).int32(message.leedProcess);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeedFinishedRspMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeedFinishedRspMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.result = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.site = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.leedProcess = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LeedFinishedRspMsg {
    return {
      result: isSet(object.result) ? globalThis.Boolean(object.result) : false,
      site: isSet(object.site) ? globalThis.Number(object.site) : 0,
      leedProcess: isSet(object.leedProcess) ? globalThis.Number(object.leedProcess) : 0,
    };
  },

  toJSON(message: LeedFinishedRspMsg): unknown {
    const obj: any = {};
    if (message.result !== false) {
      obj.result = message.result;
    }
    if (message.site !== 0) {
      obj.site = Math.round(message.site);
    }
    if (message.leedProcess !== 0) {
      obj.leedProcess = Math.round(message.leedProcess);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LeedFinishedRspMsg>, I>>(base?: I): LeedFinishedRspMsg {
    return LeedFinishedRspMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LeedFinishedRspMsg>, I>>(object: I): LeedFinishedRspMsg {
    const message = createBaseLeedFinishedRspMsg();
    message.result = object.result ?? false;
    message.site = object.site ?? 0;
    message.leedProcess = object.leedProcess ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
