// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: building/OrderInfoMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.building";

export interface OrderInfoMsg {
  orderId: number;
  orderType: number;
  remainTime: number;
  userId: number;
  beginTime: string;
  needTime: number;
}

function createBaseOrderInfoMsg(): OrderInfoMsg {
  return { orderId: 0, orderType: 0, remainTime: 0, userId: 0, beginTime: "", needTime: 0 };
}

export const OrderInfoMsg: MessageFns<OrderInfoMsg> = {
  encode(message: OrderInfoMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== 0) {
      writer.uint32(8).int32(message.orderId);
    }
    if (message.orderType !== 0) {
      writer.uint32(16).int32(message.orderType);
    }
    if (message.remainTime !== 0) {
      writer.uint32(24).int32(message.remainTime);
    }
    if (message.userId !== 0) {
      writer.uint32(32).int32(message.userId);
    }
    if (message.beginTime !== "") {
      writer.uint32(42).string(message.beginTime);
    }
    if (message.needTime !== 0) {
      writer.uint32(48).int32(message.needTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderInfoMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderInfoMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.orderId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.orderType = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.remainTime = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.beginTime = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.needTime = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderInfoMsg {
    return {
      orderId: isSet(object.orderId) ? globalThis.Number(object.orderId) : 0,
      orderType: isSet(object.orderType) ? globalThis.Number(object.orderType) : 0,
      remainTime: isSet(object.remainTime) ? globalThis.Number(object.remainTime) : 0,
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      beginTime: isSet(object.beginTime) ? globalThis.String(object.beginTime) : "",
      needTime: isSet(object.needTime) ? globalThis.Number(object.needTime) : 0,
    };
  },

  toJSON(message: OrderInfoMsg): unknown {
    const obj: any = {};
    if (message.orderId !== 0) {
      obj.orderId = Math.round(message.orderId);
    }
    if (message.orderType !== 0) {
      obj.orderType = Math.round(message.orderType);
    }
    if (message.remainTime !== 0) {
      obj.remainTime = Math.round(message.remainTime);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.beginTime !== "") {
      obj.beginTime = message.beginTime;
    }
    if (message.needTime !== 0) {
      obj.needTime = Math.round(message.needTime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderInfoMsg>, I>>(base?: I): OrderInfoMsg {
    return OrderInfoMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderInfoMsg>, I>>(object: I): OrderInfoMsg {
    const message = createBaseOrderInfoMsg();
    message.orderId = object.orderId ?? 0;
    message.orderType = object.orderType ?? 0;
    message.remainTime = object.remainTime ?? 0;
    message.userId = object.userId ?? 0;
    message.beginTime = object.beginTime ?? "";
    message.needTime = object.needTime ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
