// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: active/AchieveTotalPointInfoMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.active";

export interface AchieveTotalPointInfoMsg {
  totalPoint: number;
  pointInfo: number[];
}

function createBaseAchieveTotalPointInfoMsg(): AchieveTotalPointInfoMsg {
  return { totalPoint: 0, pointInfo: [] };
}

export const AchieveTotalPointInfoMsg: MessageFns<AchieveTotalPointInfoMsg> = {
  encode(message: AchieveTotalPointInfoMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalPoint !== 0) {
      writer.uint32(8).int32(message.totalPoint);
    }
    writer.uint32(18).fork();
    for (const v of message.pointInfo) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AchieveTotalPointInfoMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAchieveTotalPointInfoMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalPoint = reader.int32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.pointInfo.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.pointInfo.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AchieveTotalPointInfoMsg {
    return {
      totalPoint: isSet(object.totalPoint) ? globalThis.Number(object.totalPoint) : 0,
      pointInfo: globalThis.Array.isArray(object?.pointInfo)
        ? object.pointInfo.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: AchieveTotalPointInfoMsg): unknown {
    const obj: any = {};
    if (message.totalPoint !== 0) {
      obj.totalPoint = Math.round(message.totalPoint);
    }
    if (message.pointInfo?.length) {
      obj.pointInfo = message.pointInfo.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AchieveTotalPointInfoMsg>, I>>(base?: I): AchieveTotalPointInfoMsg {
    return AchieveTotalPointInfoMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AchieveTotalPointInfoMsg>, I>>(object: I): AchieveTotalPointInfoMsg {
    const message = createBaseAchieveTotalPointInfoMsg();
    message.totalPoint = object.totalPoint ?? 0;
    message.pointInfo = object.pointInfo?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
