// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: active/GiftReceiveRsp.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.active";

export interface GiftReceiveRsp {
  rewardSite: number;
  giftSite: number;
}

function createBaseGiftReceiveRsp(): GiftReceiveRsp {
  return { rewardSite: 0, giftSite: 0 };
}

export const GiftReceiveRsp: MessageFns<GiftReceiveRsp> = {
  encode(message: GiftReceiveRsp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rewardSite !== 0) {
      writer.uint32(8).int32(message.rewardSite);
    }
    if (message.giftSite !== 0) {
      writer.uint32(16).int32(message.giftSite);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GiftReceiveRsp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGiftReceiveRsp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.rewardSite = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.giftSite = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GiftReceiveRsp {
    return {
      rewardSite: isSet(object.rewardSite) ? globalThis.Number(object.rewardSite) : 0,
      giftSite: isSet(object.giftSite) ? globalThis.Number(object.giftSite) : 0,
    };
  },

  toJSON(message: GiftReceiveRsp): unknown {
    const obj: any = {};
    if (message.rewardSite !== 0) {
      obj.rewardSite = Math.round(message.rewardSite);
    }
    if (message.giftSite !== 0) {
      obj.giftSite = Math.round(message.giftSite);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GiftReceiveRsp>, I>>(base?: I): GiftReceiveRsp {
    return GiftReceiveRsp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GiftReceiveRsp>, I>>(object: I): GiftReceiveRsp {
    const message = createBaseGiftReceiveRsp();
    message.rewardSite = object.rewardSite ?? 0;
    message.giftSite = object.giftSite ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
