// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: active/OpenServiceRankInfoRes.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.active";

export interface OpenServiceRankInfoRes {
  type: number;
  time: string;
  info: number[];
}

function createBaseOpenServiceRankInfoRes(): OpenServiceRankInfoRes {
  return { type: 0, time: "", info: [] };
}

export const OpenServiceRankInfoRes: MessageFns<OpenServiceRankInfoRes> = {
  encode(message: OpenServiceRankInfoRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.time !== "") {
      writer.uint32(18).string(message.time);
    }
    writer.uint32(26).fork();
    for (const v of message.info) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpenServiceRankInfoRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOpenServiceRankInfoRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.time = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.info.push(reader.int32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.info.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OpenServiceRankInfoRes {
    return {
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      time: isSet(object.time) ? globalThis.String(object.time) : "",
      info: globalThis.Array.isArray(object?.info) ? object.info.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: OpenServiceRankInfoRes): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.time !== "") {
      obj.time = message.time;
    }
    if (message.info?.length) {
      obj.info = message.info.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OpenServiceRankInfoRes>, I>>(base?: I): OpenServiceRankInfoRes {
    return OpenServiceRankInfoRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OpenServiceRankInfoRes>, I>>(object: I): OpenServiceRankInfoRes {
    const message = createBaseOpenServiceRankInfoRes();
    message.type = object.type ?? 0;
    message.time = object.time ?? "";
    message.info = object.info?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
