// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: active/SumActiveGetPackageMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.active";

export interface SumActiveGetPackageMsg {
  activeId: string;
  packageId: string;
  type: number;
  count: number;
}

function createBaseSumActiveGetPackageMsg(): SumActiveGetPackageMsg {
  return { activeId: "", packageId: "", type: 0, count: 0 };
}

export const SumActiveGetPackageMsg: MessageFns<SumActiveGetPackageMsg> = {
  encode(message: SumActiveGetPackageMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.activeId !== "") {
      writer.uint32(10).string(message.activeId);
    }
    if (message.packageId !== "") {
      writer.uint32(18).string(message.packageId);
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    if (message.count !== 0) {
      writer.uint32(32).int32(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SumActiveGetPackageMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSumActiveGetPackageMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.activeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.packageId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SumActiveGetPackageMsg {
    return {
      activeId: isSet(object.activeId) ? globalThis.String(object.activeId) : "",
      packageId: isSet(object.packageId) ? globalThis.String(object.packageId) : "",
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
    };
  },

  toJSON(message: SumActiveGetPackageMsg): unknown {
    const obj: any = {};
    if (message.activeId !== "") {
      obj.activeId = message.activeId;
    }
    if (message.packageId !== "") {
      obj.packageId = message.packageId;
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SumActiveGetPackageMsg>, I>>(base?: I): SumActiveGetPackageMsg {
    return SumActiveGetPackageMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SumActiveGetPackageMsg>, I>>(object: I): SumActiveGetPackageMsg {
    const message = createBaseSumActiveGetPackageMsg();
    message.activeId = object.activeId ?? "";
    message.packageId = object.packageId ?? "";
    message.type = object.type ?? 0;
    message.count = object.count ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
