// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: active/TurnTableMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.active";

export interface TurnTableMsg {
  turntableId: number;
  freeRemainTimes: number;
  nextRefreshTime: string;
  payTimes: number;
  records: number[];
}

function createBaseTurnTableMsg(): TurnTableMsg {
  return { turntableId: 0, freeRemainTimes: 0, nextRefreshTime: "", payTimes: 0, records: [] };
}

export const TurnTableMsg: MessageFns<TurnTableMsg> = {
  encode(message: TurnTableMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.turntableId !== 0) {
      writer.uint32(8).int32(message.turntableId);
    }
    if (message.freeRemainTimes !== 0) {
      writer.uint32(16).int32(message.freeRemainTimes);
    }
    if (message.nextRefreshTime !== "") {
      writer.uint32(26).string(message.nextRefreshTime);
    }
    if (message.payTimes !== 0) {
      writer.uint32(32).int32(message.payTimes);
    }
    writer.uint32(42).fork();
    for (const v of message.records) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TurnTableMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTurnTableMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.turntableId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.freeRemainTimes = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nextRefreshTime = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.payTimes = reader.int32();
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.records.push(reader.int32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.records.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TurnTableMsg {
    return {
      turntableId: isSet(object.turntableId) ? globalThis.Number(object.turntableId) : 0,
      freeRemainTimes: isSet(object.freeRemainTimes) ? globalThis.Number(object.freeRemainTimes) : 0,
      nextRefreshTime: isSet(object.nextRefreshTime) ? globalThis.String(object.nextRefreshTime) : "",
      payTimes: isSet(object.payTimes) ? globalThis.Number(object.payTimes) : 0,
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: TurnTableMsg): unknown {
    const obj: any = {};
    if (message.turntableId !== 0) {
      obj.turntableId = Math.round(message.turntableId);
    }
    if (message.freeRemainTimes !== 0) {
      obj.freeRemainTimes = Math.round(message.freeRemainTimes);
    }
    if (message.nextRefreshTime !== "") {
      obj.nextRefreshTime = message.nextRefreshTime;
    }
    if (message.payTimes !== 0) {
      obj.payTimes = Math.round(message.payTimes);
    }
    if (message.records?.length) {
      obj.records = message.records.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TurnTableMsg>, I>>(base?: I): TurnTableMsg {
    return TurnTableMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TurnTableMsg>, I>>(object: I): TurnTableMsg {
    const message = createBaseTurnTableMsg();
    message.turntableId = object.turntableId ?? 0;
    message.freeRemainTimes = object.freeRemainTimes ?? 0;
    message.nextRefreshTime = object.nextRefreshTime ?? "";
    message.payTimes = object.payTimes ?? 0;
    message.records = object.records?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
