// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: consortia/ConsortiaAltarOpenReqMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.consortia";

export interface ConsortiaAltarOpenReqMsg {
  altarType: number;
  waveNum: number;
}

function createBaseConsortiaAltarOpenReqMsg(): ConsortiaAltarOpenReqMsg {
  return { altarType: 0, waveNum: 0 };
}

export const ConsortiaAltarOpenReqMsg: MessageFns<ConsortiaAltarOpenReqMsg> = {
  encode(message: ConsortiaAltarOpenReqMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.altarType !== 0) {
      writer.uint32(8).int32(message.altarType);
    }
    if (message.waveNum !== 0) {
      writer.uint32(16).int32(message.waveNum);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsortiaAltarOpenReqMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsortiaAltarOpenReqMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.altarType = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.waveNum = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConsortiaAltarOpenReqMsg {
    return {
      altarType: isSet(object.altarType) ? globalThis.Number(object.altarType) : 0,
      waveNum: isSet(object.waveNum) ? globalThis.Number(object.waveNum) : 0,
    };
  },

  toJSON(message: ConsortiaAltarOpenReqMsg): unknown {
    const obj: any = {};
    if (message.altarType !== 0) {
      obj.altarType = Math.round(message.altarType);
    }
    if (message.waveNum !== 0) {
      obj.waveNum = Math.round(message.waveNum);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConsortiaAltarOpenReqMsg>, I>>(base?: I): ConsortiaAltarOpenReqMsg {
    return ConsortiaAltarOpenReqMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConsortiaAltarOpenReqMsg>, I>>(object: I): ConsortiaAltarOpenReqMsg {
    const message = createBaseConsortiaAltarOpenReqMsg();
    message.altarType = object.altarType ?? 0;
    message.waveNum = object.waveNum ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
