// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: consortia/ConsortiaBossMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.consortia";

export interface ConsortiaBossMsg {
  grade: number;
  spirit: string;
  state: number;
  endTime: string;
  totalHp: string;
  callGrade: number;
}

function createBaseConsortiaBossMsg(): ConsortiaBossMsg {
  return { grade: 0, spirit: "", state: 0, endTime: "", totalHp: "", callGrade: 0 };
}

export const ConsortiaBossMsg: MessageFns<ConsortiaBossMsg> = {
  encode(message: ConsortiaBossMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.grade !== 0) {
      writer.uint32(8).int32(message.grade);
    }
    if (message.spirit !== "") {
      writer.uint32(18).string(message.spirit);
    }
    if (message.state !== 0) {
      writer.uint32(24).int32(message.state);
    }
    if (message.endTime !== "") {
      writer.uint32(34).string(message.endTime);
    }
    if (message.totalHp !== "") {
      writer.uint32(42).string(message.totalHp);
    }
    if (message.callGrade !== 0) {
      writer.uint32(48).int32(message.callGrade);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsortiaBossMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsortiaBossMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.grade = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.spirit = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.state = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.endTime = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.totalHp = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.callGrade = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConsortiaBossMsg {
    return {
      grade: isSet(object.grade) ? globalThis.Number(object.grade) : 0,
      spirit: isSet(object.spirit) ? globalThis.String(object.spirit) : "",
      state: isSet(object.state) ? globalThis.Number(object.state) : 0,
      endTime: isSet(object.endTime) ? globalThis.String(object.endTime) : "",
      totalHp: isSet(object.totalHp) ? globalThis.String(object.totalHp) : "",
      callGrade: isSet(object.callGrade) ? globalThis.Number(object.callGrade) : 0,
    };
  },

  toJSON(message: ConsortiaBossMsg): unknown {
    const obj: any = {};
    if (message.grade !== 0) {
      obj.grade = Math.round(message.grade);
    }
    if (message.spirit !== "") {
      obj.spirit = message.spirit;
    }
    if (message.state !== 0) {
      obj.state = Math.round(message.state);
    }
    if (message.endTime !== "") {
      obj.endTime = message.endTime;
    }
    if (message.totalHp !== "") {
      obj.totalHp = message.totalHp;
    }
    if (message.callGrade !== 0) {
      obj.callGrade = Math.round(message.callGrade);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConsortiaBossMsg>, I>>(base?: I): ConsortiaBossMsg {
    return ConsortiaBossMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConsortiaBossMsg>, I>>(object: I): ConsortiaBossMsg {
    const message = createBaseConsortiaBossMsg();
    message.grade = object.grade ?? 0;
    message.spirit = object.spirit ?? "";
    message.state = object.state ?? 0;
    message.endTime = object.endTime ?? "";
    message.totalHp = object.totalHp ?? "";
    message.callGrade = object.callGrade ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
