// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: consortia/ConsortiaEventInfoMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.consortia";

export interface ConsortiaEventInfoMsg {
  id: number;
  consortiaId: number;
  remark: string;
  createDate: string;
  type: number;
  isExist: boolean;
}

function createBaseConsortiaEventInfoMsg(): ConsortiaEventInfoMsg {
  return { id: 0, consortiaId: 0, remark: "", createDate: "", type: 0, isExist: false };
}

export const ConsortiaEventInfoMsg: MessageFns<ConsortiaEventInfoMsg> = {
  encode(message: ConsortiaEventInfoMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.consortiaId !== 0) {
      writer.uint32(16).int32(message.consortiaId);
    }
    if (message.remark !== "") {
      writer.uint32(26).string(message.remark);
    }
    if (message.createDate !== "") {
      writer.uint32(34).string(message.createDate);
    }
    if (message.type !== 0) {
      writer.uint32(40).int32(message.type);
    }
    if (message.isExist !== false) {
      writer.uint32(48).bool(message.isExist);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsortiaEventInfoMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsortiaEventInfoMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.consortiaId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.remark = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isExist = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConsortiaEventInfoMsg {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      consortiaId: isSet(object.consortiaId) ? globalThis.Number(object.consortiaId) : 0,
      remark: isSet(object.remark) ? globalThis.String(object.remark) : "",
      createDate: isSet(object.createDate) ? globalThis.String(object.createDate) : "",
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      isExist: isSet(object.isExist) ? globalThis.Boolean(object.isExist) : false,
    };
  },

  toJSON(message: ConsortiaEventInfoMsg): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.consortiaId !== 0) {
      obj.consortiaId = Math.round(message.consortiaId);
    }
    if (message.remark !== "") {
      obj.remark = message.remark;
    }
    if (message.createDate !== "") {
      obj.createDate = message.createDate;
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.isExist !== false) {
      obj.isExist = message.isExist;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConsortiaEventInfoMsg>, I>>(base?: I): ConsortiaEventInfoMsg {
    return ConsortiaEventInfoMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConsortiaEventInfoMsg>, I>>(object: I): ConsortiaEventInfoMsg {
    const message = createBaseConsortiaEventInfoMsg();
    message.id = object.id ?? 0;
    message.consortiaId = object.consortiaId ?? 0;
    message.remark = object.remark ?? "";
    message.createDate = object.createDate ?? "";
    message.type = object.type ?? 0;
    message.isExist = object.isExist ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
