// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: consortia/ConsortiaBossPlayerMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.consortia";

export interface ConsortiaBossPlayerMsg {
  userid: number;
  collectCount: number;
  missionItemCount: number;
}

function createBaseConsortiaBossPlayerMsg(): ConsortiaBossPlayerMsg {
  return { userid: 0, collectCount: 0, missionItemCount: 0 };
}

export const ConsortiaBossPlayerMsg: MessageFns<ConsortiaBossPlayerMsg> = {
  encode(message: ConsortiaBossPlayerMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userid !== 0) {
      writer.uint32(8).int32(message.userid);
    }
    if (message.collectCount !== 0) {
      writer.uint32(16).int32(message.collectCount);
    }
    if (message.missionItemCount !== 0) {
      writer.uint32(24).int32(message.missionItemCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsortiaBossPlayerMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsortiaBossPlayerMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userid = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.collectCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.missionItemCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConsortiaBossPlayerMsg {
    return {
      userid: isSet(object.userid) ? globalThis.Number(object.userid) : 0,
      collectCount: isSet(object.collectCount) ? globalThis.Number(object.collectCount) : 0,
      missionItemCount: isSet(object.missionItemCount) ? globalThis.Number(object.missionItemCount) : 0,
    };
  },

  toJSON(message: ConsortiaBossPlayerMsg): unknown {
    const obj: any = {};
    if (message.userid !== 0) {
      obj.userid = Math.round(message.userid);
    }
    if (message.collectCount !== 0) {
      obj.collectCount = Math.round(message.collectCount);
    }
    if (message.missionItemCount !== 0) {
      obj.missionItemCount = Math.round(message.missionItemCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConsortiaBossPlayerMsg>, I>>(base?: I): ConsortiaBossPlayerMsg {
    return ConsortiaBossPlayerMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConsortiaBossPlayerMsg>, I>>(object: I): ConsortiaBossPlayerMsg {
    const message = createBaseConsortiaBossPlayerMsg();
    message.userid = object.userid ?? 0;
    message.collectCount = object.collectCount ?? 0;
    message.missionItemCount = object.missionItemCount ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
