// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: consortia/TaskRecordMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.consortia";

export interface TaskRecordMsg {
  nickName: string;
  starNum: number;
  score: number;
  time: number;
}

function createBaseTaskRecordMsg(): TaskRecordMsg {
  return { nickName: "", starNum: 0, score: 0, time: 0 };
}

export const TaskRecordMsg: MessageFns<TaskRecordMsg> = {
  encode(message: TaskRecordMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nickName !== "") {
      writer.uint32(10).string(message.nickName);
    }
    if (message.starNum !== 0) {
      writer.uint32(16).int32(message.starNum);
    }
    if (message.score !== 0) {
      writer.uint32(24).int32(message.score);
    }
    if (message.time !== 0) {
      writer.uint32(32).int32(message.time);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskRecordMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskRecordMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nickName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.starNum = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.score = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.time = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskRecordMsg {
    return {
      nickName: isSet(object.nickName) ? globalThis.String(object.nickName) : "",
      starNum: isSet(object.starNum) ? globalThis.Number(object.starNum) : 0,
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
    };
  },

  toJSON(message: TaskRecordMsg): unknown {
    const obj: any = {};
    if (message.nickName !== "") {
      obj.nickName = message.nickName;
    }
    if (message.starNum !== 0) {
      obj.starNum = Math.round(message.starNum);
    }
    if (message.score !== 0) {
      obj.score = Math.round(message.score);
    }
    if (message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskRecordMsg>, I>>(base?: I): TaskRecordMsg {
    return TaskRecordMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskRecordMsg>, I>>(object: I): TaskRecordMsg {
    const message = createBaseTaskRecordMsg();
    message.nickName = object.nickName ?? "";
    message.starNum = object.starNum ?? 0;
    message.score = object.score ?? 0;
    message.time = object.time ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
