// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: limitedtimegift/LimitedTimeGiftData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.limitedtimegift";

export interface LimitedTimeGiftData {
  templateId: number;
  lastShowTime: string;
  showSecond: number;
  status: number;
  type: number;
}

function createBaseLimitedTimeGiftData(): LimitedTimeGiftData {
  return { templateId: 0, lastShowTime: "", showSecond: 0, status: 0, type: 0 };
}

export const LimitedTimeGiftData: MessageFns<LimitedTimeGiftData> = {
  encode(message: LimitedTimeGiftData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.templateId !== 0) {
      writer.uint32(8).int32(message.templateId);
    }
    if (message.lastShowTime !== "") {
      writer.uint32(18).string(message.lastShowTime);
    }
    if (message.showSecond !== 0) {
      writer.uint32(24).int32(message.showSecond);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    if (message.type !== 0) {
      writer.uint32(40).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LimitedTimeGiftData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLimitedTimeGiftData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.templateId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lastShowTime = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.showSecond = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LimitedTimeGiftData {
    return {
      templateId: isSet(object.templateId) ? globalThis.Number(object.templateId) : 0,
      lastShowTime: isSet(object.lastShowTime) ? globalThis.String(object.lastShowTime) : "",
      showSecond: isSet(object.showSecond) ? globalThis.Number(object.showSecond) : 0,
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
    };
  },

  toJSON(message: LimitedTimeGiftData): unknown {
    const obj: any = {};
    if (message.templateId !== 0) {
      obj.templateId = Math.round(message.templateId);
    }
    if (message.lastShowTime !== "") {
      obj.lastShowTime = message.lastShowTime;
    }
    if (message.showSecond !== 0) {
      obj.showSecond = Math.round(message.showSecond);
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LimitedTimeGiftData>, I>>(base?: I): LimitedTimeGiftData {
    return LimitedTimeGiftData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LimitedTimeGiftData>, I>>(object: I): LimitedTimeGiftData {
    const message = createBaseLimitedTimeGiftData();
    message.templateId = object.templateId ?? 0;
    message.lastShowTime = object.lastShowTime ?? "";
    message.showSecond = object.showSecond ?? 0;
    message.status = object.status ?? 0;
    message.type = object.type ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
