// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: limitedtimegift/LimitedTimeGiftRspMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.limitedtimegift";

export interface LimitedTimeGiftRspMsg {
  op: number;
  gifts: number[];
  dailyGift: string;
}

function createBaseLimitedTimeGiftRspMsg(): LimitedTimeGiftRspMsg {
  return { op: 0, gifts: [], dailyGift: "" };
}

export const LimitedTimeGiftRspMsg: MessageFns<LimitedTimeGiftRspMsg> = {
  encode(message: LimitedTimeGiftRspMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.op !== 0) {
      writer.uint32(8).int32(message.op);
    }
    writer.uint32(18).fork();
    for (const v of message.gifts) {
      writer.int32(v);
    }
    writer.join();
    if (message.dailyGift !== "") {
      writer.uint32(26).string(message.dailyGift);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LimitedTimeGiftRspMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLimitedTimeGiftRspMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.op = reader.int32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.gifts.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.gifts.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dailyGift = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LimitedTimeGiftRspMsg {
    return {
      op: isSet(object.op) ? globalThis.Number(object.op) : 0,
      gifts: globalThis.Array.isArray(object?.gifts) ? object.gifts.map((e: any) => globalThis.Number(e)) : [],
      dailyGift: isSet(object.dailyGift) ? globalThis.String(object.dailyGift) : "",
    };
  },

  toJSON(message: LimitedTimeGiftRspMsg): unknown {
    const obj: any = {};
    if (message.op !== 0) {
      obj.op = Math.round(message.op);
    }
    if (message.gifts?.length) {
      obj.gifts = message.gifts.map((e) => Math.round(e));
    }
    if (message.dailyGift !== "") {
      obj.dailyGift = message.dailyGift;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LimitedTimeGiftRspMsg>, I>>(base?: I): LimitedTimeGiftRspMsg {
    return LimitedTimeGiftRspMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LimitedTimeGiftRspMsg>, I>>(object: I): LimitedTimeGiftRspMsg {
    const message = createBaseLimitedTimeGiftRspMsg();
    message.op = object.op ?? 0;
    message.gifts = object.gifts?.map((e) => e) || [];
    message.dailyGift = object.dailyGift ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
