export enum ActionsEvent {
	ACTION_ALL_COMPLETE = "action_all_complete",
}

export enum LoginEvent {
	LOGIN_OTHER = "LOGINOTHER",
}

export enum SelectServerEvent {
	CHANGE = "CHANGE",
}

export enum PetDragEvent {
	DRAG_OVER = "DRAG_OVER",
}

export enum PK_Event {
	SPACE_PK = "SPACE_PK",
}

export enum FunnyEvent {
	/***
	 * 收到活动模版数据
	 * */
	REFRESH_TEMP = "REFRESH_TEMP",
	/***
	 * 收到用户的活动数据
	 * */
	REFRESH_ITEM = "REFRESH_ITEM",
	/***
	 * 有可领取的活动
	 * */
	ITEM_CANGET = "ITEM_CANGET",
	/**
	 * 提醒状态变化
	 */
	REMAIN_STATE = "REMAIN_STATE",
}

export enum AiEvents {
	MOVE_STATE = "moveState",
	UPDATE_SPEED = "updateSpeed",
	IS_LIVING = "isLiving",
	UPDATE_CENTER_POINT = "updateCenterPoint",
	UPDATE_NEXT_POINT = "updateNextPoint",
	UPDATE_PATHS = "updatePaths",
	NEXT_POINT = "nextPoint",
}

export enum SortEvent {
	SELECTE_CHANGE = "SELECTE_CHANGE",
	PAGE_UPDATE = "PAGE_UPDATE",
	SELECTE_LIST_CHANG = "SELECTE_LIST_CHANG",
	WARLORD_RANK_DATA_UPDATE = "WARLORD_RANK_DATA_UPDATE",
}

export enum DayGuideEvent {
	ACTIVE_CHANGE = "ACTIVE_CHANGE",
	WEEK_ACTIVE_CHANGE = "WEEK_ACTIVE_CHANGE",
	LEED_PROGRESS_CHANGE = "LEED_PROGRESS_CHANGE",
	LEEDINFO_CHANGE = "LEEDINFO_CHANGE",
	LEED_COMPLETE = "LEED_COMPLETE",
	DAY_ACTIVE_GOBACK = "DAY_ACTIVE_GOBACK",
	LEFT_SELECTED_CHANGE = "LEFT_SELECTED_CHANGE",
	DAILY_ITEM_CLICK = "DAILY_ITEM_CLICK",
	DAILY_ITEM_REFRESH = "DAILY_ITEM_REFRESH",
	ONLINE_REWARD = "ONLINE_REWARD",
	DAILY_AWARD_STATE = "DAILY_AWARD_STATE",
	ONLINE_REWARD_BACK = "ONLINE_REWARD_BACK",
}

export enum QuestionnaireEvent {
	QUESTIONNAIRE_FRESH = "QUESTIONNAIRE_FRESH",
	QUESTIONNAIRE_CHECKED = "QUESTIONNAIRE_CHECKED",
	QUESTIONNAIRE_CHANGE = "QUESTIONNAIRE_CHANGE",
}

export enum QuestionEvent {
	SCROLL_TO_NEXT = "SCROLL_TO_NEXT",
	FINISH_QUESTION = "FINISH_QUESTION",
	FOCUS = "FOCUS",
	BLUR = "BLUR",
	SELECT_ANSWER_ITEM = "SELECT_ANSWER_ITEM",
	INPUT_WORDS_CHANGE = "INPUT_WORDS_CHANGE",
}

export enum WorldBossEvent {
	UPDATE_WORLDBOSS_INFO = "UPDATE_WORLDBOSS_INFO",
	UPDATE_WOUND_LIST = "UPDATE_WOUND_LIST",
	UPDATE_STATE_LIST = "UPDATE_STATE_LIST",
	UPDATE_WARFIGHT_STATE_LIST = "UPDATE_WARFIGHT_STATE_LIST",
	REWARDS_INIT = "REWARDS_INIT",
	UPDATE_CONSORTIA_BOSS_HP = "UPDATE_CONSORTIA_BOSS_HP",
	UPDATE_WORLDBOSS_NODE_STATE = "UPDATE_WORLDBOSS_NODE_STATE",
}

export enum TimeBoxEvent {
	TIME_COMPLETE = "TIME_COMPLETE",
	UPDATE_TIME_BOX = "UPDATE_TIME_BOX",
}

export enum FundEvent {
	SHOWTOPBTN = "SHOWTOPBTN",
	SHOWGET = "SHOWGET",
	OPEN = "OPEN",
}

export enum SinglePassEvent {
	SINGLEPASS_INFO_UPDATE = "SINGLEPASS_INFO_UPDATE",
	ORDERDATA_LOAD_COMPLETE = "ORDERDATA_LOAD_COMPLETE",
	UPDATE_BUGLE_INFO = "UPDATE_BUGLE_INFO",
	UPDATE_BUGLE_REWARDS = "UPDATE_BUGLE_REWARDS",
	SINGLEPASS_UPDATE_REWARD = "SINGLEPASS_UPDATE_REWARD",
}

export enum NotificationEvent {
	APPELL = "APPELL",
	CHECK_NETSPEED = "CHECK_NETSPEED",
	KING_CONTRACT = "KING_CONTRACT",
	KING_CONTRACT_BUFF_GET = "KING_CONTRACT_BUFF_GET",
	SEMINARY_BLESS = "SEMINARY_BLESS",
	CHAT_BIGBUGLE = "CHAT_BIGBUGLE",
	WEAPON_CHANGE = "WEAPON_CHANGE",
	OPEN_CAMPAIGN_FRAME = "OPEN_CAMPAIGN_FRAME",
	TASKWND_VISIBLE = "TASKWND_VISIBLE",

	/**
	 *聊天状态改变
	 */
	IMSTATE_CHANGE = "IMSTATE_CHANGE",
	/**
	 *停止动画播放
	 */
	STOP_EFFECT = "STOP_EFFECT",
	/**
	 *登陆成功, 得到场景状态
	 */
	LOGIN_STATE = "LOGIN_STATE",
	/**
	 * 刷新NPC；
	 */
	REFRESH_NPC = "REFRESH_NPC",
	/**
	 * 攻打NPC,
	 * var key :string = end.x+","+end.y,
	 */
	ATTACK_NPC = "ATTACK_NPC",
	/**
	 *科技升级点击
	 */
	TEC_UPGRADE_CLICK = "TEC_UPGRADE_CLICK",
	/**
	 * 战斗结束
	 *  var data:Object = {x:arr[0],y:arr[1]}
	 */
	BATTLE_OVER = "BATTLE_OVER",

	/**
	 * 外城野地更新
	 * var wInfo:WildLandInfo = new WildLandInfo(),
	 */
	UPDATE_WILDLAND = "UPDATE_WILDLAND",
	/**
	 * 外城行军队更新
	 *
	 */
	UPDTAE_ARMY = "$UPDTAE_ARMY",
	SWITCH_SCENE = "SWITCH_SCENE",
	BEFORE_LEAVEING_SCENE = "BEFORE_LEAVEING_SCENE",
	LOCK_SCENE = "LOCK_SCENE",

	ADD_MAP_CHEST = "ADD_MAP_CHEST",

	UI_OUT_SCENE = "UI_OUT_SCENE",
	UI_ENTER_SCENE = "UI_ENTER_SCENE",

	SEND_CAMPAIGN_ARRIVE = "sendCampaignArrive",

	ROOM_KILL_OUT = "roomKillOut",
	VEHICLE_ROOM_KILL_OUT = "VEHICLE_ROOM_KILL_OUT",
	CAMPAIGN_GUIDE = "campaignGuide",
	QUIT_CAMPAIGN = "QUIT_CAMPAIGN",
	ARMY_SYSC_CALL = "ARMY_SYSC_CALL",

	SHOPHOMEPAGE_UPDATA = "SHOPHOMEPAGE_UPDATA",
	SWITCH_MAP_TRANSFER = "SWITCH_MAP_TRANSFER",
	LOCK_PVP_WARFIGHT = "LOCK_PVP_WARFIGHT",
	BATTLE_RESULT = "BATTLE_RESULT",
	CLICK_MAP = "CLICK_MAP",
	OPEN_CHEST_BOX = "OPEN_CHEST_BOX",
	SELECT_FRIEND = "SELECT_FRIEND",
	WORK_NEXT_NODE = "WORK_NEXT_NODE",
	CHARGE_ORDER_RSP = "CHARGE_ORDER_RSP",
	SHOW_RECHARGE = "SHOW_RECHARGE",

	SHOP_TIME_BUY_REFRESH = "SHOP_TIME_BUY_REFRESH",
	SHOP_RESET_LIMITBUY_COUNT = "SHOP_RESET_LIMITBUY_COUNT",
	/**
	 * 运输中
	 */
	TRANSPORT_STATE = "TRANSPORT_STATE",

	CAMPAIGN_PK = "CAMPAIGN_PK",
	MAIN_TOOL_BAR_RESIZED = "MAIN_TOOL_BAR_RESIZED",

	BEHAVIOR_ANALYSIS = "BEHAVIOR_ANALYSIS",
	GAMEGUIDE_PAGE_CHANGE = "GAMEGUIDE_PAGE_CHANGE",
	AUCTION_HOT_SEARCH = "AUCTION_HOT_SEARCH",
	/**
	 * 邀请成功
	 */
	INVITE_SUCCESS = "INVITE_SUCCESS",

	CUSTOMER_SERVICE_SWITCH = "CUSTOMER_SERVICE_SWITCH",

	CUSTOMER_SERVICE_REPLY = "CUSTOMER_SERVICE_REPLY",

	/**
	 * 魔罐
	 */
	REFRESH_TOPTOOLS = "REFRESH_TOPTOOLS",

	HERO_LEVELUP_CLOSE = "HERO_LEVELUP_CLOSE", //英雄升级界面关闭
	VEHICLE_TECH_CHANGE = "VEHICLE_TECH_CHANGE", //魔灵科技变化
	RECEIVE_BAG_360 = "RECEIVE_BAG_360", //360礼包的领取数据
	CHASE_NPC = "CHASE_NPC", //追击npc
	LOCK_NODE = "LOCK_NODE",
	UN_LOCK_NODE = "UN_LOCK_NODE",
	CHECK_PLAYING = "CHECK_PLAYING",

	USE_SKILL_RESULT = "USE_SKILL_RESULT",

	NPC_LOAD_COMPLETE = "NPC_LOAD_COMPLETE",
	START_DRAG = "START_DRAG",
	END_DRAG = "END_DRAG",
	FUND_REFRESH = "FUND_REFRESH",
	/** 环任务中对话任务的完成事件 */
	TALKRINGTASK_COMPLETE = "TALKRINGTASK_COMPLETE",
	/** 基金刷新 改变基金的图片的位置 */
	FUNDREFRESH = "FUNDREFRESH",

	DISPOSEVIEW = "DISPOSEVIEW",

	/** 答题*/
	ANSWER_SWITCH = "ANSWER_SWITCH",

	/**
	 * 卡点自助
	 */
	SELF_HELP_RESET_POSITION = "SELF_HELP_RESET_POSITION",
	/**
	 * 获得更新公告
	 */
	RECEIVED_NOTICE = "RECEIVED_NOTICE",

	OPEN_BATTLEGUARD_ITEM = "OPEN_BATTLEGUARD_ITEM",
	DOUBLE_CLICK = "DOUBLE_CLICK",
	SWITCH_PANEL = "SWITCH_PANEL",

	LOCK_TEAM_FOLLOW_TARGET = "LOCK_TEAM_FOLLOW_TARGET",

	REFRESH_FIGHT = "REFRESH_FIGHT",

	/** 七日引导显示按钮 */
	SHOWBTN = "SHOWBTN",
	/** 七日引导显示特效 */
	SHOWEFF = "SHOWEFF",

	SHOWCAMPAIGN = "SHOWCAMPAIGN",

	/**
	 * 鱼群的更新
	 */
	UPDATE_FISH_INFO = "UPDATE_FISH_INFO",
	/**
	 * 鱼钩的更新
	 */
	UPDATE_FISH_FORK = "UPDATE_FISH_FORK",

	HIDE_FREEDOMTEAMLIST = "HIDE_FREEDOMTEAMLIST",
	/** 关闭宝石迷阵界面 */
	CLOSE_GEMMAZEFRAME = "CLOSE_GEMMAZEFRAME",

	/** 隐藏扫荡界面 **/
	HIDE_MOPUPING = "HIDE_MOPUPING",

	/**
	 * 背包打开事件 因为背包和夺宝奇兵背包一起打开重叠的时候会影响背包的拖动和出售
	 */
	ARMYFRAMEII_OPEN_FOR_GEMMAZE = "ARMYFRAMEII_OPEN_FOR_GEMMAZE",
	ARMYFRAMEII_CLOSE_FOR_GEMMAZE = "ARMYFRAMEII_CLOSE_FOR_GEMMAZE",

	CLOSE_SPECIALSELECTWND = "CLOSE_SPECIALSELECTWND", //关闭特性选择界面
	UPDATE_SPECIALSELECTITEM = "UPDATE_SPECIALSELECTITEM", //更新特性选择项目
	UPDATE_CONFIRM_SPECIALSELECTITEM = "UPDATE_CONFIRM_SPECIALSELECTITEM",
	SHOW_BATTLE_GUARD_ITEMS = "SHOW_BATTLE_GUARD_ITEMS", //显示战斗守护宝石道具
	FIRSTPAY_DATA_UPDATE = "FIRSTPAY_DATA_UPDATE", //首充数据更新
	GROWTH_FUND_UPDATE = "GROWTH_FUND_UPDATE", //成长基金数据更新
	LEVEL_GIFT_UPDATE = "LEVEL_GIFT_UPDATE", //等级礼包数据更新
	SEVEN_GOALS_TASK_UPDATE = "SEVEN_GOALS_TASK_UPDATE", //七日目标任务数据更新
	SEVEN_GOALS_REWARD_LOOK_UPDATE = "SEVEN_GOALS_REWARD_LOOK_UPDATE", //七日目标奖励预览更新
	SEVEN_GOALS_REWARDSITE_UPDATE = "SEVEN_GOALS_REWARDSITE_UPDATE", //七日目标奖励礼包领取状态更新
	SEVEN_GOALS_GIFTSITE_UPDATE = "SEVEN_GOALS_GIFTSITE_UPDATE", //七日目标特惠礼包领取状态更新
	SEVEN_GOALS_TASKGET_UPDATE = "SEVEN_GOALS_TASKGET_UPDATE", //七日目标任务l领取数据更新
	SEVEN_LOGIN_INFO_UPDATE = "SEVEN_LOGIN_INFO_UPDATE", //七日登录信息更新
	SEVEN_LOGIN_REWARD_UPDATE = "SEVEN_LOGIN_REWARD_UPDATE", //七日登录奖励更新
	UPDATA_CONSORTIAEMAIL_MEMBERLIST = "UPDATA_CONSORTIAEMAIL_MEMBERLIST", //公会发送邮件选中列表项
	UPDATE_SYSTEM_TIME = "UPDATE_SYSTEM_TIME", //更新系统时间
	TASKRING_ITEM_UPDATE = "TASKRING_ITEM_UPDATE", //任务项更新
	CLOSE_LEVELUP = "CLOSE_LEVELUP", //升级界面关闭
	AllManExchangeUpdate = "AllManExchangeUpdate", //全民兑换更新状态
	CLOSE_MOUNT_REFINING_WND = "CLOSE_MOUNT_REFINING_WND", //关闭了坐骑炼化界面
	CROSS_ADD_GOONBTN = "CROSS_ADD_GOONBTN", //跨服本中添加继续撮合按钮
	UPDATE_TEAM_ONLINE_STATUS = "UPDATE_TEAM_ONLINE_STATUS", //更新玩家状态
	UPDATE_CROSS_PVE_STATUS = "UPDATE_CROSS_PVE_STATUS", //跨服多人本的开放状态
	MEMORYCARD_DATA_UPDATE = "MEMORYCARD_DATA_UPDATE", //活动-记忆翻牌信息更新
	MEMORYCARD_STATE_UPDATE = "MEMORYCARD_STATE_UPDATE", //活动-记忆翻牌开启状态更新
	LUCKY_TEMP_CHANGE = "LUCKY_TEMP_CHANGE", //幸运兑换模板更新
	LUCKY_INFO_CHANGE = "LUCKY_INFO_CHANGE", //幸运兑换数据
	LUCK_EXCHANGE_BTN_STATUS_CHANGE = "LUCK_EXCHANGE_BTN_STATUS_CHANGE", //幸运兑换按钮点击状态变化
	CONSORTIA_BOSS_SWITCH = "CampaignEvent.CONSORTIA_BOSS_SWITCH",
	CONSORTIA_BOSS_STATE_UPDATE = "CampaignEvent.CONSORTIA_BOSS_STATE_UPDATE",
	CONSORTIA_BOSS_BUFFERIDS = "CONSORTIA_BOSS_BUFFERIDS",
	PASS_CHECK_AWARD_STATE = "PASS_CHECK_AWARD_STATE", //通行证按钮点击状态变化
	FOISONHORN_INFO_CHANGE = "FOISONHORN_INFO_CHANGE",
	FOISONHORN_RED_CHANGE = "FOISONHORN_RED_CHANGE", //红点状态改变
	CHAT_TRANSLATE_SETTING = "CHAT_TRANSLATE_SETTING", //聊天翻译目标语言设置
	/**
	 * 多人众神报名开始  开启顶部图标事件
	 * */
	MULTILORDS_OPEN = "MULTILORDS_OPEN",

	FASHION_SHOW_CHANGE = "FASHION_SHOW_CHANGE", //时装形象
	HONOR_EQUIP_LEVELUP = "HONOR_EQUIP_LEVELUP", //升级/升阶荣誉装备
	OUTYARD_STATE_INFO = "OUTYARD_STATE_INFO",
	OUTYARD_OPEN_FRAME = "OUTYARD_OPEN_FRAME",
	OUTYARD_FULL_INFO = "OUTYARD_FULL_INFO",
	OUTYARD_UPDATE_INFO = "OUTYARD_UPDATE_INFO",
	OUTYARD_USERLIST_INFO = "OUTYARD_USERLIST_INFO",
	OUTYARD_BATTLE_DEFENCE = "OUTYARD_BATTLE_DEFENCE",
	OUTYARD_SELF_INFO = "OUTYARD_SELF_INFO",
	OUTYARD_CHANGE_SENIOR = "OUTYARD_CHANGE_SENIOR",
	OUTYARD_CLOSE_WND = "OUTYARD_CLOSE_WND",
	CHARGELOTTERY_RESULT_UPDATE = "CHARGELOTTERY_RESULT_UPDATE",
	OUTYARD_REFRESH_REPORT = "OUTYARD_REFRESH_REPORT",
	OUTYARD_INIT_REPORT = "OUTYARD_INIT_REPORT",

	/**幸运盲盒信息更新 */
	LUCKBLINDBOX_INFO_UPDATE = "LUCKBLINDBOX_INFO_UPDATE",
	/**幸运盲盒开启后刷新 */
	LUCKBLINDBOX_OPEN_REFRESH = "LUCKBLINDBOX_OPEN_REFRESH",

	UPDATE_WISHDATA = "UPDATE_WISHDATA",
	USE_PROP = "USE_PROP",
	CLOSE_OUTERCITY_MAP_WND = "CLOSE_OUTERCITY_MAP_WND",
	OUTERCITY_SELECTE_MINEITEM = "OUTERCITY_SELECTE_MINEITEM",
	MAP_CLICK = "MAP_CLICK",
	UPDATE_SELECTED_PET = "UPDATE_SELECTED_PET",
	UPDATE_SELECTED_PET_STATUS = "UPDATE_SELECTED_PET_STATUS",

	/**超值团购礼包活动详情更新 */
	SUPERGIFTOFGROUP_DETAIL_UPDATE = "SUPERGIFTOFGROUP_DETAIL_UPDATE",
	/**超值团购礼包活动状态更新 */
	SUPERGIFTOFGROUP_STATE_UPDATE = "SUPERGIFTOFGROUP_STATE_UPDATE",
    ARTIFACT_SELECT_GOODS_UPDATE = "ARTIFACT_SELECT_GOODS_UPDATE",
    ARTIFACT_CANCEL_GOODS_UPDATE = "ARTIFACT_CANCEL_GOODS_UPDATE",
    ARTIFACT_SUCCESS_UPDATE = "ARTIFACT_SUCCESS_UPDATE",
	UPDATE_LOOKINFO_PETDATA = "UPDATE_LOOKINFO_PETDATA",
	UPDATE_LOOKINFO_SELECTIDEX = "UPDATE_LOOKINFO_SELECTIDEX",
	UPDATE_HEADFRAME_INFO = "UPDATE_HEADFRAME_INFO",
	UPDATE_HEADFRAME_ACTIVE = "UPDATE_HEADFRAME_ACTIVE",
	UPDATE_HEADFRAME_CLICK_STATUS = "UPDATE_HEADFRAME_CLICK_STATUS",

	USER_IS_BIND = "USER_IS_BIND",
    USER_BIND_REWARD = "USER_BIND_REWARD",
    SWITCH_ACCOUNT = "SWITCH_ACCOUNT",
	ROOM_INFO_UPDATE = "ROOM_INFO_UPDATE",
	UPDATE_SCREET_TREE = "UPDATE_SCREET_TREE",
	UPDATE_ROOM_BASE_DATA = "UPDATE_ROOM_BASE_DATA",
}

export enum PlayerBufferEvent {
	CAMPAIGN_BUFFER_UPDATE = "CAMPAIGN_BUFFER_UPDATE",
	ITEM_BUFFER_UPDATE = "ITEM_BUFFER_UPDATE",
}

export enum RequestInfoEvent {
	REQUEST_SIMPLEINFO = "REQUEST_SIMPLEINFO",
	REQUEST_SIMPLEANDSNS_INFO = "REQUEST_SIMPLEANDSNS_INFO",
	QUERY_PETDATA_RESULT = "QUERY_PETDATA_RESULT",
	QUERY_MOUNT_RESULT = "QUERY_MOUNT_RESULT",
	BAG_EQUIPLOOK = "BAG_EQUIPLOOK",
	QUERY_MASTERY_RESULT = "QUERY_MASTERY_RESULT",
}

export enum ResourceEvent {
	RESOURCE_UPDATE = "RESOURCE_UPDATE",
	PET_SKILL_SCROLL_UPDATE = "PET_SKILL_SCROLL_UPDATE",
}

export enum RoleEvent {
	LOCK_ROLE = "lockRole",
	ACTION = "action",
	POINT_CHANGE = "pointChange",
	BLOOD_CHANGE = "bloodChange",
	BLOOD_CHANGE_S = "bloodChangeS",
	IS_LIVING = "isLiving",
	DIE = "die",
	SCALE_X = "scaleX",
	COUNT_DOWN = "countDown",
	COUNT = "count",
	SP = "sp",
	HP = "hp",
	EFFECT_PLAY = "effectcPlay",
	REFRESH_BUFFER = "REFRESH_BUFFER",
	SHOW_BUFFER = "SHOW_BUFFER",
	REFRESH_BUFFER_TURN = "REFRESH_BUFFER_TURN",
	FACE_CHANGE = "FACE_CHANGE",
	DIRECTION_CHANGE = "direction_change",

	BATTLE_GOLD = "battleGold",
	BATTLE_GP = "battleGP",
	BATTLE_STRATEGY = "battleStrategy",

	AWAKEN = "AWAKEN",
	/** 变身 */
	MORPH = "MORPH",
	CHANGE_BODY = "CHANGE_BODY",
	//重置护盾
	RESET_BLOOD_SHIELD = "RESET_BLOOD_SHIELD",
}

export enum SceneViewEvent {
	ADD_TO_STAGE = "addToStage",
}

export enum ServiceReceiveEvent {
	BUILDING_QUICKEN_RECEIVE = "buildingQuickenReceive",
	PAWN_RECRUIT_LIST_RECEIVE = "pawnRecruitListReceive",
	SICK_PAWN_LIST = "sickpawnlist",
	ARMY_LIST_RECEIVE = "armyListReceive",
	ARMY_PAWN_LIST_RECEIVE = "armyPawnListReceive",
	GET_HERO_RECEIVE = "getHeroReceive",
	FREE_HERO_RECEIVE = "freeHeroReceive",
	AUTO_SETUP_ARMY_RECEIVE = "setupArmyReceive",
	SETUP_ARMY_RECEIVE = "setupArmyReceive",
	DISBAND_ARMY_RECEIVE = "disbandArmyReceive",

	TECHNOLOGY_LIST_RECEIVE = "technologyListReceive",
	TECHNOLOGY_COOLDOWN_ALL = "TECHNOLOGY_COOLDOWN_ALL",
	TECHNOLOGY_UPGRADE_RECEIVE = "technologyUpgradeReceive",
	TECHNOLOGY_QUICKEN_RECEIVE = "technologyQuickenReceive",
	TECHNOLOGY_CANCEL_RECEIVE = "technologyCancelReceive",

	RECRUIT_SUCCESS = "recruitsuccess",
	RECRUITED_PAWN_LIST = "recruitedpawnlist",
	GET_BYID_SUCCESS = "getbyidsuccess",
	UPGRADE_PAWN_SUCCESS = "upgrade_pawn_success",

	CURE_PAWN_SUCCESS = "curepawnsuccess",

	HERO_REFRESH_RECEIVE = "heroRefreshReceive",
	HERO_EMPLOY_RECEIVE = "hero_employ_receive",

	HERO_TALENT_RECEIVE = "heroTalentReceive",

	TALENT_COMMIT_RECEIVE = "talentCommitReceive",
	MOVE_BAG_TO_BAG_RECEIVE = "moveBagToBagReceive",

	PLAYER_INFO_RECEIVE = "playerInfoReceive",
	HEROINFO_CHANGE = "heroInfoChange",
	HERO_LEVEL_UP = "heroLevelUp",
	PLAYER_LEVEL_UP = "playerLevelUp",

	TRANSEFER_CASTLE_SUCCESS = "TRANSEFER_CASTLE_SUCCESS",
	TRANSEFER_ARMY_SUCCESS = "TRANSEFER_ARMY_SUCCESS",
	COOL_SUCCESS = "coolsuccess",
	ADD_POWER_SUCCESS = "addpawnsuccess",

	GET_BUILDINFO_SUCCESS = "getbuildinfosuccess",
}

export enum SLGSocketEvent {
	// EVENT = "SLGSocketEvent",//弃用, 直接监听协议号
	GAME_CMD = "GAME_CMD",
	U_PLAY_MOVIE = "U_PLAY_MOVIE",
	UPDATE_CASTLE = "UPDATE_CASTLE",
	UPDATE_WILDLAND = "UPDATE_WILDLAND",
	UPDTAE_ARMY = "UPDTAE_ARMY",
}

export enum StartupEvent {
	CORE_LOAD_COMPLETE = "coreUILoadComplete",
	CORE_SETUP_COMPLETE = "coreSetupLoadComplete",
	ROLE_DATE_COMPLETE = "roleDataComplete",
}

export enum BattleEvent {
	BEFORE_BATTLE_END = "BEFORE_BATTLE_END",
	STATE_CHANGE = "stateChange",
	SYNCHRONIZATION = "synchronization",
	SKILL_CLICK = "SKILL_CLICK_BattleEvent",
	ACTION_COUNT_CHANGE = "actionCountChange",
	REDUCE_WORLD_BOSS_BLOOD = "reduceWorldBossBlood",
	BATTLE_CANCEL = "battleCancel",
	ATTACK_MODE_CHANGE = "battleModeChange",
	BATTLE_COMPLETE = "battleComplete",
	SELF_MOVE_START = "selfMoveStart",

	BATTLE_UI_LOADED = "battleUILoaded",
	ENTER_BATTLE_SCENE = "enterbattlescene",
	SCENE_EFFECT_CLOSE = "sceneEffectClose",
	SHAKE_MAP_COMPLETE = "shakeMapComplete",
	BATTLE_DYNAMIC_UI_LOADED = "BATTLE_DYNAMIC_UI_LOADED",
	BATTLE_BGANI_LOADED = "BATTLE_BGANI_LOADED",

	BATTLE_MUSIC_ON_OFF = "battleMusicOnOff",

	TRAIL_LAYER_CHANGE = "TRAIL_LAYER_CHANGE",
	TRAIL_USECOUNT_CHANGE = "TRAIL_USECOUNT_CHANGE",
	PROP_USECOUNT_CHANGE = "PROP_USECOUNT_CHANGE",

	ROLE_BUFF_CHANGE = "ROLE_BUFF_CHANGE",
	REINFORCE = "REINFORCE",
	OPEN_BUFFINFO_PANEL = "OPEN_BUFFINFO_PANEL",
	BATTLE_NOTICE = "BATTLE_NOTICE",
}
export enum BattleNotic {
	/**
	 * 重置行动力
	 */
	RESET_ACTION_TIME = "RESET_ACTION_TIME_BattleNotic",
	/**
	 * 开始行动力计时
	 * var maxTime:number,
	 */
	START_ACTION_TIME = "START_ACTION_TIME_BattleNotic",
	/**
	 * 释放技能
	 * var data:Object = {id:1,target:[6,7,8,9]}
	 * id 技能id,
	 * target 释放目标,
	 */
	ACTION_SKILL = "ACTION_SKILL_BattleNotic",
	/**
	 * 暂停行动力
	 */
	PAUSE_ACTION_TIME = "PAUSE_ACTION_TIME_BattleNotic",
	/**
	 * 恢复行动力
	 */
	RESUME_ACTION_TIME = "RESUMSE_BattleNotic",
	/**
	 * 显示技能使用成功
	 * var goodInfo:GoodsInfo
	 */
	SHOW_SKILL_USE_SUCCESS = "SHOW_SKILL_USE_SUCCESS_BattleNotic",
	/**
	 * 添加一个技能
	 */
	SHOW_SKILL_ITEM = "show_skill_item",
	/**
	 * 设置技能是否可选
	 * var enable:boolean = true,
	 */
	SKILL_ENABLE = "SKILL_ENABLE",
	SPECIAL_SKILL_ENABLE = "SPECIAL_SKILL_ENABLE",
	/**
	 * buffer影响技能是否可用
	 * var enable:boolean = true,
	 */
	BUFFER_SKILL_ENABLE = "BUFFER_SKILL_ENABLE",
	/**
	 * 强制设置技能是否可选
	 * var enable:boolean = true,
	 */
	FORCE_SKILL_ENABLE = "FORCE_SKILL_ENABLE",
	/**
	 * 显示技能条
	 */
	SHOW_SKILL_BAR = "show_skill_bar",
	/**
	 * 设置连击数
	 * var count:number = 10,
	 */
	SET_BATTER_COUNT = "SET_BATTER_COUNT_BattleNotic",
	/**
	 * 设置总伤害值
	 * var count:number = 10,
	 */
	SET_TOTAL_DAMAGE = "SET_TOTAL_DAMAGE_BattleNotic",
	/**
	 * 设置连击UI是否可见
	 * var isVisible:boolean = true,
	 */
	SET_BATTERUI_VISIBLE = "SET_BATTERUI_VISIBLE_BattleNotic",
	/**
	 * 设置抗性总伤害值
	 */
	SET_RESIST_TOTAL_DAMAGE = "SET_RESIST_TOTAL_DAMAGE",
	/**
	 * 设置抗性UI是否可见
	 */
	SET_RESIST_VISIBLE = "SET_RESIST_VISIBLE",
	/**
	 * 显示技能名,
	 * var name:string = "光系必杀",
	 */
	SHOW_SKILL_NAME = "SHOW_SKILL_NAME_BattleNotic",
	/**
	 * 首次攻击,
	 */
	FIRST_ATTACK = "FIRST_ATTACK_BattleNotic",
	/**
	 * 重新刷新扭曲效果使用的背景,
	 */
	REFRESH_BACK_BITMAP = "REFRESH_BACK_BITMAP",

	RESTRICT_CHANGED = "restrictChanged",

	SKILL_CD = "skillCd",
	/**
	 * 是否是自动战斗状态改变.
	 */
	AUTO_FIGHT_CHANGED = "autoFightChanged",

	REMOTEPET_SKILL = "REMOTEPET_SKILL",

	PETPK_ACTION_SKILL = "PETPK_ACTION_SKILL",
}

export enum SpaceEvent {
	TARGET_CHANGE = "TARGET_CHANGE",
	HIDE_OTHERS = "HIDE_OTHERS",
	FIND_NODE = "FIND_NODE",
	SELECT_NODE = "SELECT_NODE",
	HIDE_OTHER_NAME = "HIDE_OTHER_NAME",
}

export enum FreedomTeamEvent {
	ADD_MEMBER = "ADD_MEMBER",
	REMOVE_MEMBER = "REMOVE_MEMBER",
	TEAM_INFO_UPDATE = "TEAM_INFO_UPDATE",
	/**
	 * 同步位置（地图id,坐标）, 状态（在线, 离线）
	 */
	TEAM_INFO_SYNC = "TEAM_INFO_SYNC",
	EDIT_TEAM_FIGHT_POS = "EDIT_TEAM_FIGHT_POS",
}

export enum ArmyEvent {
	RECIEVED_ARMY = "RECIEVED_ARMY",
	ARMY_INFO_CHANGE = "ARMY_PAWN_CHANGE",
	UPDATE_STATE = "UPDATE_STATE",
	UPDATE_CASTLE = "UPDATE_CASTLE",
	SORT_PAWN = "SORT_PAWN",
	PETINFO_CHANGED = "PETINFO_CHANGED",
	TATTOO_INFO = "TATTOO_INFO",
	TATTOO_NEWHOLE_SELECT = "TATTOO_NEWHOLE_SELECT",
}

//兵种相应事件
export enum PawnEvent {
	PAWN_PROPERTY_CHAGER = "pawnProppertyChager",
	SPECIAL_ALIBITY = "SPECIAL_ALIBITY",
	SPECIAL_BLESS = "SPECIAL_BLESS",
}

export enum BagEvent {
	BAG_GOODS_CHANGE = "BAG_GOODS_CHANGE",
	UPDATE_BAG = "UPDATE_BAG",
	DELETE_BAG = "DELETE_BAG",
	ADD_GOODS = "ADD_GOODS", //不同于NEW_GOODS事件, 该事件
	NEW_GOODS = "NEW_GOODS",
	INTENSIFY_GOODS = "INTENSIFY_GOODS",
	FILTER_GOODS = "FILTER_GOODS",
	CHECK_BAG_FULL = "BAG_FULL",
	RETURN_REFRESH = "RETURN_REFRESH", //出售物品返回失败或者出售失败刷新背包遮罩
	UPDATE_BOTTLE_BAG = "UPDATE_BOTTLE_BAG", //获得魔罐物品
	DELETE_BOTTLE_BAG = "DELETE_BOTTLE_BAG", //删除魔罐物品
	DELETE_FISH_BAG = "DELETE_FISH_BAG", //删除鱼篓物品
	SELL_GOODS = "SELL_GOODS", //点击出售物品后选择物品
	SELLITEM_DELETE = "SELLITEM_DELETE", //删除出售框中单件物品
	COUNT_CHANGE = "COUNT_CHANGE", //修改出售框中物品数量
	FILTR_BY_SELL = "FILTR_BY_SELL", //修改批量出售状态后设置滤镜
	ATTRIBUTE_CLICK = "ATTRIBUTE_CLICK", //点击背包界面的“属性”按钮
	DELETE_TREASURE_MAP = "DELETE_TREASURE_MAP", //删除藏宝图
	ADD_RUNE_GEM = "ADD_RUNE_GEM", //获得符石
	ADD_PET_EQUIP = "ADD_PET_EQUIP", //穿戴英灵装备
	DELETE_PET_EQUIP = "DELETE_PET_EQUIP", //卸下或分解英灵装备
	NEW_EQUIP = "NEW_EQUIP", //新装备
}

export enum ConsortiaEvent {
	UPDE_ALTAR_SIZE = "UPDE_ALTAR_SIZE",
	IS_CONSORTIA_EXIST = "IS_CONSORTIA_EXIST",
	ON_BLESS_COMPLETE = "ON_BLESS_COMPLETE",
	ON_TEMPLETEID_UPDATA = "ON_TEMPLETEID_UPDATA",
	UPDE_MEMEBER_STATE = "UPDE_MEMEBER_STATE",
	UPDE_CONSORTIA_SEARCH_PAGE = "UPDE_CONSORTIA_SEARCH_PAGE",
	UPDE_CONTRIBUTION_SEARCH_PAGE = "UPDE_CONTRIBUTION_SEARCH_PAGE",
	UPDE_RECRUIT_SEARCH_PAGE = "UPDE_RECRUIT_SEARCH_PAGE",
	UPDE_SHOP_SEARCH_PAGE = "UPDE_SHOP_SEARCH_PAGE",
	UPDE_SHOP_GOODS_LIST = "UPDE_SHOP_GOODS_LIST",
	UPDE_ALTAR_GOODS = "UPDE_ALTAR_GOODS",
	UPDA_COOLDOWN_TIME = "UPDA_COOLDOWN_TIME",
	UPDA_CONSORTIA_LIST = "UPDA_CONSORTIA_LIST",
	UPDA_CONSORTIA_EVENT_LIST = "UPDA_CONSORTIA_EVENT_LIST",
	UPDA_RECORD_LIST = "UPDA_RECORD_LIST",
	UPDA_ALTAR_BLESS_INFO = "UPDA_ALTAR_BLESS_INFO",
	UPDA_ALTAR_BLESS = "UPDA_ALTAR_BLESS", //祈福失败
	UPDA_CONSORTIA_INFO = "UPDA_CONSORTIA_INFO",
	GET_CONSORTIA_INFO = "GET_CONSORTIA_INFO",
	UPDA_APPLY_CONSORTIA_INFO = "UPDA_APPLY_CONSORTIA_INFO",
	UPDA_CONSORTIA_CONTRIBUTE_INFO = "UPDA_CONSORTIA_CONTRIBUTE_INFO",
	UPDA_CONSORTIA_RIGHTS = "UPDA_CONSORTIA_RIGHTS",
	UPDA_CONSORTIA_SKILL_LIST = "UPDA_CONSORTIA_SKILL_LIST",
	UPDA_ALTAR_BLESS_LEFT_TIME = "UPDA_ALTAR_BLESS_LEFT_TIME",
	UPDATA_CONSORTIA_MEMBER = "UPDATA_CONSORTIA_MEMBER",
	UPDA_CONSORTIA_CHAIRMAN = "UPDA_CONSORTIA_CHAIRMAN",
	CONSORTIA_UPGRADE = "CONSORTIA_UPGRADE",
	CONSORTIA_ITEM_CLICK = "CONSORTIA_ITEM_CLICK",
	APPLY_PLAYER_ITEM_CLICK = "APPLY_PLAYER_ITEM_CLICK",
	GET_ALTAR_GOODS = "GET_ALTAR_GOODS",
	APPLY_CONSORTIA_SUCCESS = "APPLY_CONSORTIA_SUCCESS",
	APPLY_CONSORTIA_RECEIVE = "APPLY_CONSORTIA_RECEIVE",
	SHOW_MEMBER_LIST = "SHOW_MEMBER_LIST",
	ON_CONSORTIA_CONTRIBUTE_SUCCEED = "ON_CONSORTIA_CONTRIBUTE_SUCCEED",
	CONSORTIA_STUDY = "CONSORTIA_STUDY",
	CONSORTIA_STUDY_UPGRADE = "CONSORTIA_STUDY_UPGRADE",
	RECRUITNUM_CHANGED = "recruitnum_changed",
	MEMBERLIST_SELECTED_CHANGE = "MEMBERLIST_SELECTED_CHANGE",
	CONSORTIA_OFFER_CHANGE = "CONSORTIA_OFFER_CHANGE",
	CONSORTIA_VOTINGLIST_CHANGE = "CONSORTIA_VOTINGLIST_CHANGE",
	SECRET_UPDATE = "SECRET_UPDATE",
	TREE_STATE_UPDATE = "TREE_STATE_UPDATE",
	PICK_TIME_UPDATE = "PICK_TIME_UPDATE",
	DEMON_SWITCH = "DEMON_SWITCH",
	DEMON_INFO_UPDATE = "DEMON_INFO_UPDATE",
	DEMON_DURA_CHANGE = "DEMON_DURA_CHANGE",
	DEMON_WAVE_CHANGE = "DEMON_WAVE_CHANGE",
	DEMON_SKILL_USED = "DEMON_SKILL_USED",
	PRIZE_LIST_UPDATE = "PRIZE_LIST_UPDATE",
	PRIZE_LIST_COUNT_UPDATE = "PRIZE_LIST_COUNT_UPDATE",
	PRIZE_MEMBER_LIST_UPDATE = "PRIZE_MEMBER_LIST_UPDATE",
	REFRESH_CONSORTIA_NAME = "REFRESH_CONSORTIA_NAME",
	GOTO_GUILD_FIGHT = "GOTO_GUILD_FIGHT",
	CONSORTIA_MATERIAL = "CONSORTIA_MATERIAL",

	TASK_INFO = "TASK_INFO", // 任务信息
	TASK_WEEK_REWARD = "TASK_WEEK_REWARD",// 任务周公会总积分奖励
	TASK_RECORD = "TASK_RECORD", // 任务完成记录
	SECRET_SEENED = "SECRET_SEENED",

}

export enum GvgEvent {
	GUILD_ORDER_INFO_LIST = "GUILD_ORDER_INFO_LIST",
	GUILD_CHALLENGE_LIST = "GUILD_CHALLENGE_LIST",
	GUILD_INFO_CHANGE = "GUILD_INFO_CHANGE",
	SELECT_MEMBER_ITEM = "SELECT_MEMBER_ITEM",
	UPDATE_GUILD_GROUP = "UPDATE_GUILD_GROUP",
	UPDATE_GUILD_ORDER_GROUP = "UPDATE_GUILD_ORDER_GROUP",
	UPDATE_CURRENT_COUNT = "UPDATE_CURRENT_COUNT",
	GUILDWAR_OPEN_LEFTTIME = "GUILDWAR_OPEN_LEFTTIME",
	GUILDWAR_PLAYER_COUNT = "GUILDWAR_PLAYER_COUNT",
	TOP_TEN_CHANGE = "TOP_TEN_CHANGE",
}

export enum PetEvent {
	PETINFO_CHANGE = "PETINFO_CHANGE",
	PET_DATA = "PET_DATA",
	PET_ADD = "PET_ADD",
	PET_UPDATE = "PET_UPDATE",
	PET_REMOVE = "PET_REMOVE",
	ENTERWAR_PET_CHANGE = "PET_ENTERWAR_CHANGE",
	PET_LEVEL_UP = "PET_LEVEL_UP", //英灵升级
	PET_CHANGE_SKILL_CHANGE = "PET_CHANGE_SKILL_CHANGE", //英灵已学会的变身技能改变
	PET_FAST_SKILL_CHANGE = "PET_FAST_SKILL_CHANGE", //英灵携带的变身技能改变
	PET_CHALLENGE_SKILL_CHANGE = "PET_CHALLENGE_SKILL_CHANGE", //英灵竞技携带的变身技能改变
	PET_REMOTE_SKILL_CHANGE = "PET_REMOTE_SKILL_CHANGE", //英灵远征携带的变身技能改变
	PET_MAXCOUNT_CHANGE = "PET_MAXCOUNT_CHANGE", //英灵携带上限
	PET_SELECT_CHANGE = "PET_SELECT_CHANGE", //选择一个英灵
	PET_SELECT_SECONDARY = "PET_SELECT_SECONDARY", //选择副英灵
	PET_BOSS_ITEM_CLICK = "PET_BOSS_ITEM_CLICK", //
	PET_EUIP_PART = "PET_EUIP_PART", //选择一个英灵装备部位
	PET_EUIP_BAG_PART = "PET_EUIP_BAG_PART", //选择英灵背包中的一个部位
	REPLACE_PET_EQUIP = "REPLACE_PET_EQUIP", //替换英灵装备
	STERN_PET_EQUIP = "STERN_PET_EQUIP", //强化英灵装备
	PET_SELECT_FORMATION_CHANGE = "PET_SELECT_FORMATION_CHANGE", //上阵英灵改变
}

export enum LoadingSceneEvent {
	CLOSE = "CLOSE",
}

export enum ObjectsEvent {
	WALK_OVER = "walkOver",
	WALK_NEXT = "WALK_NEXT",
}

export enum RuneEvent {
	RUNE_UPGRADE = "RUNE_UPGRADE",
	SET_FAST_KEY = "RUNE_SET_FAST_KEY",
	FAST_KEY_MOVE = "RUNE_FAST_KEY_MOVE",
	SHOW_INLAY_RUNE_BAG = "SHOW_INLAY_RUNE_BAG", //显示或隐藏镶嵌背包
	RESOLVE_RUNE_GEM = "RESOLVE_RUNE_GEM",
	RUNE_GEM_RESOLVE = "RUNE_GEM_RESOLVE",
	RUNE_GEM_UPGRADE = "RUNE_GEM_UPGRADE",
	INLAY_RUNE_GEM = "INLAY_RUNE_GEM", //镶嵌符文石
	PUTOFF_RUNE_GEM = "PUTOFF_RUNE_GEM", //卸下符文石
	SHOW_REPLACE_RUNE_GEM = "SHOW_REPLACE_RUNE_GEM", //显示替换符文石
	REPLACE_RUNE_GEM = "REPLACE_RUNE_GEM", //替换操作符文石
	RECV_REPLACE_RUNE_HOLE = "RECV_REPLACE_RUNE_HOLE", //替换符孔
	CARVE_RUNE = "CARVE_RUNE", //雕刻
	ACTIVE_RUNEGEM = "ACTIVE_RUNEGEM", //开启符石
	PEPLACE = "PEPLACE", //
	CLOSE_GEM = "CLOSE_GEM", //关闭符石获取界面
	CANCEL_RESOLOVE = "CANCEL_RESOLOVE", //取消分解
}

export enum SkillEvent {
	SKILL_UPGRADE = "SKILL_SKILL_UPGRADE",
	SKILL_RESET = "SKILL_SKILL_RESET",
	OPEN_RUNE_VIEW = "SKILL_OPEN_RUNE_VIEW",
	SET_FAST_KEY = "SKILL_SET_FAST_KEY",
	FAST_KEY_MOVE = "SKILL_FAST_KEY_MOVE",
	REFRESH_LINE = "SKILL_REFRESH_LINE",
	CHANGE_SKILL = "CHANGE_SKILL",
	SKILL_EDIT = "SKILL_EDIT",
	PUTOFF = "PUTOFF",
	PUTON = "PUTON",
	RESET_SKILL_STATE = "RESET_SKILL_STATE",
	UPDATE_SKILL_POINT = "UPDATE_SKILL_POINT",
	DRAG = "DRAG",
	REPLACE = "REPLACE", //拖动替换
	SWITCH_MASTERY = "SWITCH_MASTERY", //切换专精技能
	CLICK_MASTERY_SKILL = "CLICK_MASTERY_SKILL", //
	DRAGING = "DRAGING", //
}

export enum TalentEvent {
	TALENT_UPGRADE = "TALENT_UPGRADE",
	TALENT_GRADUP_SUCC = "TALENT_GRADUP_SUCC",
	TALENT_RESET = "TALENT_RESET",
	UPDATE_TALENT = "UPDATE_TALENT",
	SELECT_TALENT = "SELECT_TALENT",
	SET_FAST_KEY = "TALENT_SET_FAST_KEY",
	UPDATE_TREE = "UPDATE_TREE",
}

export enum FateGuardEvent {
	FATE_GUARD_GP = "fategpchange",
}

export enum ExtraJobEvent {
	LEVEL_UP = "LEVEL_UP",
	STAGE_UP = "STAGE_UP",
	CLICK_INLAY = "CLICK_INLAY",
	SELECT_HOLE = "SELECT_HOLE",
}

export enum WaterEvent {
	CREATE_TREE = "CREATE_TREE",
	PRE_SELECTED = "PRE_SELECTED",
	NEXT_SELECTED = "NEXT_SELECTED",
	SELECTED_TREE_CHANGE = "SELECTED_TREE_CHANGE",
	WATER_LOG_UPDATE = "WATER_LOG_UPDATE",
	TREE_UPDATE = "TREE_UPDATE",
	CLEAN_WATER_EFFECT = "CLEAN_WATER_EFFECT",
	UPDATA_WATER_STATE = "UPDATA_WATER_STATE",
	GP_CHANGED = "gp_changed",
	GRAGE_CHANGED = "grade_changed",
}

export enum MsgEventType {
	/**
	 *显示地图名动画
	 */
	SHOW_MAP_NAME_MOVIE = "SHOW_MAP_NAME_MOVIE",
	/**
	 *显示通关条件
	 */
	SHOW_CONDITIONS_FRAME = "SHOW_CONDITIONS_FRAME",
	/**
	 * 会话完成
	 */
	SESSION_OVER = "SESSION_OVER",
	/**
	 *二级密码操作成功
	 */
	VICE_PASSWORD_OP_SUCCESS_EVENT = "yishi.datas.consant.VICE_PASSWORD_OP_SUCCESS_EVENT",
}
export enum CampaignMapEvent {
	PREPARE_BATTLE_FRAME2_COLSE = "PREPARE_BATTLE_FRAME2_COLSE",
	UPDATE_HOUSE_OWNER = "UPDATE_HOUSE_OWNER",
	UPDATE_IS_PLAYING = "UPDATE_IS_PLAYING",
	UPDATE_CAMPAIGN_ARMY = "UPDATE_CAMPAIGN_ARMY",
	ONLINE_STATE = "ONLINE_STATE",
	UPDATE_CAMPAIGN_NODE_STATE = "UPDATE_CAMPAIGN_NODE_STATE",
	NEXT_NODE_GUIDE_TIME = "NEXT_NODE_GUIDE_TIME",
	NEXT_NODE_GUIDE_TIME_OVER = "NEXT_NODE_GUIDE_TIME_OVER",
	SYS_FOG_DATA = "SYS_FOG_DATA",
	LOCAL_UPDATE_FOG = "LOCAL_UPDATE_FOG",
	SYN_FOG_DATA = "SYN_FOG_DATA",
	UPDATE_CHEST_INFO = "UPDATE_CHEST_INFO",
	ADD_CHEST_NODE = "ADD_CHEST_NODE",
	ATTACK_BOSS_TEMA = "ATTACK_BOSS_TEMA",
	ATTACK_BOSS_INVITE = "ATTACK_BOSS_INVITE",
	MOVE_SCENET_END = "MOVE_SCENET_END",
	DRAG_SCENE_END = "DRAG_SCENE_END",
	LOOK_AT_ROLE = "LOOK_AT_ROLE",
	CREATE_ARMY = "CREATE_ARMY",
	IS_DIE = "IS_DIE",
	MOVE_PATHS_ARMY = "MOVE_PATHS_ARMY",
	GO_TO_POS = "GO_TO_POS",
	UPDATE_WALK_TARGET = "UPDATE_WALK_TARGET",
	HANGUP_STATE = "hangupState",
	HANGUP_ADD = "hangupadd",
	TRANSEFER_WAIT_STATE = "transeferWaitState",
	MAZE_DIE = "MAZE_DIE",
	BUFFER_TEMP_ID = "BUFFER_TEMP_ID",
	UPDATE_PVP_SCORE = "UPDATE_PVP_SCORE",
	UPDATE_PVP_GESTE = "UPDATE_PVP_GESTE",
	UPDATE_TEAM_ID = "UPDATE_TEAM_ID",
	SYNC_ERROR_TIME = "syncErrorTime",
	OPENTIME_MV = "opentimemv",
	MOVE_TO_VISIBLE = "MOVE_TO_VISIBLE",
	MOVE_TO_UNVISIBLE = "MOVE_TO_UNVISIBLE",
}

export enum OuterCityEvent {
	NINE_SLICE_SCALING = "nineSliceScaling", //9宫格
	CURRENT_CONFIG_CHANGE = "currentConfigChange", //当前图片配置更新
	READ_FILE_OVER = "readFileOver", //读配置文件完成
	CURRENT_CASTLES = "currentCastles", //当前城堡接收到
	CURRENT_WILD_LAND = "currentWildLand", //当前野地收到
	CURRENT_NPC_POS = "currentNpcPos", //当前NPC收到
	BEGIN_LOADING = "beginLoading", //绑定
	COMMIT_LOADING = "commitLoading", //提交
	ADD_GARRISON = "addGarrison", //增加軍队
	UPDATE_SELF = "updateSelf", //更新自己
	REMOVE_ARMY = "REMOVE_ARMY", //用户退出时, 删去部队
	ADD_PLUNDER = "addPlunder", //掠夺
	ADD_DIJKSTRA = "addDijkstra",
	OVERSTEP = "overstep", //军队超出显示范围
	CENTER_POINT = "centerPoint",
	LAY_MAP_ARMY = "layMapArmy", //显示地图上部队位置
	RETURN_HOME = "return_home",
	POSATION_POINT = "POSATION_POINT", //定点传送
	CURRENT_TREASURE_LAND = "CURRENT_TREASURE_LAND",
	REFRESH_NPC = "REFRESH_NPC",
	CHANGE_HERO_FOCUS = "changeHeroFocus", //改变左边英雄图标的焦点
	TARGET_POINT = "target_point",
	UPDATA_MAP_PHYSICS = "UPDATA_MAP_PHYSICS",
	DRAG_SCENE_END = "DRAG_SCENE_END",
	DRAG_SCENE_START = "DRAG_SCENE_START",
	ADD_NPCS = "ADD_NPCS",
	START_MOVE = "START_MOVE",
	MOVE_OVER = "MOVE_OVER",
	REMOVE_NODE = "REMOVE_NODE",
	SELECT_PK_ARMY = "selectPkArmy",

	REMOVE_NODE_NPC = "REMOVE_NODE_NPC",
	REMOVE_NODE_MOVIE = "REMOVE_NODE_MOVIE",
	REMOVE_CASTLE = "REMOVE_CASTLE",
	MAP_MOVE = "MAP_MOVE",
	/**
	 * 外城为建筑添加散开的迷雾
	 */
	ADD_DENSEFOG_BY_BUILD = "OUTERCITY_ADD_DENSEFOG_BY_BUILD",
	/**
	 *外城获得BOSS信息数据
	 */
	OUTER_CITY_GET_BOSSINFO = "OUTER_CITY_GET_BOSSINFO",
	/**
	 *刷新外城BOSS刷新时间
	 */
	OUTER_CITY_UPDATE_BOSS_TIME = "OUTER_CITY_UPDATE_BOSS_TIME",
	/**
	 *外城移除迷雾
	 */
	OUTER_CITY_REMOVE_FOG = "OUTER_CITY_REMOVE_FOG",
	/**
	 *外城恢复迷雾
	 */
	OUTER_CITY_ADD_FOG = "OUTER_CITY_ADD_FOG",
	/**
	 *外城掉落怪物宝箱
	 */
	OUTER_CITY_UPDATE_BOX = "OUTER_CITY_UPDATE_BOX",
	/**
	 * 宝矿简要信息更新
	 */
	UPDATE_TREASURE_INFO = "UPDATE_TREASURE_INFO",
	/**
	 * 外城三级节点更新
	 */
	UPDATE_THREE_NODE_DATA = "UPDATE_THREE_NODE_DATA",
	/**
	 * 外城二级节点更新
	 */
	UPDATE_SECOND_NODE_DATA = "UPDATE_SECOND_NODE_DATA",
	/**
	 * 外城二级节点初始化
	 */
	INIT_SECOND_NODE_DATA = "INIT_SECOND_NODE_DATA",

	ADD_DENSEFOG_BY_MINE = "ADD_DENSEFOG_BY_MINE",

	UPDATE_MEMBER_POSITION = "UPDATE_MEMBER_POSITION",
	OUTERCITY_SELECTE_CANCEL = "OUTERCITY_SELECTE_CANCEL",
	CLOSE_OUTERCITY_RESOURCE_WND = "CLOSE_OUTERCITY_RESOURCE_WND",
	CLOSE_OUTERCITY_OUTERCITYBOSS_WND = "CLOSE_OUTERCITY_OUTERCITYBOSS_WND",
	OUTERCITY_LOCK_WAR_FIGHT = "OUTERCITY_LOCK_WAR_FIGHT",
	SELF_CASTLE = "SELF_CASTLE",
	UPDATE_SECOND_NODE_SELE_DATA = "UPDATE_SECOND_NODE_SELE_DATA",
	OUTERCITY_UNLOCK_WAR_FIGHT = "OUTERCITY_UNLOCK_WAR_FIGHT",
	OUTERCITY_CLICK = "OUTERCITY_CLICK",
	CASTLE_INFO = "OUTERCITY_CASTLE_INFO",
	OUTER_CITY_VEHICLE_UPDATE = "OUTER_CITY_VEHICLE_UPDATE",
	OUTERCITY_LOCK_VEHICLE_FIGHT = "OUTERCITY_LOCK_VEHICLE_FIGHT",
	OUTERCITY_UNLOCK_VEHICLE_FIGHT = "OUTERCITY_UNLOCK_VEHICLE_FIGHT",
}
export enum KingContractEvents {
	UPDATE_KINGCONTRACT = "UPDATE_KINGCONTRACT",
}
export enum CampaignEvent {
	SELECT_ITEM = "SELECT_ITEM",
	CONTINGEN_LIST_CHANGE = "CONTINGEN_LIST_CHANGE",
	UPDATE_CAMPAIGN_ROOM = "UPDATE_CAMPAIGN_ROOM",
	ADD_CAMPAIGN_ROOM = "ADD_CAMPAIGN_ROOM",
	CAMPAIGN_ROOM_MEMBER_LIST_CHANGE = "CAMPAIGN_ROOM_LIST_MEMBER_CHANGE",
	ADD_CAMPAIGN_ROOM_MEMBER_CHANGE = "ADD_CAMPAIGN_ROOM_MEMBER_CHANGE",
	REMOVE_CAMPAIGN_ROOM_MEMBER_CHANGE = "REMOVE_CAMPAIGN_ROOM_MEMBER_CHANGE",
	CUR_CAMPAIGN_TEMPINFO = "curCampaignTempInfo", //当前战役模板信息
	CUR_CAMPAIGN_ROOM = "curCampaignRoom",
	ENTER_CAMPAIGN_SCENE = "ENTER_CAMPAIGN_SCENE", //从房间过入战役
	SWITCH_STATE = "SWITCH_STATE",
	MOVE_ARMY_TO_RANGE = "MOVE_ARMY_TO_RANGE",
	GET_SYS_ARMY_INFO = "GET_SYS_ARMY_INFO",
	SYS_ARMY_UPDATE = "SYS_ARMY_UPDATE",
	PLAYER_NODE_MOVIE = "PLAYER_NODE_MOVIE",
	SHOW_FALLGOODS_SELECTITEM = "show_fallgoods_selectItem",
	NPC_ATTACK_ARMY = "NPC_ATTACK_ARMY",
	UPDATE_SMALL_MAP_ICON = "UPDATE_SMALL_MAP_ICON",
	STANDPOS = "STANDPOS",
	MOVE_NPC = "MOVE_NPC",
	NPC_CHASE = "NPC_CHASE",
	UPDATE_GVG_INFO = "UPDATE_GVG_INFO",
	UPDATE_MINERAL_INFO = "UPDATE_MINERAL_INFO",
	UPDATE_MINERAL_CAR = "UPDATE_MINERAL_CAR",
	CAMPAIGN_OVER = "CAMPAIGN_OVER",
	PET_BOSS_SWITCH = "PET_BOSS_SWITCH",
	AUTO_WALK_CHANGED = "AUTO_WALK_CHANGED",
	CAMPAIGN_CREATE = "CAMPAIGN_CREATE",
	WORLDBOSS_AUTO_WALK_CHANGED = "WORLDBOSS_AUTO_WALK_CHANGED",
}
export enum RoomEvent {
	UPDATE_ROOM_MAP = "UPDATE_ROOM_MAP",
	UPDATE_ROOM_BASE_DATA = "UPDATE_ROOM_BASE_DATA",
	UPDATE_ROOM_PLAYER_DATA = "UPDATE_ROOM_PLAYER_DATA",
	UPDATE_TEAM_FIGHT_POS = "UPDATE_TEAM_FIGHT_POS",
	EDIT_TEAM_FIGHT_POS = "EDIT_TEAM_FIGHT_POS",
	ADD_PLAYER_ROOM = "ADD_PLAYER_ROOM",
	REMOVE_PLAYER_ROOM = "REMOVE_PLAYER_ROOM",
	ROOM_HOUSEOWNER_CHANGE = "room_HouseOwner_change",
	PLAYER_READY = "player_ready",
	PLAYER_CENCEL = "player_cancel",
	ROOM_LIST_PLAYER = "ROOM_LIST_PLAYER",
	RANK_INFO_LIST = "rankInfoList",

	ROOM_PLACE_STATE_CHANGE = "ROOM_PLACE_STATE_CHANGE",

	/** 房间列表刷新 */
	REFRESH_ROOM_LIST = "REFRESH_ROOM_LIST",
}

export enum FriendUpdateEvent {
	UPDATE_RECOMONDLIST = "UPDATE_RECOMONDLIST",
	FRIEND_CHANGE = "friendchange",
	FRIEND_UPDATE = "FRIEND_UPDATE",
	ADD_FRIEND = "ADD_FRIEND",
	REMOVE_FRIEND = "REMOVE_FRIEND",
	ADD_RECENT_CONTACT = "ADD_RECENT_CONTACT",
	RECENT_CONTACT_UPDATE = "RECENT_CONTACT_UPDATE",

	INVITE_UPDATE = "INVITE_UPDATE",
}

export enum IMEvent {
	/**
	 *消息盒子闪动更新
	 */
	MSGBOX_SHINING_UPDATE = "MSGBOX_SHINING_UPDATE",
	/**
	 *信息列表删除
	 */
	MSG_LIST_DEL = "MSG_LIST_DEL",
	/**
	 *信息发送响应
	 */
	MSG_SEND_RESPONSE = "MSG_SEND_RESPONSE",
	/**
	 *收到信息
	 */
	RECEIVE_MSG = "RECEIVE_MSG",
	/**
	 *收到语音信息
	 */
	RECEIVE_VOICE_MSG = "RECEIVE_VOICE_MSG",
	/**
	 *翻译聊天消息
	 */
	TRANSLATE_MSG = "TRANSLATE_MSG",
}

export enum IMFrameEvent {
	DISPOSE = "IMFRAME_DISPOSE",
	REMOVE = "IMFRAME_REMOVE",
}

export enum SocketDataProxyEventEvent {
	READ_SOCKET_DATA_OVEW = "READ_SOCKET_DATA_OVEW",
}
export enum SceneEvent {
	SWITCH_SCENE_LOCK = "SWITCH_SCENE_LOCK",
	SCENE_SWITCH_CALL = "SCENE_SWITCH_CALL",
	LOCK_SCENE = "LOCK_SCENE",
	BLUR_MASK = "BLUR_MASK",
	RM_WINDOW = "RM_WINDOW",
	HIDE_SCENE_OBJ = "HIDE_SCENE_OBJ",
}

export enum WinEvent {
	GROUP_CONFLICT = "GROUP_CONFLICT",
	RETURN_TO_WIN = "RETURN_TO_WIN", // 关闭自身, 打开上一个界面
	SHOW = "SHOW",
	HIDE = "HIDE",
}

export enum BuildOrderEvent {
	ADD_ONE_ORDER = "ADD_ONE_ORDER",
	USE_ONE_ORDER = "USE_ONE_ORDER",
	COLL_ONE_ORDER = "COLL_ONE_ORDER",
	UPDATE_ORDER = "UPDATE_ORDER",
}

export enum FarmEvent {
	SELECTED_CHANGE = "SELECTED_CHANGE",
	FARM_GP_CHANGE = "FARM_GP_CHANGE",
	FARM_GRADE_CHANGE = "FARM_GRADE_CHANGE",
	LAND_GRADE_CHANGE = "LAND_GRADE_CHANGE",
	LAND_OPEN = "LAND_OPEN",
	LANDINFO_UPDATE = "LANDINFO_UPDATE",
	FRIEND_FARM_STATE_CHANGE = "FRIEND_FARM_STATE_CHANGE",
	OPER_BACK = "OPER_BACK",
	PET_LAND_OPEN = "PET_LAND_OPEN",
	PET_LAND_UPDATE = "PET_LAND_UPDATE",
	FARM_DEFENDER_CHANGE = "FARM_DEFENDER_CHANGE",
	LIGHT_AVAILABLE_LAND = "LIGHT_AVAILABLE_LAND",
	SHOW_AKEY_BTN = "SHOW_AKEY_BTN", // 一键处理按钮
}

/**
 *社交模板加载完成
 */
export enum SNSEvent {
	SNSTEMP_LOAD_COMPLETE = "SNSTEMP_LOAD_COMPLETE",
	/**
	 *社交信息更新
	 */
	SNSINFO_UPDATE = "SNSINFO_UPDATE",
}

export enum FindResultEvent {
	GET_FIND_RESULTS = "GET_FIND_RESULTS",
	GET_FIND_RESULTS_BY_NAME = "GET_FIND_RESULTS_BY_NAME",
}

export enum FriendGroupEvent {
	/**
	 *添加分组
	 */
	ADD_GROUP = "ADD_GROUP",
	/**
	 *删除分组
	 */
	DEL_GROUP = "DEL_GROUP",
	/**
	 *重命名分组
	 */
	RENAME_GROUP = "RENAME_GROUP",
	/**
	 *分组好友移动
	 */
	MOVE_FRIEND = "MOVE_FRIEND",

	FRIEND_ITEM_SELECTED = "FRIEND_ITEM_SELECTED", //选中列表中的一个
}

export enum ChatEvent {
	UPDATE_CHAT_VIEW = "UPDATE_CHAT_VIEW",
	UPDATE_BIGBUGLE_VIEW = "UPDATE_BIGBUGLE_VIEW",
	UPDATE_NOTICE_VIEW = "UPDATE_NOTICE_VIEW",
	CHAT_FROM_CONSORTIA = "CHAT_FROM_CONSORTIA",
	INPUT_CHANNEL_CHANGE = "INPUT_CHANNEL_CHANGE",
	OUTPUT_CHANNEL_CHANGE = "OUTPUT_CHANNEL_CHANGE",
	ADD_CHAT = "ADD_CHAT",
	ADD_PRIVATE_CHAT = "ADD_PRIVATE_CHAT",
	REMOVE_PRIVATE_CHAT = "REMOVE_PRIVATE_CHAT",

	CHANNEL_CLICK = "CHANNEL_CLICK",
	PLAYER_NAME_CLICK = "PLAYER_NAME_CLICK",
	CONSORTIA_CLICK = "CONSORTIA_CLICK",
	PROP_CLICK = "PROP_CLICK",
	EQUIP_CLICK = "EQUIP_CLICK",
	STAR_CLICK = "STAR_CLICK",
	CARD_CLICK = "CARD_CLICK",
	ROOM_CLICK = "ROOM_CLICK",
	VIP_LINK_CLICK = "VIP_LINK_CLICK",
	CHAT_MESSAGE = "CHAT_MESSAGE",
	HIDE_BATTLE_CHAT = "HIDE_BATTLE_CHAT",
	SHOW_NEW_MSG = "SHOW_NEW_MSG",
	BLACKLIST = "BLACKLIST",

	/**
	 * 称号查询点击事件
	 */
	APPELL_LINK_CLICK = "APPELL_LINK_CLICK",
	ROSE_BACK_CLICK = "ROSE_BACK_CLICK", //玫瑰回赠
	REINFORCE_CLICK = "REINFORCE_CLICK",

	CHAT_CHANNEL_CHANGE = "CHAT_CHANNEL_CHANGE",

	CHAT_NAME_CLICK = "CHAT_NAME_CLICK",
	SEEK_LINK_CLICK = "SEEK_LINK_CLICK", //前去寻宝

	CHAT_REFESH_TO_VIEW = "CHAT_REFESH_TO_VIEW",
	CLEAN_CHAT = "CLEAN_CHAT",
	OUTPUT_TEXT_SCROLL = "OUTPUT_TEXT_SCROLL",
	OUTPUT_SCROLL_SCROLL = "OUTPUT_SCROLL_SCROLL",

	CHAT_LOCK_CHANGE = "CHAT_LOCK_CHANGE",
	CHAT_LOCK_ENABLE_CHANGE = "CHAT_LOCK_ENABLE_CHANGE",

	SEND_GOODS = "SEND_GOODS",
	SEND_STAR = "SEND_STAR",
	SEND_CARD = "SEND_CARD",

	OUTER_CITY_BOSS_CLICK = "OUTER_CITY_BOSS_CLICK",

	FISH_CLICK = "FISH_CLICK",
	CHAT_EMJOY_CLICK = "CHAT_EMJOY_CLICK",
	UPDATE_SELECTED_PRIVATECHAT = "UPDATE_SELECTED_PRIVATECHAT",
	UPDATE_CHAT_VIEW_VISIBLE = "UPDATE_CHAT_VIEW_VISIBLE",
	UPDATE_CHAT_BUGLE_VIEW_VISIBLE = "UPDATE_CHAT_BUGLE_VIEW_VISIBLE",
}
export enum ChatDebugEvent {
	Debug = "Debug",
}
export enum VIPEvent {
	UPFRAMEVIEW_CHANGE = "upframeview_change",
	VIP_EFFCT_COMPLETE = "vipeffctcomplete",
	VIP_UPROULETTE_INFO = "vip_uprolette_info",
	VIP_RECHARGE_TIP = "vip_recharge_tip",
	VIP_OPEN_BOX = "vip_open_box",
	VIP_PRIVILEGE_UPDATE = "vip_privilege_update",
}

export enum AppellEvent {
	APPELL_DATA_UPDATA = "APPELL_DATA_UPDATA",
}

export enum MopupEvent {
	MOPUP_RESULT_LIST_REFRESH = "MOPUP_RESULT_LIST_REFRESH",
	MOPUP_END = "MOPUP_END",
}

export enum PhysicsEvent {
	UP_STATE = "UP_STATE",
	UP_SONTYPE = "UP_SONTYPE",
	FOLLOW_TARGET = "followTarget",
	VISIT_USER_ID = "_visitUserIds",
	CHAT_DATA = "CHAT_DATA",
	UPDATE_CUR_HP = "UPDATE_CUR_HP",
	WALK_NEXT_POINT = "WALK_NEXT_POINT",
	MOVE_POS = "MOVE_POS",
	PARA_1 = "PARA_1",
}

export enum JoyStickEvent {
	JoystickMoving = "JoystickMoving",
	JoystickUp = "JoystickUp",
	JoystickTriggerUp = "JoystickTriggerUp",
}

export enum BagSortEvent {
	BAG_SORT_SELECT = "BAG_SORT_SELECT",
	BAG_SORT_CHANGE = "BAG_SORT_CHANGE",
}

export enum StoreEvent {
	UPDATA_ITEM_DATA = "UPDATA_ITEM_DATA",
	UPDATE_COMPOSE_SELECTED_CELL = "UPDATE_COMPOSE_SELECTED_CELL",
	UPDATE_COMPOSE_TEMP_LIST = "UPDATE_COMPOSE_TEMP_LIST",
	UPDATE_COMPOSE_MAX_COUNT = "UPDATE_COMPOSE_MAX_COUNT",
	REFRESH_LOCK_CHANGE = "REFRESH_LOCK_CHANGE",
}

export enum MazeEvent {
	/**
	 *加载排行榜数据完成
	 */
	ORDERDATA_LOAD_COMPLETE = "ORDERDATA_LOAD_COMPLETE",

	UPDATE_SHOP_PAGE_DATA = "UPDATE_SHOP_PAGE_DATA",
	UPDATE_SHOP_GOODS_LIST = "UPDATE_SHOP_GOODS_LIST",
}
/**
 * 商城事件
 */
export enum ShopEvent {
	MAIN_TAB_CHANGE = "MAIN_TAB_CHANGE",
	CURSELECTED_TAB_CHANGE = "CURSELECTED_TAB_CHANGE",
	GOODS_INFO_UPDATE = "GOODS_INFO_UPDATE",
	GOODS_LIST_UPDATE = "GOODS_LIST_UPDATE",
	PAGE_UPDATE = "PAGE_UPDATE",
	SWITCH_FASHION_PANEL = "SWITCH_FASHION_PANEL",
	GOODS_SELECT_UPDATE = "GOODS_SELECT_UPDATE",
	BUY_DISCOUNT_RET = "BUY_DISCOUNT_RET",
	GOODS_DISCOUNT_UPDATE = "GOODS_DISCOUNT_UPDATE",
	PAGE_SELECTED = "PAGE_SELECTED",
	PRODUCT_UPDATE_COUNT = "PRODUCT_UPDATE_COUNT",
	PRODUCT_TODAY_UPDATE_COUNT = "PRODUCT_TODAY_UPDATE_COUNT",
	PRODUCT_WEEK_UPDATE_COUNT = "PRODUCT_WEEK_UPDATE_COUNT",
	SHOP_BUY_RESULT = "SHOP_BUY_RESULT",
	DISCOUNTSHOP_UPDATE = "DISCOUNTSHOP_UPDATE",
	DISCOUNTSHOP_OPENSTATE = "DISCOUNTSHOP_OPENSTATE",
}

export enum TaskEvent {
	TASK_DETAIL_CHANGE = "task_detail_change",
	TASK_ADDED = "task_added",
	MANUAL_TASK_ADDED = "manual_task_added",
	TASK_REMOVE = "task_remove",
	MANUAL_TASK_REMOVE = "manual_task_remove",
	TASK_SHOWTIPS = "task_showtips", //右下角提示
}

export enum MonopolyEvent {
	MONOPOLY_INFO_CHANGE = "MONOPOLY_INFO_CHANGE",
	ROLL_DICE = "ROLL_DICE",
}

export enum SwitchEvent {
	SWITCH = "SWITCH",
	SWITCH_MAP_SHOP = "SWITCH_MAP_SHOP",
	SWITCH_GEMMAZE = "SWITCH_GEMMAZE",
	COMPREHENSIVE_ENTRANCE = "COMPREHENSIVE_ENTRANCE",
	COMPREHENSIVE_WEBSITE = "COMPREHENSIVE_WEBSITE",
	COMPREHENSIVE_OFFICIAL_ACCOUNTS = "COMPREHENSIVE_OFFICIAL_ACCOUNTS",
	COMPREHENSIVE_PUSH = "COMPREHENSIVE_PUSH",
	COMPREHENSIVE_CUSTOMER = "COMPREHENSIVE_CUSTOMER",
	MOUNT_SHARE = "MOUNT_SHARE",
	MICRO_APP = "MICRO_APP",
}

export enum DictionaryEvent {
	PREADD = "preaddDictionary",
	PREUPDATE = "preupdateDictionary",
	PREDELETE = "predeleteDictionary",
	PRECLEAR = "preclearDictionary",
	ADD = "addDictionary",
	UPDATE = "updateDictionary",
	DELETE = "deleteDictionary",
	CLEAR = "clearDictionary",
}
export enum RewardEvent {
	/**
	 *悬赏任务添加
	 */
	REWARD_TASK_ADD = "REWARD_TASK_ADD",
	/**
	 *悬赏任务选中
	 */
	REWARD_TASK_SELECTED = "REWARD_TASK_SELECTED",
	/**
	 *悬赏任务更新
	 */
	REWARD_TASK_UPDATE = "REWARD_TASK_UPDATE",
	/**
	 *悬赏任务完成
	 */
	REWARD_TASK_FINISH = "REWARD_TASK_FINISH",
	/**
	 *悬赏任务列表刷新
	 */
	OFFER_REWARD_LIST_REFRESH = "OFFER_REWARD_LIST_REFRESH",
	/**
	 * 悬赏数据重置（每日5点重置）
	 */
	NEED_RESET_DATA = "NEED_RESET_DATA",
}
export enum RingTaskEvent {
	REFRESHRING = "REFRESHTING",
	ADDRINGTASK = "ADDRINGTASK",
	COMPLETETASK = "COMPLETETASK",
}
/**邮件 */
export enum EmailEvent {
	DATA_EMAIL_DELETE = "DATA_EMAIL_DELETE",
	DATA_EMAIL_UPDATE = "DATA_EMAIL_UPDATE",
	DATA_EMAIL_NEW = "DATA_EMAIL_NEW",
	ADD_FRIEND_CELL_CHECK = "ADD_FRIEND_CELL_CHECK",
	STATE_UPDATE = "MailCheckEvent.STATE_UPDATE",
	UPDATE_EMAIL_STATUS = "UPDATE_EMAIL_STATUS",
	UPDATE_ALL_EMAIL_STATUS = "UPDATE_ALL_EMAIL_STATUS",
	// 福利  邮箱、手机绑定状态
	WELFARE_BIND_STATE = "WELFARE_BIND_STATE",
}

export enum TaskSelectEvent {
	ITEM_SELECTED = "task_item_selected",
}

export enum FashionEvent {
	FASHION_STORE_CHANGE = "FASHION_STORE_CHANGE",
	BUY_ITEM_SELECTED = "BUY_ITEM_SELECTED",
	COMPOSE_SUCCEED = "COMPOSE_SUCCEED",
	SWITCH_EQUIPVIEW = "SWITCH_EQUIPVIEW",
	REFRESH_BAG = "REFRESH_BAG",
	RESET_MOVIECLIP = "RESET_MOVIECLIP",
	FASHION_BOOK_WEAR = "FASHION_BOOK_WEAR",
	FASHION_BOOK_RECEIVE = "FASHION_BOOK_RECEIVE",
	CHANGE_SWITCH = "CHANGE_SWITCH",
	SWITCH_FASION = "SWITCH_FASION",
	SHOW_FASHION_TAB = "SHOW_FASHION_TAB",
	SWALLOW = "SWALLOW",
}
export enum TechnologyItemEvent {
	ITEM_CLICK = "ITEM_CLICK",
	CREATE = "CREATE",
	UPDATA = "UPDATA",
	TECHNOLOGY_ITEM_ROLL_OVER = "technology_item_roll_over",
	TECHNOLOGY_ITEM_ROLL_OUT = "technology_item_roll_out",
}
export enum TipsEvent {
	EQUIP_TIPS_HIDE = "EQUIP_TIPS_HIDE",
	EQUIP_TIPS_OBTAIN = "EQUIP_TIPS_OBTAIN",
}
export enum TreasureMapEvent {
	TREASURE_INFO_UPDATE = "TREASURE_INFO_UPDATE",
}
export enum InteractiveEvent {
	STATE_CHANGED = "stateChange",
	CLICK = "interactive_click",
	DOUBLE_CLICK = "interactive_double_click",
	LONG_PRESS = "interactive_long_press",
	LONG_PRESS_END = "interactive_long_press_end",
}
export enum MountsEvent {
	MOUNT_INFO_CHANGE = "mountInfoChange",
	MOUNT_LIST_CHANGE = "mountListChange",
	PAGE_INDEX_CHANGE = "pageIndexChange",
	MOUNT_LEVEL_UP = "mountLevelup",
	PROP_LEVEL_UP = "propLevelup",
	MOUNT_STAR_UP = "mountStarUp",
}
export enum NativeEvent {
    STATUS_BAR_CHANGE = "STATUS_BAR_CHANGE",
    AFTER_STATUS_BAR_CHANGE = "AFTER_STATUS_BAR_CHANGE",
    PERMISSION_UPDATE = "PERMISSION_UPDATE",
    MOUNT_SHARE_RESULT = "MOUNT_SHARE_RESULT",
    WIFI_STATE_UPDATE = "WIFI_STATE_UPDATE",
    GAME_ENTER_OVER = "GAME_ENTER_OVER",
    BIND_ACCOUNT_RET = "BIND_ACCOUNT_RET",
    CHECK_BIND_ACCOUNT = "CHECK_BIND_ACCOUNT",
    SDK_INIT = "SDK_INIT",
    ERROR_CODE = "ERROR_CODE",
}

export enum AnswerEvent {
	/** 更新排行榜信息*/
	UPDATE_RANK = "UPDATE_RANK",
	/** 更新答题数据*/
	UPDATE_ANSWER = "UPDATE_ANSWER",
	/** 更新状态*/
	UPDATE_STATE = "UPDATE_STATE",
	/** 更新道具*/
	UPDATE_ITEM = "UPDATE_ITEM",
	/** 答题结果*/
	UPDATE_RESULT = "UPDATE_RESULT",
	/** 更新自己的排行信息*/
	UPDATE_SELF_RANK = "UPDATE_SELF_RANK",
	/** 显示奖励*/
	SHOW_REWARDS = "SHOW_REWARDS",
	/** 选择道具*/
	SELECT_ITEM = "SELECT_ITEM",
	/** 选择答案*/
	SELECT_ANSWER = "SELECT_ANSWER",
}

/**武斗会事件类  */
export enum WarlordsEvent {
	/**
	 *武斗会信息更新
	 */
	INFO_UPDATE = "INFO_UPDATE",
	/**
	 *当前下注选择改变
	 */
	CUR_BETTING_CHANGE = "CUR_BETTING_CHANGE",
	/**
	 *奖励领取状态改变
	 */
	REWARD_STATE_CHANGE = "REWARD_STATE_CHANGE",
	/**
	 *上届获奖列表更新
	 */
	LAST_AWARDLIST_UPDATE = "LAST_AWARDLIST_UPDATE",
	/**
	 *进入决赛玩家列表更新
	 */
	ACCESS_FINALLIST_UPDATE = "ACCESS_FINALLIST_UPDATE",
	/**
	 *各职业第一avatar更新
	 */
	TOP_AVATAR_CHANGE = "TOP_AVATAR_CHANGE",
	/**
	 * 登录的时候 时间已经发送完成
	 */
	DATE_INIT_COMPLETE = "DATE_INIT_COMPLETE",
}

/**武斗会事件类  */
export enum MultilordsEvent {
	/**
	 *武斗会信息更新
	 */
	INFO_UPDATE = "INFO_UPDATE",
	/**
	 *当前下注选择改变
	 */
	CUR_BETTING_CHANGE = "CUR_BETTING_CHANGE",
	/**
	 *奖励领取状态改变
	 */
	REWARD_STATE_CHANGE = "REWARD_STATE_CHANGE",
	/**
	 *上届获奖列表更新
	 */
	LAST_AWARDLIST_UPDATE = "LAST_AWARDLIST_UPDATE",
	/**
	 *进入决赛玩家列表更新
	 */
	ACCESS_FINALLIST_UPDATE = "ACCESS_FINALLIST_UPDATE",
	/**
	 *各职业第一avatar更新
	 */
	TOP_AVATAR_CHANGE = "TOP_AVATAR_CHANGE",
}

/**战场事件类  */
export enum PvpWarFightEvent {
	PVP_WAR_FIGHT_INFO_CHAGE = "PVP_WAR_FIGHT_INFO_CHAGE",
	PVP_WAR_FIGHT_REPORT = "PVP_WAR_FIGHT_REPORT",
	PVP_WAR_FIGHT_ORDER_REPORT = "PVP_WAR_FIGHT_ORDER_REPORT",
}

export enum WebViewEvent {
	RECEIVE_DATA = "receive_data",
	RECEIVE_WEBVIEW_INFO = "RECEIVE_WEBVIEW_INFO",
	RECEIVE_PHOTO_CALL = "RECEIVE_PHOTO_CALL",
}

export enum WanViewEvent {
	RECEIVE_DATA = "receive_data",
}

export enum PhysicsMenuEvent {
	BTN_ATTACK = "BTN_ATTACK",
	BTN_MOVE = "BTN_MOVE",
	BTN_INFO = "BTN_INFO",
	BTN_ENTER = "BTN_ENTER",
	BTN_RETURN = "BTN_RETURN",
	BTN_CALL = "BTN_CALL",
	BTN_PORTAL = "BTN_PORTAL",
	BTN_GIVE_UP = "BTN_GIVE_UP",
	WRITE_EMAIL = "WRITE_EMAIL",
	FRIEND = "FRIEND",
}

export enum ExpBackEvent {
	/** 请求数据*/
	REQUEST_DATA = "requestData",
	/** 更新全部信息*/
	UPDATE_INFO = "updateInfo",
	/** 更新单个信息*/
	UPDATE_ITEM_INFO = "updateItemInfo",
	/** 找回*/
	EXP_BACK = "expback",
	/** 翻页*/
	PAGE_CHANGE = "pagChange",
	/** 显示找回面板*/
	SHOW_BACK_FRAME = "showbackframe",

	UPDATE_EXPBACK_STATUS = "UPDATE_EXPBACK_STATUS",
}

export enum HookEvent {
	UPDATE_HOOK = "UPDATE_HOOK", //更新修行神殿信息
}

export enum CustomerServiceEvent {
	UPLOAD_SUCCESS = "UPLOAD_SUCCESS",
}

export enum RoomHallEvent {
	CHANGE_CAMPAIGN = "CHANGE_CAMPAIGN",
}

export enum FeedBackEvent {
	/**
	 * 点击礼包Item
	 * */
	FEEDBACK_ITEM_CLICK = "FEEDBACK_ITEM_CLICK",
	/**
	 * 收到用户的数据
	 * */
	FEEDBACK_RECEIVE_USERINFO = "FEEDBACK_RECEIVE_USERINFO",
	/**
	 * 删除回馈活动
	 * */
	FEEDBACK_DELETE_ACTIVE = "FEEDBACK_DELETE_ACTIVE",
}

export enum ShadowUIEvent {
	// 位置变化时
	SHADOW_POSX = "SHADOW_POSX",
	SHADOW_POSY = "SHADOW_POSY",
	//
	CREATE_SHADOW = "CREATE_SHADOW",
	DISPOSE_SHADOW = "DISPOSE_SHADOW",

	SHADOW_VISIBLE = "SHADOW_VISIBLE",
	SHADOW_ALPHA = "SHADOW_ALPHA",
}

export enum AvatarInfoUIEvent {
	// 昵称位置变化时
	CON_POSX = "CON_POSX",
	CON_POSY = "CON_POSY",
	CON_CREATE = "CON_CREATE",
	CON_DISPOSE = "CON_DISPOSE",
	CON_VISIBLE = "CON_VISIBLE",
	CON_ALPHA = "CON_ALPHA",

	NAME_TEXT = "NAME_TEXT",
	NAME_FRAME = "NAME_FRAME",
	CONSORTIA_TEXT = "CONSORTIA_TEXT",
	CONSORTIA_FRAME = "CONSORTIA_FRAME",
	PET_TAIL_SCALE = "PET_TAIL_SCALE",

	PET_STAR_NUM = "PET_STAR_NUM",
}

export enum OuterCityShopEvent {
	PAYTYPE_CHANGE = "PAYTYPE_CHANGE",
	FRESH_VIEW = "FRESH_VIEW",
	EXCHANGE_GOODS_LIST_UPDATE = "EXCHANGE_GOODS_LIST_UPDATE",
	LOOK_GOODS_LIST_UPDATE = "LOOK_GOODS_LIST_UPDATE",
	UPDATE_LUCK_SHOW_INFO = "UPDATE_LUCK_SHOW_INFO",
}

export enum GemMazeEvent {
	//获取初始信息返回
	GEMMAZE_GET_INIT_INFO = "GEMMAZE_GET_INIT_INFO",
	// 每回合更新数据
	GEMMAZE_UPDATE_INFO = "GEMMAZE_UPDATE_INFO",
	//更新剩余次数
	GEMMAZE_UPDATE_TIMESLEFT = "GEMMAZE_UPDATE_TIMESLEFT",
	//消除动画播放完毕
	GEMMAZE_REMOVE_COMPLETE = "GEMMAZE_REMOVE_COMPLETE",
	//移动宝石完毕
	GEMMAZE_GEM_ACTION_COMPLETE = "GEMMAZE_GEM_ACTION_COMPLETE",
	//更新frmae
	GEMMAZE_GEM_UPDATE_FRAME = "GEMMAZE_GEM_UPDATE_FRAME",
	//加载排行榜
	ORDERDATA_LOAD_COMPLETE = "ORDERDATA_LOAD_COMPLETE",
	//播放消除宝石物品飞落动画
	GEMMAZE_GEM_PLAYER_GOODS_FLY = "GEMMAZE_GEM_PLAYER_GOODS_FLY",
	//更新积分宝箱状态
	GEMMAZE_UPDATE_BOX_STATUS = "GEMMAZE_UPDATE_BOX_STATUS",
	//更新藏宝箱物品
	GEMMAZE_UPDATE_BAG = "GEMMAZE_UPDATE_BAG",
	//播放粒子动画
	GEMMAZE_PLAYER_GRAIN = "GEMMAZE_PLAYER_GRAIN",
	//播放领取积分宝箱奖励动画
	GEMMAZE_PLAYER_BOX_GOODS = "GEMMAZE_PLAYER_BOX_GOODS",
	//播放添加积分文字
	GEMMAZE_ADD_INTERGAL = "GEMMAZE_ADD_INTERGAL",
}
/**
 * 通行证事件
 */
export enum PassCheckEvent {
	//收到奖励数据
	RECEIVE_PASS_REWARD = "RECEIVE_PASS_REWARD",
	//收到任务数据
	// RECEIVE_PASS_TASK = "RECEIVE_PASS_TASK",
	//任务刷新或领取
	PASS_TASK_FRESH = "PASS_TASK_FRESH",
	//活动关闭
	PASS_TIME_VOER = "PASS_TIME_VOER",
}

/**
 * 气泡
 */
export enum CharBubbleEvent {
	//收到奖励数据
	ALL_CHAT_BUBBLES = "ALL_CHAT_BUBBLES",
	//
	CHAT_BUBBLES_OPT = "CHAT_BUBBLES_OPT",
}

/**
 * 多选宝箱
 */
export enum MultiBoxSelectEvent {
	FOCUS = "FOCUS",
	BLUR = "BLUR",
}

/**
 * 采集
 */
export enum ClollectActionEvent {
	CANCEL_CLOLLECT = "CANCEL_CLOLLECT",
}

export enum SHARE_EVENT {
	HIGH_FRAME_CHANGE = "HIGH_FRAME_CHANGE",
}

export enum DISCOUNT_ITEM {
	DISCOUNT_ITEM_CHECK_STATE = "DISCOUNT_ITEM_CHECK_STATE",
}

export enum GoldenSheepEvent {
	INFO_UPDATE = "INFO_UPDATE",
	STATE_UPDATE = "STATE_UPDATE",
	ANIMATION_UPDATE = "ANIMATION_UPDATE",
}

export enum TurntableEvent {
	OPENSTATE = "OPENSTATE",
	SINGLEINFO_UPDATE = "SINGLEINFO_UPDATE",
	TURNTABLE_REWARD = "TURNTABLE_REWARD",
}
/**
 * 跳转到背包里面的模块的事件
 */
export enum BAG_EVENT {
	JEWEL = "JEWEL",
	// DRAGONSOUL = "DRAGONSOUL",
}

export enum QQ_HALL_EVENT {
	GARDE_CHANGE = "GARDE_CHANGE",
	TAB_CHANGE = "TAB_CHANGE",
	GIFT_CHANGE = "GIFT_CHANGE",
	GIFT_TAB_CHANGE = "GIFT_TAB_CHANGE",
}

export enum BottleEvent {
	UPDATE_REWARDS_INFO = "UPDATE_REWARDS_INFO",
	UPDATE_LUCK_SHOW_INFO = "UPDATE_LUCK_SHOW_INFO",
	CT__UPDATE_BOX_STATUS = "CT__UPDATE_BOX_STATUS",
	UPDATE_REWARD_USERINFO = "UPDATE_REWARD_USERINFO",
	UPDATE_LAYER_SHOW_INFO = "UPDATE_LAYER_SHOW_INFO",
}
export enum FunOpenEvent {
	UPDATE_FUNOPEN_STATE = "UPDATE_FUNOPEN_STATE",
}

export default class NewbieEvent {
	public static MANUAL_TRIGGER: string = "MANUAL_TRIGGER";
	public static MAIN_NODE_FINISH: string = "MAIN_NODE_FINISH";
	public static ARROW_STATE: string = "ARROW_STATE";
}

export enum OuterCityWarEvent {
	/** 城堡信息 */
	CASTLE_INFO = "OUTERCITYWAR_CASTLE_INFO",
	BUILD_INFO = "OUTERCITYWAR_BUILD_INFO",
	ALL_BUILD_INFO = "OUTERCITYWAR_ALL_BUILD_INFO",

	/** 建筑前置完全占领状态 */
	BUILD_PRE_COMPLETE_OCCUPY_STATE = "BUILD_PRE_COMPLETE_OCCUPY_STATE",
	/** 玩家、npc信息 */
	PLAYER_INFO = "OUTERCITYWAR_PLAYER_INFO",
	/** 行动点 */
	ACTION_POINT = "OUTERCITYWAR_ACTION_POINT",
	/** 公会通知 */
	GUILD_NOTICE = "OUTERCITYWAR_GUILD_NOTICE",
	/** 守军怪物积分 */
	DEFENCE_NPC_SCORE = "OUTERCITYWAR_DEFENCE_NPC_SCORE",
}

export enum SecretEvent {
	//秘境信息
	SECRET_INFO = "SECRET_INFO",
	//未通关秘境记录信息
	SECRET_RECORD_INFO = "SECRET_RECORD_INFO",
	//失去秘宝
	LOSE_TRESURE = "LOSE_TRESURE",
	//获得秘宝
	GAIN_TRESURE = "GAIN_TRESURE",
	//更新秘宝
	UPDATE_TRESURE = "UPDATE_TRESURE",
	//战败
	FAILED = "FAILED",
	//复活
	REVIVE = "REVIVE",
	//添加怪物
	ADD_NPC = "ADD_NPC",
	//移除怪物
	REMOVE_NPC = "REMOVE_NPC",
}
