// @ts-nocheck
export default class TemplateIDConstant {
    public static TEMP_ID_POWER: number = -5700;//体力
    public static TEMP_ID_DIAMOND: number = -400;//钻石
    public static TEMP_ID_GIFT: number = -500;//绑定钻石
    public static TEMP_ID_GOLD: number = -100;//黄金
    public static TEMP_ID_EXP: number = -700;//经验
    public static TEMP_ID_RYSJ: number = -800;//荣耀水晶
    public static TEMP_ID_TITAN: number = -1300;//泰坦结晶
    public static TEMP_ID_MYSTERY_SHOP_SCORE: number = -6000;//神秘商店积分
    public static TEMP_ID_VIP_EXP: number = -5500;//VIP经验
    public static TEMP_ID_CARNIVAL_POINT: number = -5600;//嘉年华积分
    public static TEMP_ID_CONSORTIA: number = -1400;//恐惧之牙
    public static TEMP_ID_CONSORTIA_CONTRIBUTE: number = -5800;//公会贡献
    public static TEMP_ID_CONSORTIA_CAIFU: number = -5900;//公会财富
    public static GUILD_GOODS: number = -6100;//公会高级财富（公会物资）
    public static GUILD_CONTRIBUTION: number = -6200;//公会高级贡献（公会个人建设值）
    public static GUILD_TASK_SCORE: number = -6300;//公会积分
    public static TEMP_ID_PET_JINHUN: number = -910;//英灵晶魂
    public static TEMP_ID_PET_ZIJIN: number = -200;//紫晶积分
    public static TEMP_ID_FUSHI_SUIPIAN: number = -1000;//符石碎片
    public static TEMP_ID_SHUIJIN: number = -600;//水晶
    public static TEMP_ID_ZHANHUN: number = -300;//战魂

    public static TEMP_ID_XUNZHANG: number = 208001;//勋章
    public static TEMP_ID_WENZHANG: number = 2131020;//修行纹章
    public static TEMP_ID_MAZE: number = 208009;//迷宫硬币
    public static TEMP_ID_JINGHUA_SHUI: number = 3101021;//水之精华
    public static TEMP_ID_JINGHUA_DIAN: number = 3101031;//电之精华
    public static TEMP_ID_JINGHUA_HUO: number = 3101011;//火之精华
    public static TEMP_ID_JINGHUA_FENG: number = 3101041;//风之精华
    public static TEMP_ID_JINGHUA_AN: number = 3101051;//暗之精华
    public static TEMP_ID_JINGHUA_GUANG: number = 3101061;//光之精华
    public static TEMP_ID_STONE: number = 208024;//命运石
    public static TEMP_ID_SHUJING: number = 208014;//灵魂水晶
    public static TEMP_ID_DRAGONCRYID: number = 208052;//龙晶
    public static TEMP_ID_DRAGONCRYID2: number = 208053;//高级龙晶
    public static TEMP_ID_PET_GROWTH_STONE: number = 208023;//宠物成长石
    public static TEMP_ID_PET_COE_STONE: number = 3040001;//宠物资质丹
    public static TEMP_ID_GOLD_ZUAN: number = 208004;//金刚钻
    public static TEMP_ID_FUKONG: number = 4010001;//符孔钻
    public static TEMP_ID_FUWEN_STONE: number = 3020010;//符文石
    public static TEMP_ID_XILIAN_SUO: number = 208027;//洗炼锁
    public static TEMP_ID_MYSTERY_STONE: number = 2131057;//神秘石
    public static TEMP_ID_STONE_ENERGY: number = 4020002;//符石能量
    public static TEMP_ID_WISHPOOL: number = 208056;//许愿券
    public static TEMP_ID_WISHPOOL_GOLD: number = 208057;//金色许愿券
    public static TEMP_ID_CUP: number = 208055;//圣杯
    public static TEMP_ID_CRUSADE: number = 208058;//古战场讨伐令
    public static TEMP_ID_ENERG_STNE: number = 2131056;//能量之石
    public static TEMP_ID_PET_SKILL_SCROLL: number = 208061;//英灵技能卷轴
    public static TEMP_ID_MOUNT_FOOD: number = 208017;//兽魂石
    public static TEMP_ID_SECRETBOOK: number = 208072;//初级秘典残页
    public static TEMP_ID_SECRETBOOK_M: number = 208080;//中级秘典残页
    public static TEMP_ID_SECRETBOOK_H: number = 208081;//高级秘典残页
    static TEMP_ID_MASTERY_STONE_P : number = 208076 // 初级锻魂石
    static TEMP_ID_MASTERY_STONE_M : number = 208077
    static TEMP_ID_MASTERY_STONE_H : number = 208078
    static TEMP_ID_MASTERY_PIECES_P : number = 208073 // 初级魂器碎片
    static TEMP_ID_MASTERY_PIECES_M : number = 208074
    static TEMP_ID_MASTERY_PIECES_H : number = 208075

}