/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import FUI_AirGardenGameLLKItem from "./FUI_AirGardenGameLLKItem";

export default class FUI_AirGardenGameLLKGroup extends fgui.GComponent {

	public l09:FUI_AirGardenGameLLKItem;
	public l08:FUI_AirGardenGameLLKItem;
	public l07:FUI_AirGardenGameLLKItem;
	public l06:FUI_AirGardenGameLLKItem;
	public l05:FUI_AirGardenGameLLKItem;
	public l04:FUI_AirGardenGameLLKItem;
	public l03:FUI_AirGardenGameLLKItem;
	public l02:FUI_AirGardenGameLLKItem;
	public l01:FUI_AirGardenGameLLKItem;
	public l00:FUI_AirGardenGameLLKItem;
	public l19:FUI_AirGardenGameLLKItem;
	public l18:FUI_AirGardenGameLLKItem;
	public l17:FUI_AirGardenGameLLKItem;
	public l16:FUI_AirGardenGameLLKItem;
	public l15:FUI_AirGardenGameLLKItem;
	public l14:FUI_AirGardenGameLLKItem;
	public l13:FUI_AirGardenGameLLKItem;
	public l12:FUI_AirGardenGameLLKItem;
	public l11:FUI_AirGardenGameLLKItem;
	public l10:FUI_AirGardenGameLLKItem;
	public l29:FUI_AirGardenGameLLKItem;
	public l28:FUI_AirGardenGameLLKItem;
	public l27:FUI_AirGardenGameLLKItem;
	public l26:FUI_AirGardenGameLLKItem;
	public l25:FUI_AirGardenGameLLKItem;
	public l24:FUI_AirGardenGameLLKItem;
	public l23:FUI_AirGardenGameLLKItem;
	public l22:FUI_AirGardenGameLLKItem;
	public l21:FUI_AirGardenGameLLKItem;
	public l20:FUI_AirGardenGameLLKItem;
	public l39:FUI_AirGardenGameLLKItem;
	public l38:FUI_AirGardenGameLLKItem;
	public l37:FUI_AirGardenGameLLKItem;
	public l36:FUI_AirGardenGameLLKItem;
	public l35:FUI_AirGardenGameLLKItem;
	public l34:FUI_AirGardenGameLLKItem;
	public l33:FUI_AirGardenGameLLKItem;
	public l32:FUI_AirGardenGameLLKItem;
	public l31:FUI_AirGardenGameLLKItem;
	public l30:FUI_AirGardenGameLLKItem;
	public l49:FUI_AirGardenGameLLKItem;
	public l48:FUI_AirGardenGameLLKItem;
	public l47:FUI_AirGardenGameLLKItem;
	public l46:FUI_AirGardenGameLLKItem;
	public l45:FUI_AirGardenGameLLKItem;
	public l44:FUI_AirGardenGameLLKItem;
	public l43:FUI_AirGardenGameLLKItem;
	public l42:FUI_AirGardenGameLLKItem;
	public l41:FUI_AirGardenGameLLKItem;
	public l40:FUI_AirGardenGameLLKItem;
	public l59:FUI_AirGardenGameLLKItem;
	public l58:FUI_AirGardenGameLLKItem;
	public l57:FUI_AirGardenGameLLKItem;
	public l56:FUI_AirGardenGameLLKItem;
	public l55:FUI_AirGardenGameLLKItem;
	public l54:FUI_AirGardenGameLLKItem;
	public l53:FUI_AirGardenGameLLKItem;
	public l52:FUI_AirGardenGameLLKItem;
	public l51:FUI_AirGardenGameLLKItem;
	public l50:FUI_AirGardenGameLLKItem;
	public l69:FUI_AirGardenGameLLKItem;
	public l68:FUI_AirGardenGameLLKItem;
	public l67:FUI_AirGardenGameLLKItem;
	public l66:FUI_AirGardenGameLLKItem;
	public l65:FUI_AirGardenGameLLKItem;
	public l64:FUI_AirGardenGameLLKItem;
	public l63:FUI_AirGardenGameLLKItem;
	public l62:FUI_AirGardenGameLLKItem;
	public l61:FUI_AirGardenGameLLKItem;
	public l60:FUI_AirGardenGameLLKItem;
	public static URL:string = "ui://qvbm8hnzav7smifa";

	public static createInstance():FUI_AirGardenGameLLKGroup {
		return <FUI_AirGardenGameLLKGroup>(fgui.UIPackage.createObject("Carnival", "AirGardenGameLLKGroup"));
	}

	protected onConstruct():void {
		this.l09 = <FUI_AirGardenGameLLKItem>(this.getChild("l09"));
		this.l08 = <FUI_AirGardenGameLLKItem>(this.getChild("l08"));
		this.l07 = <FUI_AirGardenGameLLKItem>(this.getChild("l07"));
		this.l06 = <FUI_AirGardenGameLLKItem>(this.getChild("l06"));
		this.l05 = <FUI_AirGardenGameLLKItem>(this.getChild("l05"));
		this.l04 = <FUI_AirGardenGameLLKItem>(this.getChild("l04"));
		this.l03 = <FUI_AirGardenGameLLKItem>(this.getChild("l03"));
		this.l02 = <FUI_AirGardenGameLLKItem>(this.getChild("l02"));
		this.l01 = <FUI_AirGardenGameLLKItem>(this.getChild("l01"));
		this.l00 = <FUI_AirGardenGameLLKItem>(this.getChild("l00"));
		this.l19 = <FUI_AirGardenGameLLKItem>(this.getChild("l19"));
		this.l18 = <FUI_AirGardenGameLLKItem>(this.getChild("l18"));
		this.l17 = <FUI_AirGardenGameLLKItem>(this.getChild("l17"));
		this.l16 = <FUI_AirGardenGameLLKItem>(this.getChild("l16"));
		this.l15 = <FUI_AirGardenGameLLKItem>(this.getChild("l15"));
		this.l14 = <FUI_AirGardenGameLLKItem>(this.getChild("l14"));
		this.l13 = <FUI_AirGardenGameLLKItem>(this.getChild("l13"));
		this.l12 = <FUI_AirGardenGameLLKItem>(this.getChild("l12"));
		this.l11 = <FUI_AirGardenGameLLKItem>(this.getChild("l11"));
		this.l10 = <FUI_AirGardenGameLLKItem>(this.getChild("l10"));
		this.l29 = <FUI_AirGardenGameLLKItem>(this.getChild("l29"));
		this.l28 = <FUI_AirGardenGameLLKItem>(this.getChild("l28"));
		this.l27 = <FUI_AirGardenGameLLKItem>(this.getChild("l27"));
		this.l26 = <FUI_AirGardenGameLLKItem>(this.getChild("l26"));
		this.l25 = <FUI_AirGardenGameLLKItem>(this.getChild("l25"));
		this.l24 = <FUI_AirGardenGameLLKItem>(this.getChild("l24"));
		this.l23 = <FUI_AirGardenGameLLKItem>(this.getChild("l23"));
		this.l22 = <FUI_AirGardenGameLLKItem>(this.getChild("l22"));
		this.l21 = <FUI_AirGardenGameLLKItem>(this.getChild("l21"));
		this.l20 = <FUI_AirGardenGameLLKItem>(this.getChild("l20"));
		this.l39 = <FUI_AirGardenGameLLKItem>(this.getChild("l39"));
		this.l38 = <FUI_AirGardenGameLLKItem>(this.getChild("l38"));
		this.l37 = <FUI_AirGardenGameLLKItem>(this.getChild("l37"));
		this.l36 = <FUI_AirGardenGameLLKItem>(this.getChild("l36"));
		this.l35 = <FUI_AirGardenGameLLKItem>(this.getChild("l35"));
		this.l34 = <FUI_AirGardenGameLLKItem>(this.getChild("l34"));
		this.l33 = <FUI_AirGardenGameLLKItem>(this.getChild("l33"));
		this.l32 = <FUI_AirGardenGameLLKItem>(this.getChild("l32"));
		this.l31 = <FUI_AirGardenGameLLKItem>(this.getChild("l31"));
		this.l30 = <FUI_AirGardenGameLLKItem>(this.getChild("l30"));
		this.l49 = <FUI_AirGardenGameLLKItem>(this.getChild("l49"));
		this.l48 = <FUI_AirGardenGameLLKItem>(this.getChild("l48"));
		this.l47 = <FUI_AirGardenGameLLKItem>(this.getChild("l47"));
		this.l46 = <FUI_AirGardenGameLLKItem>(this.getChild("l46"));
		this.l45 = <FUI_AirGardenGameLLKItem>(this.getChild("l45"));
		this.l44 = <FUI_AirGardenGameLLKItem>(this.getChild("l44"));
		this.l43 = <FUI_AirGardenGameLLKItem>(this.getChild("l43"));
		this.l42 = <FUI_AirGardenGameLLKItem>(this.getChild("l42"));
		this.l41 = <FUI_AirGardenGameLLKItem>(this.getChild("l41"));
		this.l40 = <FUI_AirGardenGameLLKItem>(this.getChild("l40"));
		this.l59 = <FUI_AirGardenGameLLKItem>(this.getChild("l59"));
		this.l58 = <FUI_AirGardenGameLLKItem>(this.getChild("l58"));
		this.l57 = <FUI_AirGardenGameLLKItem>(this.getChild("l57"));
		this.l56 = <FUI_AirGardenGameLLKItem>(this.getChild("l56"));
		this.l55 = <FUI_AirGardenGameLLKItem>(this.getChild("l55"));
		this.l54 = <FUI_AirGardenGameLLKItem>(this.getChild("l54"));
		this.l53 = <FUI_AirGardenGameLLKItem>(this.getChild("l53"));
		this.l52 = <FUI_AirGardenGameLLKItem>(this.getChild("l52"));
		this.l51 = <FUI_AirGardenGameLLKItem>(this.getChild("l51"));
		this.l50 = <FUI_AirGardenGameLLKItem>(this.getChild("l50"));
		this.l69 = <FUI_AirGardenGameLLKItem>(this.getChild("l69"));
		this.l68 = <FUI_AirGardenGameLLKItem>(this.getChild("l68"));
		this.l67 = <FUI_AirGardenGameLLKItem>(this.getChild("l67"));
		this.l66 = <FUI_AirGardenGameLLKItem>(this.getChild("l66"));
		this.l65 = <FUI_AirGardenGameLLKItem>(this.getChild("l65"));
		this.l64 = <FUI_AirGardenGameLLKItem>(this.getChild("l64"));
		this.l63 = <FUI_AirGardenGameLLKItem>(this.getChild("l63"));
		this.l62 = <FUI_AirGardenGameLLKItem>(this.getChild("l62"));
		this.l61 = <FUI_AirGardenGameLLKItem>(this.getChild("l61"));
		this.l60 = <FUI_AirGardenGameLLKItem>(this.getChild("l60"));
	}
}