// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: extrajob/ExtraJobItemMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.extrajob";

export interface ExtraJobItemMsg {
  jobType: number;
  jobLevel: number;
  skillScript: string;
}

function createBaseExtraJobItemMsg(): ExtraJobItemMsg {
  return { jobType: 0, jobLevel: 0, skillScript: "" };
}

export const ExtraJobItemMsg: MessageFns<ExtraJobItemMsg> = {
  encode(message: ExtraJobItemMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobType !== 0) {
      writer.uint32(8).int32(message.jobType);
    }
    if (message.jobLevel !== 0) {
      writer.uint32(16).int32(message.jobLevel);
    }
    if (message.skillScript !== "") {
      writer.uint32(26).string(message.skillScript);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExtraJobItemMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExtraJobItemMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.jobType = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.jobLevel = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.skillScript = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExtraJobItemMsg {
    return {
      jobType: isSet(object.jobType) ? globalThis.Number(object.jobType) : 0,
      jobLevel: isSet(object.jobLevel) ? globalThis.Number(object.jobLevel) : 0,
      skillScript: isSet(object.skillScript) ? globalThis.String(object.skillScript) : "",
    };
  },

  toJSON(message: ExtraJobItemMsg): unknown {
    const obj: any = {};
    if (message.jobType !== 0) {
      obj.jobType = Math.round(message.jobType);
    }
    if (message.jobLevel !== 0) {
      obj.jobLevel = Math.round(message.jobLevel);
    }
    if (message.skillScript !== "") {
      obj.skillScript = message.skillScript;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExtraJobItemMsg>, I>>(base?: I): ExtraJobItemMsg {
    return ExtraJobItemMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExtraJobItemMsg>, I>>(object: I): ExtraJobItemMsg {
    const message = createBaseExtraJobItemMsg();
    message.jobType = object.jobType ?? 0;
    message.jobLevel = object.jobLevel ?? 0;
    message.skillScript = object.skillScript ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
