// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: battle/ArmyResMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.battle";

export interface ArmyResMsg {
  loadRes: number[];
  reinforceCount: number;
  reinforceType: number;
}

function createBaseArmyResMsg(): ArmyResMsg {
  return { loadRes: [], reinforceCount: 0, reinforceType: 0 };
}

export const ArmyResMsg: MessageFns<ArmyResMsg> = {
  encode(message: ArmyResMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.loadRes) {
      writer.int32(v);
    }
    writer.join();
    if (message.reinforceCount !== 0) {
      writer.uint32(16).int32(message.reinforceCount);
    }
    if (message.reinforceType !== 0) {
      writer.uint32(24).int32(message.reinforceType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ArmyResMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArmyResMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.loadRes.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.loadRes.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.reinforceCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reinforceType = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ArmyResMsg {
    return {
      loadRes: globalThis.Array.isArray(object?.loadRes) ? object.loadRes.map((e: any) => globalThis.Number(e)) : [],
      reinforceCount: isSet(object.reinforceCount) ? globalThis.Number(object.reinforceCount) : 0,
      reinforceType: isSet(object.reinforceType) ? globalThis.Number(object.reinforceType) : 0,
    };
  },

  toJSON(message: ArmyResMsg): unknown {
    const obj: any = {};
    if (message.loadRes?.length) {
      obj.loadRes = message.loadRes.map((e) => Math.round(e));
    }
    if (message.reinforceCount !== 0) {
      obj.reinforceCount = Math.round(message.reinforceCount);
    }
    if (message.reinforceType !== 0) {
      obj.reinforceType = Math.round(message.reinforceType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ArmyResMsg>, I>>(base?: I): ArmyResMsg {
    return ArmyResMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ArmyResMsg>, I>>(object: I): ArmyResMsg {
    const message = createBaseArmyResMsg();
    message.loadRes = object.loadRes?.map((e) => e) || [];
    message.reinforceCount = object.reinforceCount ?? 0;
    message.reinforceType = object.reinforceType ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
