// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: battle/MultiLanParamMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.battle";

export interface MultiLanParamMsg {
  lan: number;
  param: string;
}

function createBaseMultiLanParamMsg(): MultiLanParamMsg {
  return { lan: 0, param: "" };
}

export const MultiLanParamMsg: MessageFns<MultiLanParamMsg> = {
  encode(message: MultiLanParamMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lan !== 0) {
      writer.uint32(8).int32(message.lan);
    }
    if (message.param !== "") {
      writer.uint32(18).string(message.param);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultiLanParamMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultiLanParamMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lan = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.param = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MultiLanParamMsg {
    return {
      lan: isSet(object.lan) ? globalThis.Number(object.lan) : 0,
      param: isSet(object.param) ? globalThis.String(object.param) : "",
    };
  },

  toJSON(message: MultiLanParamMsg): unknown {
    const obj: any = {};
    if (message.lan !== 0) {
      obj.lan = Math.round(message.lan);
    }
    if (message.param !== "") {
      obj.param = message.param;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MultiLanParamMsg>, I>>(base?: I): MultiLanParamMsg {
    return MultiLanParamMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MultiLanParamMsg>, I>>(object: I): MultiLanParamMsg {
    const message = createBaseMultiLanParamMsg();
    message.lan = object.lan ?? 0;
    message.param = object.param ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
