// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: room/RoomCreatedMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.room";

export interface RoomCreatedMsg {
  createdType: number;
  room: string;
  isCross: boolean;
  campignId: number;
}

function createBaseRoomCreatedMsg(): RoomCreatedMsg {
  return { createdType: 0, room: "", isCross: false, campignId: 0 };
}

export const RoomCreatedMsg: MessageFns<RoomCreatedMsg> = {
  encode(message: RoomCreatedMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.createdType !== 0) {
      writer.uint32(8).int32(message.createdType);
    }
    if (message.room !== "") {
      writer.uint32(18).string(message.room);
    }
    if (message.isCross !== false) {
      writer.uint32(24).bool(message.isCross);
    }
    if (message.campignId !== 0) {
      writer.uint32(32).int32(message.campignId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoomCreatedMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoomCreatedMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.createdType = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.room = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isCross = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.campignId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoomCreatedMsg {
    return {
      createdType: isSet(object.createdType) ? globalThis.Number(object.createdType) : 0,
      room: isSet(object.room) ? globalThis.String(object.room) : "",
      isCross: isSet(object.isCross) ? globalThis.Boolean(object.isCross) : false,
      campignId: isSet(object.campignId) ? globalThis.Number(object.campignId) : 0,
    };
  },

  toJSON(message: RoomCreatedMsg): unknown {
    const obj: any = {};
    if (message.createdType !== 0) {
      obj.createdType = Math.round(message.createdType);
    }
    if (message.room !== "") {
      obj.room = message.room;
    }
    if (message.isCross !== false) {
      obj.isCross = message.isCross;
    }
    if (message.campignId !== 0) {
      obj.campignId = Math.round(message.campignId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoomCreatedMsg>, I>>(base?: I): RoomCreatedMsg {
    return RoomCreatedMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoomCreatedMsg>, I>>(object: I): RoomCreatedMsg {
    const message = createBaseRoomCreatedMsg();
    message.createdType = object.createdType ?? 0;
    message.room = object.room ?? "";
    message.isCross = object.isCross ?? false;
    message.campignId = object.campignId ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
