// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: outcitywar/CastleMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.outcitywar";

export interface CastleMsg {
  nodeId: number;
  parentNodeId: number;
  state: number;
  leftTime: number;
  guildMsg: number[];
  isGiveUp: boolean;
}

function createBaseCastleMsg(): CastleMsg {
  return { nodeId: 0, parentNodeId: 0, state: 0, leftTime: 0, guildMsg: [], isGiveUp: false };
}

export const CastleMsg: MessageFns<CastleMsg> = {
  encode(message: CastleMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== 0) {
      writer.uint32(8).int32(message.nodeId);
    }
    if (message.parentNodeId !== 0) {
      writer.uint32(16).int32(message.parentNodeId);
    }
    if (message.state !== 0) {
      writer.uint32(24).int32(message.state);
    }
    if (message.leftTime !== 0) {
      writer.uint32(32).int32(message.leftTime);
    }
    writer.uint32(42).fork();
    for (const v of message.guildMsg) {
      writer.int32(v);
    }
    writer.join();
    if (message.isGiveUp !== false) {
      writer.uint32(48).bool(message.isGiveUp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CastleMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCastleMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.nodeId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.parentNodeId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.state = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.leftTime = reader.int32();
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.guildMsg.push(reader.int32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.guildMsg.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isGiveUp = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CastleMsg {
    return {
      nodeId: isSet(object.nodeId) ? globalThis.Number(object.nodeId) : 0,
      parentNodeId: isSet(object.parentNodeId) ? globalThis.Number(object.parentNodeId) : 0,
      state: isSet(object.state) ? globalThis.Number(object.state) : 0,
      leftTime: isSet(object.leftTime) ? globalThis.Number(object.leftTime) : 0,
      guildMsg: globalThis.Array.isArray(object?.guildMsg) ? object.guildMsg.map((e: any) => globalThis.Number(e)) : [],
      isGiveUp: isSet(object.isGiveUp) ? globalThis.Boolean(object.isGiveUp) : false,
    };
  },

  toJSON(message: CastleMsg): unknown {
    const obj: any = {};
    if (message.nodeId !== 0) {
      obj.nodeId = Math.round(message.nodeId);
    }
    if (message.parentNodeId !== 0) {
      obj.parentNodeId = Math.round(message.parentNodeId);
    }
    if (message.state !== 0) {
      obj.state = Math.round(message.state);
    }
    if (message.leftTime !== 0) {
      obj.leftTime = Math.round(message.leftTime);
    }
    if (message.guildMsg?.length) {
      obj.guildMsg = message.guildMsg.map((e) => Math.round(e));
    }
    if (message.isGiveUp !== false) {
      obj.isGiveUp = message.isGiveUp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CastleMsg>, I>>(base?: I): CastleMsg {
    return CastleMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CastleMsg>, I>>(object: I): CastleMsg {
    const message = createBaseCastleMsg();
    message.nodeId = object.nodeId ?? 0;
    message.parentNodeId = object.parentNodeId ?? 0;
    message.state = object.state ?? 0;
    message.leftTime = object.leftTime ?? 0;
    message.guildMsg = object.guildMsg?.map((e) => e) || [];
    message.isGiveUp = object.isGiveUp ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
