// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: army/BossArmyListMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.army";

export interface BossArmyListMsg {
  leftFightTime: number;
  bossName: string;
  level: number;
  bossTemplateId: number;
  fightPlayer: number[];
}

function createBaseBossArmyListMsg(): BossArmyListMsg {
  return { leftFightTime: 0, bossName: "", level: 0, bossTemplateId: 0, fightPlayer: [] };
}

export const BossArmyListMsg: MessageFns<BossArmyListMsg> = {
  encode(message: BossArmyListMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.leftFightTime !== 0) {
      writer.uint32(8).int32(message.leftFightTime);
    }
    if (message.bossName !== "") {
      writer.uint32(18).string(message.bossName);
    }
    if (message.level !== 0) {
      writer.uint32(24).int32(message.level);
    }
    if (message.bossTemplateId !== 0) {
      writer.uint32(32).int32(message.bossTemplateId);
    }
    writer.uint32(42).fork();
    for (const v of message.fightPlayer) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BossArmyListMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBossArmyListMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.leftFightTime = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bossName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.bossTemplateId = reader.int32();
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.fightPlayer.push(reader.int32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.fightPlayer.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BossArmyListMsg {
    return {
      leftFightTime: isSet(object.leftFightTime) ? globalThis.Number(object.leftFightTime) : 0,
      bossName: isSet(object.bossName) ? globalThis.String(object.bossName) : "",
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
      bossTemplateId: isSet(object.bossTemplateId) ? globalThis.Number(object.bossTemplateId) : 0,
      fightPlayer: globalThis.Array.isArray(object?.fightPlayer)
        ? object.fightPlayer.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: BossArmyListMsg): unknown {
    const obj: any = {};
    if (message.leftFightTime !== 0) {
      obj.leftFightTime = Math.round(message.leftFightTime);
    }
    if (message.bossName !== "") {
      obj.bossName = message.bossName;
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    if (message.bossTemplateId !== 0) {
      obj.bossTemplateId = Math.round(message.bossTemplateId);
    }
    if (message.fightPlayer?.length) {
      obj.fightPlayer = message.fightPlayer.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BossArmyListMsg>, I>>(base?: I): BossArmyListMsg {
    return BossArmyListMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BossArmyListMsg>, I>>(object: I): BossArmyListMsg {
    const message = createBaseBossArmyListMsg();
    message.leftFightTime = object.leftFightTime ?? 0;
    message.bossName = object.bossName ?? "";
    message.level = object.level ?? 0;
    message.bossTemplateId = object.bossTemplateId ?? 0;
    message.fightPlayer = object.fightPlayer?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
