// @ts-nocheck
export enum BuildingEvent
{ 
       U_C_GOLD_IMPOSERESULT = "U_C_GOLD_IMPOSERESULT",
       CASTLE_SCALE = "CASTLE_SCALE",
       BUILDING_LOAD_COMPLETE = "BUILDING_LOAD_COMPLETE",
       ADD_NEW_BUILD = "ADD_NEW_BUILD",
       BUILD_INFO_UPDATE = "BUILD_INFO_UPDATE",
    
       BUILDING_UPGRADE_RECEIVE = "BUILDING_UPGRADE_RECEIVE",
       CREATE_NEW_BUILDING = "CREATE_NEW_BUILDING",
       BUILDING_CREATE_RECEIVE = "BUILDING_CREATE_RECEIVE",
       CASTLE_MAP_SCALe_CHANGE = "CASTLE_MAP_SCALe_CHANGE",
       ADD_BUILDING_NAME = "ADD_BUILDING_NAME",
       CHANGE_BUILDING_NAME = "CHANGE_BUILDING_NAME",
       NEW_BUILDING_FOCUS = "NEW_BUILDING_FOCUS",
       BUILDING_NAME_SHOW_HIDE = "building_name_show_hide",
       BUILDING_SHOW_VIEW = "show_buildingView",
    
       TRANSFER_TIME_COOL = "TRANSFER_TIME_COOL",
       TRANSFER_POWER_SUCCESS = "TRANSFER_POWER_SUCCESS",
       U_UNOCCPWILDLAND = "U_UNOCCPWILDLAND",
    
       U_SECURITY_INFO_UPDATE = "U_SECURITY_INFO_UPDATE",
    
       UNAPPLY = "UNAPPLY",
   
}