// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: remotepet/PetSiteMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.remotepet";

export interface PetSiteMsg {
  site: string;
  petId: string;
  skills: string;
}

function createBasePetSiteMsg(): PetSiteMsg {
  return { site: "", petId: "", skills: "" };
}

export const PetSiteMsg: MessageFns<PetSiteMsg> = {
  encode(message: PetSiteMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.site !== "") {
      writer.uint32(10).string(message.site);
    }
    if (message.petId !== "") {
      writer.uint32(18).string(message.petId);
    }
    if (message.skills !== "") {
      writer.uint32(26).string(message.skills);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PetSiteMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePetSiteMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.site = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.petId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.skills = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PetSiteMsg {
    return {
      site: isSet(object.site) ? globalThis.String(object.site) : "",
      petId: isSet(object.petId) ? globalThis.String(object.petId) : "",
      skills: isSet(object.skills) ? globalThis.String(object.skills) : "",
    };
  },

  toJSON(message: PetSiteMsg): unknown {
    const obj: any = {};
    if (message.site !== "") {
      obj.site = message.site;
    }
    if (message.petId !== "") {
      obj.petId = message.petId;
    }
    if (message.skills !== "") {
      obj.skills = message.skills;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PetSiteMsg>, I>>(base?: I): PetSiteMsg {
    return PetSiteMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PetSiteMsg>, I>>(object: I): PetSiteMsg {
    const message = createBasePetSiteMsg();
    message.site = object.site ?? "";
    message.petId = object.petId ?? "";
    message.skills = object.skills ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
