// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: team/MemberFightPosListMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.team";

export interface MemberFightPosListMsg {
  isGet: boolean;
  memberPos: number[];
}

function createBaseMemberFightPosListMsg(): MemberFightPosListMsg {
  return { isGet: false, memberPos: [] };
}

export const MemberFightPosListMsg: MessageFns<MemberFightPosListMsg> = {
  encode(message: MemberFightPosListMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isGet !== false) {
      writer.uint32(8).bool(message.isGet);
    }
    writer.uint32(18).fork();
    for (const v of message.memberPos) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MemberFightPosListMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMemberFightPosListMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isGet = reader.bool();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.memberPos.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.memberPos.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MemberFightPosListMsg {
    return {
      isGet: isSet(object.isGet) ? globalThis.Boolean(object.isGet) : false,
      memberPos: globalThis.Array.isArray(object?.memberPos)
        ? object.memberPos.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: MemberFightPosListMsg): unknown {
    const obj: any = {};
    if (message.isGet !== false) {
      obj.isGet = message.isGet;
    }
    if (message.memberPos?.length) {
      obj.memberPos = message.memberPos.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MemberFightPosListMsg>, I>>(base?: I): MemberFightPosListMsg {
    return MemberFightPosListMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MemberFightPosListMsg>, I>>(object: I): MemberFightPosListMsg {
    const message = createBaseMemberFightPosListMsg();
    message.isGet = object.isGet ?? false;
    message.memberPos = object.memberPos?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
