// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: vehicle/PlayerVehicleProfileMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.vehicle";

export interface PlayerVehicleProfileMsg {
  exp: number;
  score: number;
  defaultVehicle: number;
}

function createBasePlayerVehicleProfileMsg(): PlayerVehicleProfileMsg {
  return { exp: 0, score: 0, defaultVehicle: 0 };
}

export const PlayerVehicleProfileMsg: MessageFns<PlayerVehicleProfileMsg> = {
  encode(message: PlayerVehicleProfileMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.exp !== 0) {
      writer.uint32(8).int32(message.exp);
    }
    if (message.score !== 0) {
      writer.uint32(16).int32(message.score);
    }
    if (message.defaultVehicle !== 0) {
      writer.uint32(24).int32(message.defaultVehicle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerVehicleProfileMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerVehicleProfileMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.exp = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.score = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.defaultVehicle = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerVehicleProfileMsg {
    return {
      exp: isSet(object.exp) ? globalThis.Number(object.exp) : 0,
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
      defaultVehicle: isSet(object.defaultVehicle) ? globalThis.Number(object.defaultVehicle) : 0,
    };
  },

  toJSON(message: PlayerVehicleProfileMsg): unknown {
    const obj: any = {};
    if (message.exp !== 0) {
      obj.exp = Math.round(message.exp);
    }
    if (message.score !== 0) {
      obj.score = Math.round(message.score);
    }
    if (message.defaultVehicle !== 0) {
      obj.defaultVehicle = Math.round(message.defaultVehicle);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerVehicleProfileMsg>, I>>(base?: I): PlayerVehicleProfileMsg {
    return PlayerVehicleProfileMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerVehicleProfileMsg>, I>>(object: I): PlayerVehicleProfileMsg {
    const message = createBasePlayerVehicleProfileMsg();
    message.exp = object.exp ?? 0;
    message.score = object.score ?? 0;
    message.defaultVehicle = object.defaultVehicle ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
