// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: guildcampaign/GuildJoinPlayerInfoMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.guildcampaign";

export interface GuildJoinPlayerInfoMsg {
  redConsortiaId: number;
  redCount: number;
  blueConsortiaId: number;
  blueCount: number;
  userIds: number[];
}

function createBaseGuildJoinPlayerInfoMsg(): GuildJoinPlayerInfoMsg {
  return { redConsortiaId: 0, redCount: 0, blueConsortiaId: 0, blueCount: 0, userIds: [] };
}

export const GuildJoinPlayerInfoMsg: MessageFns<GuildJoinPlayerInfoMsg> = {
  encode(message: GuildJoinPlayerInfoMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.redConsortiaId !== 0) {
      writer.uint32(8).int32(message.redConsortiaId);
    }
    if (message.redCount !== 0) {
      writer.uint32(16).int32(message.redCount);
    }
    if (message.blueConsortiaId !== 0) {
      writer.uint32(24).int32(message.blueConsortiaId);
    }
    if (message.blueCount !== 0) {
      writer.uint32(32).int32(message.blueCount);
    }
    writer.uint32(42).fork();
    for (const v of message.userIds) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GuildJoinPlayerInfoMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGuildJoinPlayerInfoMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.redConsortiaId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.redCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.blueConsortiaId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.blueCount = reader.int32();
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.userIds.push(reader.int32());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.userIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GuildJoinPlayerInfoMsg {
    return {
      redConsortiaId: isSet(object.redConsortiaId) ? globalThis.Number(object.redConsortiaId) : 0,
      redCount: isSet(object.redCount) ? globalThis.Number(object.redCount) : 0,
      blueConsortiaId: isSet(object.blueConsortiaId) ? globalThis.Number(object.blueConsortiaId) : 0,
      blueCount: isSet(object.blueCount) ? globalThis.Number(object.blueCount) : 0,
      userIds: globalThis.Array.isArray(object?.userIds) ? object.userIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: GuildJoinPlayerInfoMsg): unknown {
    const obj: any = {};
    if (message.redConsortiaId !== 0) {
      obj.redConsortiaId = Math.round(message.redConsortiaId);
    }
    if (message.redCount !== 0) {
      obj.redCount = Math.round(message.redCount);
    }
    if (message.blueConsortiaId !== 0) {
      obj.blueConsortiaId = Math.round(message.blueConsortiaId);
    }
    if (message.blueCount !== 0) {
      obj.blueCount = Math.round(message.blueCount);
    }
    if (message.userIds?.length) {
      obj.userIds = message.userIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GuildJoinPlayerInfoMsg>, I>>(base?: I): GuildJoinPlayerInfoMsg {
    return GuildJoinPlayerInfoMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GuildJoinPlayerInfoMsg>, I>>(object: I): GuildJoinPlayerInfoMsg {
    const message = createBaseGuildJoinPlayerInfoMsg();
    message.redConsortiaId = object.redConsortiaId ?? 0;
    message.redCount = object.redCount ?? 0;
    message.blueConsortiaId = object.blueConsortiaId ?? 0;
    message.blueCount = object.blueCount ?? 0;
    message.userIds = object.userIds?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
