// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: stackhead/StackHeadRequestMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.stackhead";

export interface StackHeadRequestMsg {
  op: number;
  pos: number;
  seniorGeneral: string;
  notice: string;
  param1: number;
}

function createBaseStackHeadRequestMsg(): StackHeadRequestMsg {
  return { op: 0, pos: 0, seniorGeneral: "", notice: "", param1: 0 };
}

export const StackHeadRequestMsg: MessageFns<StackHeadRequestMsg> = {
  encode(message: StackHeadRequestMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.op !== 0) {
      writer.uint32(8).int32(message.op);
    }
    if (message.pos !== 0) {
      writer.uint32(16).int32(message.pos);
    }
    if (message.seniorGeneral !== "") {
      writer.uint32(26).string(message.seniorGeneral);
    }
    if (message.notice !== "") {
      writer.uint32(34).string(message.notice);
    }
    if (message.param1 !== 0) {
      writer.uint32(40).int32(message.param1);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StackHeadRequestMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStackHeadRequestMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.op = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pos = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.seniorGeneral = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.notice = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.param1 = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StackHeadRequestMsg {
    return {
      op: isSet(object.op) ? globalThis.Number(object.op) : 0,
      pos: isSet(object.pos) ? globalThis.Number(object.pos) : 0,
      seniorGeneral: isSet(object.seniorGeneral) ? globalThis.String(object.seniorGeneral) : "",
      notice: isSet(object.notice) ? globalThis.String(object.notice) : "",
      param1: isSet(object.param1) ? globalThis.Number(object.param1) : 0,
    };
  },

  toJSON(message: StackHeadRequestMsg): unknown {
    const obj: any = {};
    if (message.op !== 0) {
      obj.op = Math.round(message.op);
    }
    if (message.pos !== 0) {
      obj.pos = Math.round(message.pos);
    }
    if (message.seniorGeneral !== "") {
      obj.seniorGeneral = message.seniorGeneral;
    }
    if (message.notice !== "") {
      obj.notice = message.notice;
    }
    if (message.param1 !== 0) {
      obj.param1 = Math.round(message.param1);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StackHeadRequestMsg>, I>>(base?: I): StackHeadRequestMsg {
    return StackHeadRequestMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StackHeadRequestMsg>, I>>(object: I): StackHeadRequestMsg {
    const message = createBaseStackHeadRequestMsg();
    message.op = object.op ?? 0;
    message.pos = object.pos ?? 0;
    message.seniorGeneral = object.seniorGeneral ?? "";
    message.notice = object.notice ?? "";
    message.param1 = object.param1 ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
