//卡洛营地

// tempId[2071]  炎魔之眼  monster001C     skillIds:[40013, 40014]
// tempId[2072]  魔化枪兵  monster001C     skillIds:[40201, 40202]
let TestBattleData_5_fyundi = {
  HeroMsg: {},

  SoldierMsg: {},
  //攻击指令
  AttackOrderMsg20000: {
    attackMillis: "2020-12-09 11:03:50",
    attackOrderSeq: 0,
    awake: 0,
    awakeAdd: 0,
    awakenSoldiers: [],
    battleId: "b029f02a-df83-4575-aeca-bc1dae6a4986",
    buffers: [
      {
        bufferId: 13,
        curTurn: 0,
        damage: [],
        execFrame: 0,
        exeWay: 3,
        hasBufferId: true,
        hasCurTurn: true,
        hasExecFrame: true,
        hasExeWay: true,
        hasMaxTurn: true,
        hasPressedNum: true,
        hasSeeType: true,
        hasSourceId: true,
        hasTargetId: true,
        hasTemplateId: true,
        maxTurn: 1,
        pressedNum: 1,
        seeType: 2,
        sourceId: 1,
        targetId: 1,
        templateId: 2004,
        unSkillIds: [],
      },
    ],
    cdTime: 0,
    damages: [
      {
        damageType: 6,
        damageValue: 1316893,
        dropInfos: [],
        extraData: 0,
        hasDamageType: true,
        hasDamageValue: true,
        hasExtraData: true,
        hasHasIcon: true,
        hasHpLimit: true,
        hasIcon: false,
        hasIsHarmful: false,
        hasLeftValue: true,
        hasLivingId: true,
        hasOrder: true,
        hasParry: true,
        hasResistType: true,
        hasResistValue: true,
        hpLimit: 0,
        isHarmful: false,
        leftValue: 0,
        livingId: 2,
        order: 0,
        parry: false,
        resistType: 0,
        resistValue: 0,
      },
    ],
    execFrame: 98,
    frame: 98,
    frameNum: 36,
    hasAttackMillis: true,
    hasAttackOrderSeq: false,
    hasAwake: true,
    hasAwakeAdd: false,
    hasBattleId: true,
    hasCdTime: false,
    hasExecFrame: true,
    hasFrame: true,
    hasFrameNum: true,
    hasIsPassive: true,
    hasLivingId: true,
    hasOrderId: true,
    hasSp: true,
    hasSpAdded: true,
    isPassive: false,
    livingId: 11,
    orderId: 20000,
    sp: 100,
    spAdded: 0,
  },
  AttackOrderMsg20851: {
    attackMillis: "2020-12-09 11:03:50",
    attackOrderSeq: 0,
    awake: 0,
    awakeAdd: 0,
    awakenSoldiers: [],
    battleId: "b029f02a-df83-4575-aeca-bc1dae6a4986",
    buffers: [
      {
        bufferId: 13,
        curTurn: 0,
        damage: [],
        execFrame: 0,
        exeWay: 3,
        hasBufferId: true,
        hasCurTurn: true,
        hasExecFrame: true,
        hasExeWay: true,
        hasMaxTurn: true,
        hasPressedNum: true,
        hasSeeType: true,
        hasSourceId: true,
        hasTargetId: true,
        hasTemplateId: true,
        maxTurn: 1,
        pressedNum: 1,
        seeType: 2,
        sourceId: 1,
        targetId: 1,
        templateId: 2004,
        unSkillIds: [],
      },
    ],
    cdTime: 0,
    damages: [
      {
        damageType: 6,
        damageValue: 1141757,
        dropInfos: [],
        extraData: 1, //1暴击 0不暴击
        hasDamageType: true,
        hasDamageValue: true,
        hasExtraData: true,
        hasHasIcon: true,
        hasHpLimit: true,
        hasIcon: false,
        hasIsHarmful: false,
        hasLeftValue: true,
        hasLivingId: true,
        hasOrder: true,
        hasParry: true,
        hasResistType: true,
        hasResistValue: true,
        hpLimit: 0,
        isHarmful: false,
        leftValue: 0,
        livingId: 2,
        order: 0,
        parry: false,
        resistType: 0,
        resistValue: 0,
      },
      {
        damageType: 6,
        damageValue: 960355,
        dropInfos: [],
        extraData: 1,
        hasDamageType: true,
        hasDamageValue: true,
        hasExtraData: true,
        hasHasIcon: true,
        hasHpLimit: true,
        hasIcon: false,
        hasIsHarmful: false,
        hasLeftValue: true,
        hasLivingId: true,
        hasOrder: true,
        hasParry: true,
        hasResistType: true,
        hasResistValue: true,
        hpLimit: 0,
        isHarmful: false,
        leftValue: 0,
        livingId: 2,
        order: 1,
        parry: false,
        resistType: 0,
        resistValue: 0,
      },
    ],
    execFrame: 111,
    frame: 111,
    frameNum: 49,
    hasAttackMillis: true,
    hasAttackOrderSeq: false,
    hasAwake: true,
    hasAwakeAdd: false,
    hasBattleId: true,
    hasCdTime: false,
    hasExecFrame: true,
    hasFrame: true,
    hasFrameNum: true,
    hasIsPassive: true,
    hasLivingId: true,
    hasOrderId: true,
    hasSp: true,
    hasSpAdded: true,
    isPassive: false,
    livingId: 11,
    orderId: 20851,
    sp: 100,
    spAdded: 0,
  },
  AttackOrderMsg20311: {
    attackMillis: "2020-12-09 11:03:50",
    attackOrderSeq: 0,
    awake: 0,
    awakeAdd: 0,
    awakenSoldiers: [],
    battleId: "b029f02a-df83-4575-aeca-bc1dae6a4986",
    buffers: [
      {
        bufferId: 13,
        curTurn: 0,
        damage: [],
        execFrame: 0,
        exeWay: 3,
        hasBufferId: true,
        hasCurTurn: true,
        hasExecFrame: true,
        hasExeWay: true,
        hasMaxTurn: true,
        hasPressedNum: true,
        hasSeeType: true,
        hasSourceId: true,
        hasTargetId: true,
        hasTemplateId: true,
        maxTurn: 1,
        pressedNum: 1,
        seeType: 2,
        sourceId: 1,
        targetId: 1,
        templateId: 2004,
        unSkillIds: [],
      },
    ],
    cdTime: 0,
    damages: [
      {
        damageType: 6,
        damageValue: 1141757,
        dropInfos: [],
        extraData: 1, //1暴击 0不暴击
        hasDamageType: true,
        hasDamageValue: true,
        hasExtraData: true,
        hasHasIcon: true,
        hasHpLimit: true,
        hasIcon: false,
        hasIsHarmful: false,
        hasLeftValue: true,
        hasLivingId: true,
        hasOrder: true,
        hasParry: true,
        hasResistType: true,
        hasResistValue: true,
        hpLimit: 0,
        isHarmful: false,
        leftValue: 0,
        livingId: 7,
        order: 0,
        parry: false,
        resistType: 0,
        resistValue: 0,
      },
    ],
    execFrame: 111,
    frame: 111,
    frameNum: 49,
    hasAttackMillis: true,
    hasAttackOrderSeq: false,
    hasAwake: true,
    hasAwakeAdd: false,
    hasBattleId: true,
    hasCdTime: false,
    hasExecFrame: true,
    hasFrame: true,
    hasFrameNum: true,
    hasIsPassive: true,
    hasLivingId: true,
    hasOrderId: true,
    hasSp: true,
    hasSpAdded: true,
    isPassive: false,
    livingId: 11,
    orderId: 20311,
    sp: 100,
    spAdded: 0,
  },
  AttackOrderMsg21241: {
    attackMillis: "2020-12-09 11:03:50",
    attackOrderSeq: 0,
    awake: 0,
    awakeAdd: 0,
    awakenSoldiers: [],
    battleId: "b029f02a-df83-4575-aeca-bc1dae6a4986",
    buffers: [
      {
        bufferId: 13,
        curTurn: 0,
        damage: [],
        execFrame: 0,
        exeWay: 3,
        hasBufferId: true,
        hasCurTurn: true,
        hasExecFrame: true,
        hasExeWay: true,
        hasMaxTurn: true,
        hasPressedNum: true,
        hasSeeType: true,
        hasSourceId: true,
        hasTargetId: true,
        hasTemplateId: true,
        maxTurn: 1,
        pressedNum: 1,
        seeType: 2,
        sourceId: 1,
        targetId: 1,
        templateId: 2004,
        unSkillIds: [],
      },
    ],
    cdTime: 0,
    damages: [
      {
        damageType: 6,
        damageValue: 1141757,
        dropInfos: [],
        extraData: 1, //1暴击 0不暴击
        hasDamageType: true,
        hasDamageValue: true,
        hasExtraData: true,
        hasHasIcon: true,
        hasHpLimit: true,
        hasIcon: false,
        hasIsHarmful: false,
        hasLeftValue: true,
        hasLivingId: true,
        hasOrder: true,
        hasParry: true,
        hasResistType: true,
        hasResistValue: true,
        hpLimit: 0,
        isHarmful: false,
        leftValue: 0,
        livingId: 7,
        order: 0,
        parry: false,
        resistType: 0,
        resistValue: 0,
      },
    ],
    execFrame: 111,
    frame: 111,
    frameNum: 49,
    hasAttackMillis: true,
    hasAttackOrderSeq: false,
    hasAwake: true,
    hasAwakeAdd: false,
    hasBattleId: true,
    hasCdTime: false,
    hasExecFrame: true,
    hasFrame: true,
    hasFrameNum: true,
    hasIsPassive: true,
    hasLivingId: true,
    hasOrderId: true,
    hasSp: true,
    hasSpAdded: true,
    isPassive: false,
    livingId: 11,
    orderId: 21241,
    sp: 100,
    spAdded: 0,
  },
  AttackOrderMsg30000: {
    attackMillis: "2020-12-09 11:03:50",
    attackOrderSeq: 0,
    awake: 0,
    awakeAdd: 0,
    awakenSoldiers: [],
    battleId: "b029f02a-df83-4575-aeca-bc1dae6a4986",
    buffers: [
      {
        bufferId: 13,
        curTurn: 0,
        damage: [],
        execFrame: 0,
        exeWay: 3,
        hasBufferId: true,
        hasCurTurn: true,
        hasExecFrame: true,
        hasExeWay: true,
        hasMaxTurn: true,
        hasPressedNum: true,
        hasSeeType: true,
        hasSourceId: true,
        hasTargetId: true,
        hasTemplateId: true,
        maxTurn: 1,
        pressedNum: 1,
        seeType: 2,
        sourceId: 1,
        targetId: 1,
        templateId: 2004,
        unSkillIds: [],
      },
    ],
    cdTime: 0,
    damages: [
      {
        damageType: 6,
        damageValue: 1141757,
        dropInfos: [],
        extraData: 1, //1暴击 0不暴击
        hasDamageType: true,
        hasDamageValue: true,
        hasExtraData: true,
        hasHasIcon: true,
        hasHpLimit: true,
        hasIcon: false,
        hasIsHarmful: false,
        hasLeftValue: true,
        hasLivingId: true,
        hasOrder: true,
        hasParry: true,
        hasResistType: true,
        hasResistValue: true,
        hpLimit: 0,
        isHarmful: false,
        leftValue: 0,
        livingId: 3,
        order: 0,
        parry: false,
        resistType: 0,
        resistValue: 0,
      },
    ],
    execFrame: 111,
    frame: 111,
    frameNum: 49,
    hasAttackMillis: true,
    hasAttackOrderSeq: false,
    hasAwake: true,
    hasAwakeAdd: false,
    hasBattleId: true,
    hasCdTime: false,
    hasExecFrame: true,
    hasFrame: true,
    hasFrameNum: true,
    hasIsPassive: true,
    hasLivingId: true,
    hasOrderId: true,
    hasSp: true,
    hasSpAdded: true,
    isPassive: false,
    livingId: 12,
    orderId: 30000,
    sp: 100,
    spAdded: 0,
  },
  AttackOrderMsg50055: {
    attackMillis: "2020-12-09 11:03:50",
    attackOrderSeq: 0,
    awake: 0,
    awakeAdd: 0,
    awakenSoldiers: [],
    battleId: "b029f02a-df83-4575-aeca-bc1dae6a4986",
    buffers: [
      {
        bufferId: 13,
        curTurn: 0,
        damage: [],
        execFrame: 0,
        exeWay: 3,
        hasBufferId: true,
        hasCurTurn: true,
        hasExecFrame: true,
        hasExeWay: true,
        hasMaxTurn: true,
        hasPressedNum: true,
        hasSeeType: true,
        hasSourceId: true,
        hasTargetId: true,
        hasTemplateId: true,
        maxTurn: 1,
        pressedNum: 1,
        seeType: 2,
        sourceId: 1,
        targetId: 1,
        templateId: 2004,
        unSkillIds: [],
      },
    ],
    cdTime: 0,
    damages: [
      {
        damageType: 6,
        damageValue: 1141757,
        dropInfos: [],
        extraData: 1, //1暴击 0不暴击
        hasDamageType: true,
        hasDamageValue: true,
        hasExtraData: true,
        hasHasIcon: true,
        hasHpLimit: true,
        hasIcon: false,
        hasIsHarmful: false,
        hasLeftValue: true,
        hasLivingId: true,
        hasOrder: true,
        hasParry: true,
        hasResistType: true,
        hasResistValue: true,
        hpLimit: 0,
        isHarmful: false,
        leftValue: 0,
        livingId: 11,
        order: 0,
        parry: false,
        resistType: 0,
        resistValue: 0,
      },
    ],
    execFrame: 111,
    frame: 111,
    frameNum: 49,
    hasAttackMillis: true,
    hasAttackOrderSeq: false,
    hasAwake: true,
    hasAwakeAdd: false,
    hasBattleId: true,
    hasCdTime: false,
    hasExecFrame: true,
    hasFrame: true,
    hasFrameNum: true,
    hasIsPassive: true,
    hasLivingId: true,
    hasOrderId: true,
    hasSp: true,
    hasSpAdded: true,
    isPassive: false,
    livingId: 8,
    orderId: 50055,
    sp: 100,
    spAdded: 0,
  },
  BattlePrepareMsg: {
    heros: [
      {
        livingId2: 0,
        heroId: 340475,
        livingId: 11, //一场战斗每个角色的唯一标志
        userId: 353256,
        userPics: 5,
        tempId: 5,
        type: 1, //英雄类型   3为boss
        nickName: "fyundi",
        grade: 80,
        side: 1,
        pos: 1,
        maxHp: 16645,
        hp: 63101, //// 英雄实际血量   是死是活全由他
        initHp2: 0,
        hp2: 0,
        sp: 100,
        slotAvata: "",
        clothAvate: "",
        cloakPath: "",
        hairPath: "",
        wingAvata: "",
        fashionClothAvata: "",
        fashionArmAvata: "",
        fateSkillTempIds: "2100,2005,",
        pawnTempId: 10964,
        res: "",
        isShow: false,
        hasShadow: false,
        qteTime: 0,
        castTime: 4500,
        skillId: [
          30751, 30851, 31031, 30331, 30521, 30121, 30231, 30421, 2100, 2005,
          30011, 7105, 7104, 7103, 7102, 7101,
        ],
        changeSkillId: [704001, 706101, 708101],
        serverName: "null-1区",
        isChange: false,
        awake: 325,
      },
      {
        livingId2: 0,
        heroId: 340475,
        livingId: 12, //一场战斗每个角色的唯一标志
        userId: 353255,
        userPics: 3,
        tempId: 3,
        type: 1, //英雄类型   3为boss
        nickName: "huang01",
        grade: 80,
        side: 1,
        pos: 2,
        maxHp: 16645,
        hp: 63101, //// 英雄实际血量   是死是活全由他
        initHp2: 0,
        hp2: 0,
        sp: 100,
        slotAvata: "",
        clothAvate: "",
        cloakPath: "",
        hairPath: "",
        wingAvata: "",
        fashionClothAvata: "",
        fashionArmAvata: "",
        fateSkillTempIds: "2100,2005,",
        pawnTempId: 10964,
        res: "",
        isShow: false,
        hasShadow: false,
        qteTime: 0,
        castTime: 4500,
        skillId: [
          30751, 30851, 31031, 30331, 30521, 30121, 30231, 30421, 2100, 2005,
          30011, 7105, 7104, 7103, 7102, 7101,
        ],
        changeSkillId: [704001, 706101, 708101],
        serverName: "null-1区",
        isChange: false,
        awake: 325,
      },
    ],
    soldiers: [
      {
        armyPawnId: 0,
        attackWound: 0,
        castTime: 5000,
        forceHit: 0,
        grade: 0,
        hasArmyPawnId: false,
        hasAttackWound: false,
        hasCastTime: true,
        hasForceHit: false,
        hasGrade: false,
        hasHitWound: false,
        hasHp: true,
        hasInitHp: true,
        hasLivingId: true,
        hasMagAttack: false,
        hasMagDefence: false,
        hasParry: false,
        hasPhyAttack: false,
        hasPhyDefence: false,
        hasPos: true,
        hasQteTime: true,
        hasSide: true,
        hasSites: false,
        hasTempId: true,
        hasType: true,
        hitWound: 0,
        hp: 1155,
        initHp: 1155,
        livingId: 2,
        magAttack: 0,
        magDefence: 0,
        parry: 0,
        phyAttack: 0,
        phyDefence: 0,
        pos: 1,
        qteTime: 0,
        side: 2,
        sites: 0,
        skillId: [40201, 40202],
        tempId: 2072,
        type: 1,
      },
      {
        armyPawnId: 0,
        attackWound: 0,
        castTime: 5000,
        forceHit: 0,
        grade: 0,
        hasArmyPawnId: false,
        hasAttackWound: false,
        hasCastTime: true,
        hasForceHit: false,
        hasGrade: false,
        hasHitWound: false,
        hasHp: true,
        hasInitHp: true,
        hasLivingId: true,
        hasMagAttack: false,
        hasMagDefence: false,
        hasParry: false,
        hasPhyAttack: false,
        hasPhyDefence: false,
        hasPos: true,
        hasQteTime: true,
        hasSide: true,
        hasSites: false,
        hasTempId: true,
        hasType: true,
        hitWound: 0,
        hp: 1155,
        initHp: 1155,
        livingId: 3,
        magAttack: 0,
        magDefence: 0,
        parry: 0,
        phyAttack: 0,
        phyDefence: 0,
        pos: 2,
        qteTime: 0,
        side: 2,
        sites: 0,
        skillId: [40201, 40202],
        tempId: 2072,
        type: 1,
      },
      {
        armyPawnId: 0,
        attackWound: 0,
        castTime: 5000,
        forceHit: 0,
        grade: 0,
        hasArmyPawnId: false,
        hasAttackWound: false,
        hasCastTime: true,
        hasForceHit: false,
        hasGrade: false,
        hasHitWound: false,
        hasHp: true,
        hasInitHp: true,
        hasLivingId: true,
        hasMagAttack: false,
        hasMagDefence: false,
        hasParry: false,
        hasPhyAttack: false,
        hasPhyDefence: false,
        hasPos: true,
        hasQteTime: true,
        hasSide: true,
        hasSites: false,
        hasTempId: true,
        hasType: true,
        hitWound: 0,
        hp: 1155,
        initHp: 1155,
        livingId: 4,
        magAttack: 0,
        magDefence: 0,
        parry: 0,
        phyAttack: 0,
        phyDefence: 0,
        pos: 3,
        qteTime: 0,
        side: 2,
        sites: 0,
        skillId: [40201, 40202],
        tempId: 2072,
        type: 1,
      },
      {
        armyPawnId: 0,
        attackWound: 0,
        castTime: 5000,
        forceHit: 0,
        grade: 0,
        hasArmyPawnId: false,
        hasAttackWound: false,
        hasCastTime: true,
        hasForceHit: false,
        hasGrade: false,
        hasHitWound: false,
        hasHp: true,
        hasInitHp: true,
        hasLivingId: true,
        hasMagAttack: false,
        hasMagDefence: false,
        hasParry: false,
        hasPhyAttack: false,
        hasPhyDefence: false,
        hasPos: true,
        hasQteTime: true,
        hasSide: true,
        hasSites: false,
        hasTempId: true,
        hasType: true,
        hitWound: 0,
        hp: 1155,
        initHp: 1155,
        livingId: 5,
        magAttack: 0,
        magDefence: 0,
        parry: 0,
        phyAttack: 0,
        phyDefence: 0,
        pos: 5,
        qteTime: 0,
        side: 2,
        sites: 0,
        skillId: [40201, 40202],
        tempId: 2072,
        type: 1,
      },
      {
        armyPawnId: 0,
        attackWound: 0,
        castTime: 5000,
        forceHit: 0,
        grade: 0,
        hasArmyPawnId: false,
        hasAttackWound: false,
        hasCastTime: true,
        hasForceHit: false,
        hasGrade: false,
        hasHitWound: false,
        hasHp: true,
        hasInitHp: true,
        hasLivingId: true,
        hasMagAttack: false,
        hasMagDefence: false,
        hasParry: false,
        hasPhyAttack: false,
        hasPhyDefence: false,
        hasPos: true,
        hasQteTime: true,
        hasSide: true,
        hasSites: false,
        hasTempId: true,
        hasType: true,
        hitWound: 0,
        hp: 1155,
        initHp: 1155,
        livingId: 7,
        magAttack: 0,
        magDefence: 0,
        parry: 0,
        phyAttack: 0,
        phyDefence: 0,
        pos: 7,
        qteTime: 0,
        side: 2,
        sites: 0,
        skillId: [40201, 40202],
        tempId: 2072,
        type: 1,
      },
      {
        armyPawnId: 0,
        attackWound: 0,
        castTime: 5000,
        forceHit: 0,
        grade: 0,
        hasArmyPawnId: false,
        hasAttackWound: false,
        hasCastTime: true,
        hasForceHit: false,
        hasGrade: false,
        hasHitWound: false,
        hasHp: true,
        hasInitHp: true,
        hasLivingId: true,
        hasMagAttack: false,
        hasMagDefence: false,
        hasParry: false,
        hasPhyAttack: false,
        hasPhyDefence: false,
        hasPos: true,
        hasQteTime: true,
        hasSide: true,
        hasSites: false,
        hasTempId: true,
        hasType: true,
        hitWound: 0,
        hp: 1155,
        initHp: 1155,
        livingId: 8,
        magAttack: 0,
        magDefence: 0,
        parry: 0,
        phyAttack: 0,
        phyDefence: 0,
        pos: 8,
        qteTime: 0,
        side: 2,
        sites: 0,
        skillId: [50055, 50056],
        tempId: 2431,
        type: 1,
      },
    ],
    pets: [],
  },
};

export { TestBattleData_5_fyundi };
