// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: gamebox/MoleGameInfoRes.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.gamebox";

export interface MoleGameInfoRes {
  score: number;
  laveTimes: number;
  record: string;
  lastRecord: number[];
}

function createBaseMoleGameInfoRes(): MoleGameInfoRes {
  return { score: 0, laveTimes: 0, record: "", lastRecord: [] };
}

export const MoleGameInfoRes: MessageFns<MoleGameInfoRes> = {
  encode(message: MoleGameInfoRes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.score !== 0) {
      writer.uint32(8).int32(message.score);
    }
    if (message.laveTimes !== 0) {
      writer.uint32(16).int32(message.laveTimes);
    }
    if (message.record !== "") {
      writer.uint32(26).string(message.record);
    }
    writer.uint32(34).fork();
    for (const v of message.lastRecord) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MoleGameInfoRes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoleGameInfoRes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.score = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.laveTimes = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.record = reader.string();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.lastRecord.push(reader.int32());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.lastRecord.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MoleGameInfoRes {
    return {
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
      laveTimes: isSet(object.laveTimes) ? globalThis.Number(object.laveTimes) : 0,
      record: isSet(object.record) ? globalThis.String(object.record) : "",
      lastRecord: globalThis.Array.isArray(object?.lastRecord)
        ? object.lastRecord.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: MoleGameInfoRes): unknown {
    const obj: any = {};
    if (message.score !== 0) {
      obj.score = Math.round(message.score);
    }
    if (message.laveTimes !== 0) {
      obj.laveTimes = Math.round(message.laveTimes);
    }
    if (message.record !== "") {
      obj.record = message.record;
    }
    if (message.lastRecord?.length) {
      obj.lastRecord = message.lastRecord.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MoleGameInfoRes>, I>>(base?: I): MoleGameInfoRes {
    return MoleGameInfoRes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MoleGameInfoRes>, I>>(object: I): MoleGameInfoRes {
    const message = createBaseMoleGameInfoRes();
    message.score = object.score ?? 0;
    message.laveTimes = object.laveTimes ?? 0;
    message.record = object.record ?? "";
    message.lastRecord = object.lastRecord?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
