// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: castle/CastleReqMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.castle";

export interface CastleReqMsg {
  magId: number;
  posX: number;
  posY: number;
  leftTime: number;
  leftEnergy: number;
  payType: number;
  isTransfer: boolean;
}

function createBaseCastleReqMsg(): CastleReqMsg {
  return { magId: 0, posX: 0, posY: 0, leftTime: 0, leftEnergy: 0, payType: 0, isTransfer: false };
}

export const CastleReqMsg: MessageFns<CastleReqMsg> = {
  encode(message: CastleReqMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.magId !== 0) {
      writer.uint32(8).int32(message.magId);
    }
    if (message.posX !== 0) {
      writer.uint32(16).int32(message.posX);
    }
    if (message.posY !== 0) {
      writer.uint32(24).int32(message.posY);
    }
    if (message.leftTime !== 0) {
      writer.uint32(32).int32(message.leftTime);
    }
    if (message.leftEnergy !== 0) {
      writer.uint32(40).int32(message.leftEnergy);
    }
    if (message.payType !== 0) {
      writer.uint32(48).int32(message.payType);
    }
    if (message.isTransfer !== false) {
      writer.uint32(56).bool(message.isTransfer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CastleReqMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCastleReqMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.magId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.posX = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.posY = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.leftTime = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.leftEnergy = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.payType = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isTransfer = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CastleReqMsg {
    return {
      magId: isSet(object.magId) ? globalThis.Number(object.magId) : 0,
      posX: isSet(object.posX) ? globalThis.Number(object.posX) : 0,
      posY: isSet(object.posY) ? globalThis.Number(object.posY) : 0,
      leftTime: isSet(object.leftTime) ? globalThis.Number(object.leftTime) : 0,
      leftEnergy: isSet(object.leftEnergy) ? globalThis.Number(object.leftEnergy) : 0,
      payType: isSet(object.payType) ? globalThis.Number(object.payType) : 0,
      isTransfer: isSet(object.isTransfer) ? globalThis.Boolean(object.isTransfer) : false,
    };
  },

  toJSON(message: CastleReqMsg): unknown {
    const obj: any = {};
    if (message.magId !== 0) {
      obj.magId = Math.round(message.magId);
    }
    if (message.posX !== 0) {
      obj.posX = Math.round(message.posX);
    }
    if (message.posY !== 0) {
      obj.posY = Math.round(message.posY);
    }
    if (message.leftTime !== 0) {
      obj.leftTime = Math.round(message.leftTime);
    }
    if (message.leftEnergy !== 0) {
      obj.leftEnergy = Math.round(message.leftEnergy);
    }
    if (message.payType !== 0) {
      obj.payType = Math.round(message.payType);
    }
    if (message.isTransfer !== false) {
      obj.isTransfer = message.isTransfer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CastleReqMsg>, I>>(base?: I): CastleReqMsg {
    return CastleReqMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CastleReqMsg>, I>>(object: I): CastleReqMsg {
    const message = createBaseCastleReqMsg();
    message.magId = object.magId ?? 0;
    message.posX = object.posX ?? 0;
    message.posY = object.posY ?? 0;
    message.leftTime = object.leftTime ?? 0;
    message.leftEnergy = object.leftEnergy ?? 0;
    message.payType = object.payType ?? 0;
    message.isTransfer = object.isTransfer ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
