// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: simple/FriendSearchNickNameReqMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.simple";

export interface FriendSearchNickNameReqMsg {
  nickName: string;
}

function createBaseFriendSearchNickNameReqMsg(): FriendSearchNickNameReqMsg {
  return { nickName: "" };
}

export const FriendSearchNickNameReqMsg: MessageFns<FriendSearchNickNameReqMsg> = {
  encode(message: FriendSearchNickNameReqMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nickName !== "") {
      writer.uint32(10).string(message.nickName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FriendSearchNickNameReqMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFriendSearchNickNameReqMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nickName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FriendSearchNickNameReqMsg {
    return { nickName: isSet(object.nickName) ? globalThis.String(object.nickName) : "" };
  },

  toJSON(message: FriendSearchNickNameReqMsg): unknown {
    const obj: any = {};
    if (message.nickName !== "") {
      obj.nickName = message.nickName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FriendSearchNickNameReqMsg>, I>>(base?: I): FriendSearchNickNameReqMsg {
    return FriendSearchNickNameReqMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FriendSearchNickNameReqMsg>, I>>(object: I): FriendSearchNickNameReqMsg {
    const message = createBaseFriendSearchNickNameReqMsg();
    message.nickName = object.nickName ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
