// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: simple/PropertyListMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.simple";

export interface PropertyListMsg {
  param1: number;
  param2: number;
  param3: string;
  property: number[];
}

function createBasePropertyListMsg(): PropertyListMsg {
  return { param1: 0, param2: 0, param3: "", property: [] };
}

export const PropertyListMsg: MessageFns<PropertyListMsg> = {
  encode(message: PropertyListMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.param1 !== 0) {
      writer.uint32(8).int32(message.param1);
    }
    if (message.param2 !== 0) {
      writer.uint32(16).int32(message.param2);
    }
    if (message.param3 !== "") {
      writer.uint32(26).string(message.param3);
    }
    writer.uint32(34).fork();
    for (const v of message.property) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PropertyListMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePropertyListMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.param1 = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.param2 = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.param3 = reader.string();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.property.push(reader.int32());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.property.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PropertyListMsg {
    return {
      param1: isSet(object.param1) ? globalThis.Number(object.param1) : 0,
      param2: isSet(object.param2) ? globalThis.Number(object.param2) : 0,
      param3: isSet(object.param3) ? globalThis.String(object.param3) : "",
      property: globalThis.Array.isArray(object?.property) ? object.property.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: PropertyListMsg): unknown {
    const obj: any = {};
    if (message.param1 !== 0) {
      obj.param1 = Math.round(message.param1);
    }
    if (message.param2 !== 0) {
      obj.param2 = Math.round(message.param2);
    }
    if (message.param3 !== "") {
      obj.param3 = message.param3;
    }
    if (message.property?.length) {
      obj.property = message.property.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PropertyListMsg>, I>>(base?: I): PropertyListMsg {
    return PropertyListMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PropertyListMsg>, I>>(object: I): PropertyListMsg {
    const message = createBasePropertyListMsg();
    message.param1 = object.param1 ?? 0;
    message.param2 = object.param2 ?? 0;
    message.param3 = object.param3 ?? "";
    message.property = object.property?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
