// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: campaign/NPCChaseMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.campaign";

export interface NPCChaseMsg {
  nodeId: number;
  armyId: number;
  curPosX: number;
  curPosY: number;
  serverName: string;
}

function createBaseNPCChaseMsg(): NPCChaseMsg {
  return { nodeId: 0, armyId: 0, curPosX: 0, curPosY: 0, serverName: "" };
}

export const NPCChaseMsg: MessageFns<NPCChaseMsg> = {
  encode(message: NPCChaseMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== 0) {
      writer.uint32(8).int32(message.nodeId);
    }
    if (message.armyId !== 0) {
      writer.uint32(16).int32(message.armyId);
    }
    if (message.curPosX !== 0) {
      writer.uint32(24).int32(message.curPosX);
    }
    if (message.curPosY !== 0) {
      writer.uint32(32).int32(message.curPosY);
    }
    if (message.serverName !== "") {
      writer.uint32(42).string(message.serverName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NPCChaseMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNPCChaseMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.nodeId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.armyId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.curPosX = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.curPosY = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.serverName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NPCChaseMsg {
    return {
      nodeId: isSet(object.nodeId) ? globalThis.Number(object.nodeId) : 0,
      armyId: isSet(object.armyId) ? globalThis.Number(object.armyId) : 0,
      curPosX: isSet(object.curPosX) ? globalThis.Number(object.curPosX) : 0,
      curPosY: isSet(object.curPosY) ? globalThis.Number(object.curPosY) : 0,
      serverName: isSet(object.serverName) ? globalThis.String(object.serverName) : "",
    };
  },

  toJSON(message: NPCChaseMsg): unknown {
    const obj: any = {};
    if (message.nodeId !== 0) {
      obj.nodeId = Math.round(message.nodeId);
    }
    if (message.armyId !== 0) {
      obj.armyId = Math.round(message.armyId);
    }
    if (message.curPosX !== 0) {
      obj.curPosX = Math.round(message.curPosX);
    }
    if (message.curPosY !== 0) {
      obj.curPosY = Math.round(message.curPosY);
    }
    if (message.serverName !== "") {
      obj.serverName = message.serverName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NPCChaseMsg>, I>>(base?: I): NPCChaseMsg {
    return NPCChaseMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NPCChaseMsg>, I>>(object: I): NPCChaseMsg {
    const message = createBaseNPCChaseMsg();
    message.nodeId = object.nodeId ?? 0;
    message.armyId = object.armyId ?? 0;
    message.curPosX = object.curPosX ?? 0;
    message.curPosY = object.curPosY ?? 0;
    message.serverName = object.serverName ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
