// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: campaign/TaskCampaignReqMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.campaign";

export interface TaskCampaignReqMsg {
  dungeonId: number;
  campaignId: number;
}

function createBaseTaskCampaignReqMsg(): TaskCampaignReqMsg {
  return { dungeonId: 0, campaignId: 0 };
}

export const TaskCampaignReqMsg: MessageFns<TaskCampaignReqMsg> = {
  encode(message: TaskCampaignReqMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dungeonId !== 0) {
      writer.uint32(8).int32(message.dungeonId);
    }
    if (message.campaignId !== 0) {
      writer.uint32(16).int32(message.campaignId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskCampaignReqMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskCampaignReqMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.dungeonId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.campaignId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskCampaignReqMsg {
    return {
      dungeonId: isSet(object.dungeonId) ? globalThis.Number(object.dungeonId) : 0,
      campaignId: isSet(object.campaignId) ? globalThis.Number(object.campaignId) : 0,
    };
  },

  toJSON(message: TaskCampaignReqMsg): unknown {
    const obj: any = {};
    if (message.dungeonId !== 0) {
      obj.dungeonId = Math.round(message.dungeonId);
    }
    if (message.campaignId !== 0) {
      obj.campaignId = Math.round(message.campaignId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskCampaignReqMsg>, I>>(base?: I): TaskCampaignReqMsg {
    return TaskCampaignReqMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskCampaignReqMsg>, I>>(object: I): TaskCampaignReqMsg {
    const message = createBaseTaskCampaignReqMsg();
    message.dungeonId = object.dungeonId ?? 0;
    message.campaignId = object.campaignId ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
