// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: campaign/WarFieldAttackMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.campaign";

export interface WarFieldAttackMsg {
  userId: number;
  serverName: string;
  defenceServerName: string;
}

function createBaseWarFieldAttackMsg(): WarFieldAttackMsg {
  return { userId: 0, serverName: "", defenceServerName: "" };
}

export const WarFieldAttackMsg: MessageFns<WarFieldAttackMsg> = {
  encode(message: WarFieldAttackMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.serverName !== "") {
      writer.uint32(18).string(message.serverName);
    }
    if (message.defenceServerName !== "") {
      writer.uint32(26).string(message.defenceServerName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WarFieldAttackMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWarFieldAttackMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.defenceServerName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WarFieldAttackMsg {
    return {
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      serverName: isSet(object.serverName) ? globalThis.String(object.serverName) : "",
      defenceServerName: isSet(object.defenceServerName) ? globalThis.String(object.defenceServerName) : "",
    };
  },

  toJSON(message: WarFieldAttackMsg): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.serverName !== "") {
      obj.serverName = message.serverName;
    }
    if (message.defenceServerName !== "") {
      obj.defenceServerName = message.defenceServerName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WarFieldAttackMsg>, I>>(base?: I): WarFieldAttackMsg {
    return WarFieldAttackMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WarFieldAttackMsg>, I>>(object: I): WarFieldAttackMsg {
    const message = createBaseWarFieldAttackMsg();
    message.userId = object.userId ?? 0;
    message.serverName = object.serverName ?? "";
    message.defenceServerName = object.defenceServerName ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
