// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: campaign/WorldBossBufferMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.campaign";

export interface WorldBossBufferMsg {
  type: number;
  pointValue: number;
  giftValue: number;
  op: number;
  result: number;
  wound: number;
}

function createBaseWorldBossBufferMsg(): WorldBossBufferMsg {
  return { type: 0, pointValue: 0, giftValue: 0, op: 0, result: 0, wound: 0 };
}

export const WorldBossBufferMsg: MessageFns<WorldBossBufferMsg> = {
  encode(message: WorldBossBufferMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.pointValue !== 0) {
      writer.uint32(16).int32(message.pointValue);
    }
    if (message.giftValue !== 0) {
      writer.uint32(24).int32(message.giftValue);
    }
    if (message.op !== 0) {
      writer.uint32(32).int32(message.op);
    }
    if (message.result !== 0) {
      writer.uint32(40).int32(message.result);
    }
    if (message.wound !== 0) {
      writer.uint32(48).int32(message.wound);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorldBossBufferMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorldBossBufferMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pointValue = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.giftValue = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.op = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.result = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.wound = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorldBossBufferMsg {
    return {
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      pointValue: isSet(object.pointValue) ? globalThis.Number(object.pointValue) : 0,
      giftValue: isSet(object.giftValue) ? globalThis.Number(object.giftValue) : 0,
      op: isSet(object.op) ? globalThis.Number(object.op) : 0,
      result: isSet(object.result) ? globalThis.Number(object.result) : 0,
      wound: isSet(object.wound) ? globalThis.Number(object.wound) : 0,
    };
  },

  toJSON(message: WorldBossBufferMsg): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.pointValue !== 0) {
      obj.pointValue = Math.round(message.pointValue);
    }
    if (message.giftValue !== 0) {
      obj.giftValue = Math.round(message.giftValue);
    }
    if (message.op !== 0) {
      obj.op = Math.round(message.op);
    }
    if (message.result !== 0) {
      obj.result = Math.round(message.result);
    }
    if (message.wound !== 0) {
      obj.wound = Math.round(message.wound);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorldBossBufferMsg>, I>>(base?: I): WorldBossBufferMsg {
    return WorldBossBufferMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorldBossBufferMsg>, I>>(object: I): WorldBossBufferMsg {
    const message = createBaseWorldBossBufferMsg();
    message.type = object.type ?? 0;
    message.pointValue = object.pointValue ?? 0;
    message.giftValue = object.giftValue ?? 0;
    message.op = object.op ?? 0;
    message.result = object.result ?? 0;
    message.wound = object.wound ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
