// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: shop/MainGoodInfo.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.shop";

export interface MainGoodInfo {
  id: number;
  shopId: number;
  templateId: number;
  sortId: number;
  types: number;
}

function createBaseMainGoodInfo(): MainGoodInfo {
  return { id: 0, shopId: 0, templateId: 0, sortId: 0, types: 0 };
}

export const MainGoodInfo: MessageFns<MainGoodInfo> = {
  encode(message: MainGoodInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.shopId !== 0) {
      writer.uint32(16).int32(message.shopId);
    }
    if (message.templateId !== 0) {
      writer.uint32(24).int32(message.templateId);
    }
    if (message.sortId !== 0) {
      writer.uint32(32).int32(message.sortId);
    }
    if (message.types !== 0) {
      writer.uint32(40).int32(message.types);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MainGoodInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMainGoodInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.shopId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.templateId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sortId = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.types = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MainGoodInfo {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      shopId: isSet(object.shopId) ? globalThis.Number(object.shopId) : 0,
      templateId: isSet(object.templateId) ? globalThis.Number(object.templateId) : 0,
      sortId: isSet(object.sortId) ? globalThis.Number(object.sortId) : 0,
      types: isSet(object.types) ? globalThis.Number(object.types) : 0,
    };
  },

  toJSON(message: MainGoodInfo): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.shopId !== 0) {
      obj.shopId = Math.round(message.shopId);
    }
    if (message.templateId !== 0) {
      obj.templateId = Math.round(message.templateId);
    }
    if (message.sortId !== 0) {
      obj.sortId = Math.round(message.sortId);
    }
    if (message.types !== 0) {
      obj.types = Math.round(message.types);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MainGoodInfo>, I>>(base?: I): MainGoodInfo {
    return MainGoodInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MainGoodInfo>, I>>(object: I): MainGoodInfo {
    const message = createBaseMainGoodInfo();
    message.id = object.id ?? 0;
    message.shopId = object.shopId ?? 0;
    message.templateId = object.templateId ?? 0;
    message.sortId = object.sortId ?? 0;
    message.types = object.types ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
