// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: player/ChallengeRankRewardMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.player";

export interface ChallengeRankRewardMsg {
  isTake: boolean;
  param1: number;
  param2: number;
  param3: number;
  param4: number;
}

function createBaseChallengeRankRewardMsg(): ChallengeRankRewardMsg {
  return { isTake: false, param1: 0, param2: 0, param3: 0, param4: 0 };
}

export const ChallengeRankRewardMsg: MessageFns<ChallengeRankRewardMsg> = {
  encode(message: ChallengeRankRewardMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isTake !== false) {
      writer.uint32(8).bool(message.isTake);
    }
    if (message.param1 !== 0) {
      writer.uint32(16).int32(message.param1);
    }
    if (message.param2 !== 0) {
      writer.uint32(24).int32(message.param2);
    }
    if (message.param3 !== 0) {
      writer.uint32(32).int32(message.param3);
    }
    if (message.param4 !== 0) {
      writer.uint32(40).int32(message.param4);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChallengeRankRewardMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChallengeRankRewardMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isTake = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.param1 = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.param2 = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.param3 = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.param4 = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChallengeRankRewardMsg {
    return {
      isTake: isSet(object.isTake) ? globalThis.Boolean(object.isTake) : false,
      param1: isSet(object.param1) ? globalThis.Number(object.param1) : 0,
      param2: isSet(object.param2) ? globalThis.Number(object.param2) : 0,
      param3: isSet(object.param3) ? globalThis.Number(object.param3) : 0,
      param4: isSet(object.param4) ? globalThis.Number(object.param4) : 0,
    };
  },

  toJSON(message: ChallengeRankRewardMsg): unknown {
    const obj: any = {};
    if (message.isTake !== false) {
      obj.isTake = message.isTake;
    }
    if (message.param1 !== 0) {
      obj.param1 = Math.round(message.param1);
    }
    if (message.param2 !== 0) {
      obj.param2 = Math.round(message.param2);
    }
    if (message.param3 !== 0) {
      obj.param3 = Math.round(message.param3);
    }
    if (message.param4 !== 0) {
      obj.param4 = Math.round(message.param4);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChallengeRankRewardMsg>, I>>(base?: I): ChallengeRankRewardMsg {
    return ChallengeRankRewardMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChallengeRankRewardMsg>, I>>(object: I): ChallengeRankRewardMsg {
    const message = createBaseChallengeRankRewardMsg();
    message.isTake = object.isTake ?? false;
    message.param1 = object.param1 ?? 0;
    message.param2 = object.param2 ?? 0;
    message.param3 = object.param3 ?? 0;
    message.param4 = object.param4 ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
