// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: player/ChallengeCoolTimeMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.player";

export interface ChallengeCoolTimeMsg {
  leftTime: number;
  challengeCount: number;
  totalCount: number;
  type: number;
  totalBuyCount: number;
}

function createBaseChallengeCoolTimeMsg(): ChallengeCoolTimeMsg {
  return { leftTime: 0, challengeCount: 0, totalCount: 0, type: 0, totalBuyCount: 0 };
}

export const ChallengeCoolTimeMsg: MessageFns<ChallengeCoolTimeMsg> = {
  encode(message: ChallengeCoolTimeMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.leftTime !== 0) {
      writer.uint32(8).int32(message.leftTime);
    }
    if (message.challengeCount !== 0) {
      writer.uint32(16).int32(message.challengeCount);
    }
    if (message.totalCount !== 0) {
      writer.uint32(24).int32(message.totalCount);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    if (message.totalBuyCount !== 0) {
      writer.uint32(40).int32(message.totalBuyCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChallengeCoolTimeMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChallengeCoolTimeMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.leftTime = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.challengeCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalCount = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.totalBuyCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChallengeCoolTimeMsg {
    return {
      leftTime: isSet(object.leftTime) ? globalThis.Number(object.leftTime) : 0,
      challengeCount: isSet(object.challengeCount) ? globalThis.Number(object.challengeCount) : 0,
      totalCount: isSet(object.totalCount) ? globalThis.Number(object.totalCount) : 0,
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      totalBuyCount: isSet(object.totalBuyCount) ? globalThis.Number(object.totalBuyCount) : 0,
    };
  },

  toJSON(message: ChallengeCoolTimeMsg): unknown {
    const obj: any = {};
    if (message.leftTime !== 0) {
      obj.leftTime = Math.round(message.leftTime);
    }
    if (message.challengeCount !== 0) {
      obj.challengeCount = Math.round(message.challengeCount);
    }
    if (message.totalCount !== 0) {
      obj.totalCount = Math.round(message.totalCount);
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.totalBuyCount !== 0) {
      obj.totalBuyCount = Math.round(message.totalBuyCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChallengeCoolTimeMsg>, I>>(base?: I): ChallengeCoolTimeMsg {
    return ChallengeCoolTimeMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChallengeCoolTimeMsg>, I>>(object: I): ChallengeCoolTimeMsg {
    const message = createBaseChallengeCoolTimeMsg();
    message.leftTime = object.leftTime ?? 0;
    message.challengeCount = object.challengeCount ?? 0;
    message.totalCount = object.totalCount ?? 0;
    message.type = object.type ?? 0;
    message.totalBuyCount = object.totalBuyCount ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
