// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: player/RewardCountUpdateRspMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.player";

export interface RewardCountUpdateRspMsg {
  rewardCount: number;
}

function createBaseRewardCountUpdateRspMsg(): RewardCountUpdateRspMsg {
  return { rewardCount: 0 };
}

export const RewardCountUpdateRspMsg: MessageFns<RewardCountUpdateRspMsg> = {
  encode(message: RewardCountUpdateRspMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rewardCount !== 0) {
      writer.uint32(8).int32(message.rewardCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RewardCountUpdateRspMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRewardCountUpdateRspMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.rewardCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RewardCountUpdateRspMsg {
    return { rewardCount: isSet(object.rewardCount) ? globalThis.Number(object.rewardCount) : 0 };
  },

  toJSON(message: RewardCountUpdateRspMsg): unknown {
    const obj: any = {};
    if (message.rewardCount !== 0) {
      obj.rewardCount = Math.round(message.rewardCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RewardCountUpdateRspMsg>, I>>(base?: I): RewardCountUpdateRspMsg {
    return RewardCountUpdateRspMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RewardCountUpdateRspMsg>, I>>(object: I): RewardCountUpdateRspMsg {
    const message = createBaseRewardCountUpdateRspMsg();
    message.rewardCount = object.rewardCount ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
