// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: player/SnsRspMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.player";

export interface SnsRspMsg {
  type: number;
  data: string;
  md5: string;
  site: string;
}

function createBaseSnsRspMsg(): SnsRspMsg {
  return { type: 0, data: "", md5: "", site: "" };
}

export const SnsRspMsg: MessageFns<SnsRspMsg> = {
  encode(message: SnsRspMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.data !== "") {
      writer.uint32(18).string(message.data);
    }
    if (message.md5 !== "") {
      writer.uint32(26).string(message.md5);
    }
    if (message.site !== "") {
      writer.uint32(34).string(message.site);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SnsRspMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSnsRspMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.md5 = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.site = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SnsRspMsg {
    return {
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      md5: isSet(object.md5) ? globalThis.String(object.md5) : "",
      site: isSet(object.site) ? globalThis.String(object.site) : "",
    };
  },

  toJSON(message: SnsRspMsg): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.md5 !== "") {
      obj.md5 = message.md5;
    }
    if (message.site !== "") {
      obj.site = message.site;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SnsRspMsg>, I>>(base?: I): SnsRspMsg {
    return SnsRspMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SnsRspMsg>, I>>(object: I): SnsRspMsg {
    const message = createBaseSnsRspMsg();
    message.type = object.type ?? 0;
    message.data = object.data ?? "";
    message.md5 = object.md5 ?? "";
    message.site = object.site ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
