// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: friend/AddFriendFavorMsg.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.road.yishi.proto.friend";

export interface AddFriendFavorMsg {
  playerId: number;
  friendId: number;
  addCount: number;
  waterCount: number;
  goldCount: number;
  treeGpCount: number;
  property1: number;
  property2: number;
  isUpGrade: boolean;
}

function createBaseAddFriendFavorMsg(): AddFriendFavorMsg {
  return {
    playerId: 0,
    friendId: 0,
    addCount: 0,
    waterCount: 0,
    goldCount: 0,
    treeGpCount: 0,
    property1: 0,
    property2: 0,
    isUpGrade: false,
  };
}

export const AddFriendFavorMsg: MessageFns<AddFriendFavorMsg> = {
  encode(message: AddFriendFavorMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerId !== 0) {
      writer.uint32(8).int32(message.playerId);
    }
    if (message.friendId !== 0) {
      writer.uint32(16).int32(message.friendId);
    }
    if (message.addCount !== 0) {
      writer.uint32(24).int32(message.addCount);
    }
    if (message.waterCount !== 0) {
      writer.uint32(32).int32(message.waterCount);
    }
    if (message.goldCount !== 0) {
      writer.uint32(40).int32(message.goldCount);
    }
    if (message.treeGpCount !== 0) {
      writer.uint32(48).int32(message.treeGpCount);
    }
    if (message.property1 !== 0) {
      writer.uint32(56).int32(message.property1);
    }
    if (message.property2 !== 0) {
      writer.uint32(64).int32(message.property2);
    }
    if (message.isUpGrade !== false) {
      writer.uint32(72).bool(message.isUpGrade);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddFriendFavorMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddFriendFavorMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.playerId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.friendId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.addCount = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.waterCount = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.goldCount = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.treeGpCount = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.property1 = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.property2 = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isUpGrade = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddFriendFavorMsg {
    return {
      playerId: isSet(object.playerId) ? globalThis.Number(object.playerId) : 0,
      friendId: isSet(object.friendId) ? globalThis.Number(object.friendId) : 0,
      addCount: isSet(object.addCount) ? globalThis.Number(object.addCount) : 0,
      waterCount: isSet(object.waterCount) ? globalThis.Number(object.waterCount) : 0,
      goldCount: isSet(object.goldCount) ? globalThis.Number(object.goldCount) : 0,
      treeGpCount: isSet(object.treeGpCount) ? globalThis.Number(object.treeGpCount) : 0,
      property1: isSet(object.property1) ? globalThis.Number(object.property1) : 0,
      property2: isSet(object.property2) ? globalThis.Number(object.property2) : 0,
      isUpGrade: isSet(object.isUpGrade) ? globalThis.Boolean(object.isUpGrade) : false,
    };
  },

  toJSON(message: AddFriendFavorMsg): unknown {
    const obj: any = {};
    if (message.playerId !== 0) {
      obj.playerId = Math.round(message.playerId);
    }
    if (message.friendId !== 0) {
      obj.friendId = Math.round(message.friendId);
    }
    if (message.addCount !== 0) {
      obj.addCount = Math.round(message.addCount);
    }
    if (message.waterCount !== 0) {
      obj.waterCount = Math.round(message.waterCount);
    }
    if (message.goldCount !== 0) {
      obj.goldCount = Math.round(message.goldCount);
    }
    if (message.treeGpCount !== 0) {
      obj.treeGpCount = Math.round(message.treeGpCount);
    }
    if (message.property1 !== 0) {
      obj.property1 = Math.round(message.property1);
    }
    if (message.property2 !== 0) {
      obj.property2 = Math.round(message.property2);
    }
    if (message.isUpGrade !== false) {
      obj.isUpGrade = message.isUpGrade;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddFriendFavorMsg>, I>>(base?: I): AddFriendFavorMsg {
    return AddFriendFavorMsg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddFriendFavorMsg>, I>>(object: I): AddFriendFavorMsg {
    const message = createBaseAddFriendFavorMsg();
    message.playerId = object.playerId ?? 0;
    message.friendId = object.friendId ?? 0;
    message.addCount = object.addCount ?? 0;
    message.waterCount = object.waterCount ?? 0;
    message.goldCount = object.goldCount ?? 0;
    message.treeGpCount = object.treeGpCount ?? 0;
    message.property1 = object.property1 ?? 0;
    message.property2 = object.property2 ?? 0;
    message.isUpGrade = object.isUpGrade ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
